app.py

Previously we had the jurisdiction name and round number in the ballot retrieval list name. Now we have the election name (which is user-provided) and the current UTC time to the minute.
This change also improves the "cleaning" done to the name since there are many characters we want to disallow rather than simply spaces. This version allows ASCII letters and numbers, turning everything else into dashes.
Closes #136

feat: include election & date in retrieval list

---

arlo-client/src/components/AuditForms/EstimateSampleSize.test.tsx
arlo-client/src/components/AuditForms/EstimateSampleSize.tsx
arlo-client/src/components/AuditForms/__snapshots__/EstimateSampleSize.test.tsx.snap
arlo-client/src/components/AuditForms/__snapshots__/index.test.tsx.snap
arlo-client/src/components/AuditForms/_mocks.ts
tests/test_bravo.py
tests/test_sampler.py

Seed data can now be a string that includes any characters. I included an emoji in test data just to make sure that'd work. The server previously had defined the maximum length to be 100, so I just left that as-is.
Closes #190

feat: allow arbitrary seed data

---

app.py
arlo-client/docs/api_sequence.md
arlo-client/docs/release_notes.md
arlo-client/docs/style.md
arlo-client/src/components/AuditForms/CalculateRiskMeasurement.tsx
arlo-client/src/components/AuditForms/EstimateSampleSize.test.tsx
arlo-client/src/components/AuditForms/EstimateSampleSize.tsx
arlo-client/src/components/AuditForms/ResetButton.tsx
arlo-client/src/components/AuditForms/SelectBallotsToAudit.test.tsx
arlo-client/src/components/AuditForms/SelectBallotsToAudit.tsx
arlo-client/src/components/AuditForms/index.test.tsx
arlo-client/src/components/AuditForms/index.tsx
arlo-client/src/components/CreateAudit.tsx
arlo-client/src/components/utilities.test.ts
arlo-client/src/components/utilities.ts
tests/test_app.py

This will make testing easier if we're operating against a persistent database (#199) since each election will have its own id and we don't have to worry about rolling back transactions per test. We probably should do that anyway, but this is some cleanup that should have been done a while ago.

refactor: do not assume an election with id '1'

---

.circleci/config.yml
.gitignore
Makefile
Pipfile
Pipfile.lock
app.py
config/__init__.py
config/database.cfg.example
create.py
mypy.ini
resetdb.py
tests/test_app.py

Using sqlite for development and testing is easy, but it differs from postgres in ways that make troubleshooting staging and production issues difficult. This commit switches everything from sqlite to postgres in all environments.
The difficulty I had in making this change was primarily around ensuring we're able to easily provide the application with the right configuration in whatever environment it happens to be running in. For example, we need to continue to respect the `DATABASE_URL` environment variable because that's what heroku is using. However, asking people to set environment variables in their shell or IDE to run Arlo properly is not great.
To address this, I set up a system that vaguely resembles Rails with a `config/database.cfg` that is ignored by git but can have …

refactor(db): exclusively use postgres

---

tests/test_app.py

I've seen issues locally where I'm getting unexpected results in `test_ballot_list_ordering` that imply some data from previous test runs is somehow being included in the db results. This _shouldn't_ happen since each election and its related records should be completely independent. That said, resetting the test database on each test run is still a good idea. Typically this is done by rolling back a transaction, but getting that working was fairly involved and this was a rather simple solution that seems to work.

test(db): reset db on each test run

---

arlo-client/src/components/AuditForms/SelectBallotsToAudit.tsx

Doing math in JavaScript is just begging for floating point problems. For example, `0.55 * 100` is `55.00000000000001`. Yay JavaScript! To work around this we let the built-in number formatter format our percentage values properly.
Closes #213

fix: use `Intl.NumberFormat` to format percentages

---

README.md

self explanatory, using the `[content](link)` syntax without the `https://` was creating an internal link

fix readme voting.works link

---

docker-compose.yml

Previously I'd had a `Dockerfile` in `arlo-client`, but I removed it because it was no longer needed since I could just use the `node` image directly. However, I only changed the config for `client` and not `client-tests`. This commit fixes that problem.

fix(docker): correct build settings for client-tests

---

.gitignore

So [this](https://github.com/votingworks/arlo/commit/615d609b4d0b9f145c9405dc3b89cd4dc0f38bc4#diff-ea3ccf358dc5d823409a493c26b81d93) doesn't happen anymore.

chore: ignore vim temp files

---

app.py

Without this, the `/admin` route is vulnerable to timing attacks: https://en.wikipedia.org/wiki/Timing_attack
I realize this admin setup is intended to be short-lived, but I do not want to leave an obvious security vulnerability in the codebase for any length of time.
I could have used `safe_str_cmp` from `werkzeug.security`, but it just delegates to `hmac.compare_digest` when it's available. Since it was added in Python 3.3, we're fine to use it directly.

fix(security): compare passwords in constant-time

---

arlo.code-workspace

This makes it so you don't have to manually configure it in VS Code.

chore: forward Arlo web port

---

arlo-client/package.json
arlo-client/src/components/AuditFlow/index.test.tsx
arlo-client/src/components/AuditFlow/index_members.test.tsx
arlo-client/src/components/AuditForms/CalculateRiskMeasurement.test.tsx
arlo-client/src/components/AuditForms/index.test.tsx
arlo-client/src/components/testUtilities.ts
arlo-client/src/components/utilities.ts

- Moving `asyncActRender` from utilities to testUtilities so that `@testing-library/react` can stay in devDependencies.
EDIT: Still moving it to testUtilities, but evidently it needs to be in regular dependencies regardless. Oh well.
**New Tests**
- N/A
**Checklist**
*Function*
[] Code is fully functional and ready for review (or is tagged WIP)
[] No errors/warnings in the browser console ( ﾟヮﾟ)/
[] package.json is committed if I added or removed any dependencies
[] Tests added as needed to ensure code base still has 100% passing coverage
[] Tests added as needed to cover new functionality
*Style*
[] Passes linter without errors
[] Code is easily understandable and self-documenting (using naming conventions in keeping with the rest of the codebase)
[] Interfaces all have …

Moving asyncActRender from utilities to testUtilities

---

arlo-client/src/components/Header.test.tsx
arlo-client/src/components/Header.tsx
arlo-client/src/components/__snapshots__/Header.test.tsx.snap

- The logo in the header now is a link doing to /
**New Tests**
- Snapshots updated
**Checklist**
*Function*
[] Code is fully functional and ready for review (or is tagged WIP)
[] No errors/warnings in the browser console ( ﾟヮﾟ)/
[] package.json is committed if I added or removed any dependencies
[] Tests added as needed to ensure code base still has 100% passing coverage
[] Tests added as needed to cover new functionality
*Style*
[] Passes linter without errors
[] Code is easily understandable and self-documenting (using naming conventions in keeping with the rest of the codebase)
[] Interfaces all have 'I' before their names (as in `IAudit`)
[] Comments are only included as needed to explain the 'why' instead of the 'what'
[] Common standards and coding practices are …

Making header logo a link to home

---

docker-compose.yml

The `db` container failed to start because the `9.6` image changed (presumably to the most recent `9.6.x` version) and now wants a password. Since we're only using this for development, I added the environment variable that makes postgres trust incoming requests. This is not suitable for a production environment, so I added a comment to make it clear what this file is for.

build(docker): fixes `docker-compose up`

---

Makefile

It uses the same mechanism as `resetdb`, but sets the environment variable so the test database is used.

fix: make resettestdb work again

---

arlo_server/__init__.py
arlo_server/base.py
config/__init__.py
tests/test_app.py

This provides a cookie-based application session with a secret key from `ARLO_SESSION_SECRET`. If not provided in development or test, a fixed one will be used instead.

feat: enable sessions

---

arlo_server/__init__.py

A bare `except` is considered bad python form, as it probably catches more than intended. This narrows the `except` we're keeping to the specific error we're looking for.
This also removes some `try`/`except` statements that were unnecessary. According to the Flask docs, if `get_json` is unable to parse the JSON value from the request, it'll raise `BadRequest` just as we were doing. So we can just let it follow the default behavior.

fix: make better use of `try`/`except`

---

arlo-client/src/components/AuditForms/EstimateSampleSize.test.tsx
arlo-client/src/components/AuditForms/EstimateSampleSize.tsx
arlo_server/__init__.py
models.py
tests/test_app.py

addresses #301, see that ticket for motivation.
@MorganLove this tweaks the API calls so that `/audit/basic` no longer starts the first round. It just updates the data. You have to explicitly call `/audit/freeze` to mark the audit frozen, and then the `rounds` property appears and the sample set sizes are computed.

Freeze flag and API

---

arlo_server/__init__.py
models.py
tests/test_app_upload_jurisdictions_file.py

~This required a bit of a refactor in order to avoid cycles. Mainly, the application routes have been moved to a file called `routes.py` and a bunch of utility functions were moved to their own files.~
I managed to simply change the order of imports to avoid the cycles. That makes this PR more focused. Will follow up with a refactor later.
Closes #303

feat: add endpoint to handle an election jurisdictions file

---

arlo_server/__init__.py
tests/test_app.py
tests/test_ballot_list.py

In both ballot-list endpoints (per audit board and per jurisdiction),
the round_id parameter was being ignored, so all ballots for all rounds
of the audits were being returned. This adds a filter to the database
query to restrict results to the specified round.
**Testing**
This commit adds a new test for each endpoint with two audit rounds to
ensure this behavior.
It also updates some existing tests that tested the ordering of the
ballot lists. These tests tried to test across multiple rounds of the
audit when there was only one round, so here they are simplified to be
clearer.
**Progress**

Fix ballot-list endpoints to filter by round

---

Makefile
README.md
run-dev.sh

I discovered that in my Ubuntu dev environment, `python3` is by default
`3.6.9`. To be safe, let's use `python3.7` explicitly.
**Testing**
N/A
**Progress**
Note: needs to be merged after #327 because it assumes we've switched to black for `make format-python`

Switch all python3 commands to python3.7

---

arlo-client/src/__snapshots__/App.test.tsx.snap
arlo-client/src/components/CreateAudit.test.tsx
arlo-client/src/components/CreateAudit.tsx
arlo-client/src/components/__snapshots__/CreateAudit.test.tsx.snap
arlo-client/src/types.ts

- lists the audits currently associated with the authenticated user on the home page as link buttons
- POSTs the organization ID of an authenticated AA user to the `/election/new` endpoint so it can be associated with it
**New Tests**
- Testing of new endpoint usage
**Notes**
- When new audits are created, they aren't associated with the authenticated user, so that needs to be done on this PR for it to be functional. @benadida can you do that? EDIT: this will take place on the backend in another PR to match up with this one.
-As it is currently, I am injecting dummy data in to demonstrate the styling. That will be removed before this is merged. EDIT: now cleaned up.

Home list of audits

---

arlo_server/__init__.py
models.py
tests/helpers.py
tests/test_app.py
tests/test_app_upload_jurisdictions_file.py
tests/test_auth.py
tests/test_new_election.py

This restricts creating elections within an organization to audit admins in that organization. It also restricts the jurisdiction file upload API to audit admins for the election.
This also changes the data model to _not_ require an organization for each election. Any elections without an organization are accessible as they were before: by knowing the URL.
Refs #290 
**Testing**
Pulls tests specifically around `/election/new` into their own file and adds tests for various logged-in user scenarios.
**Progress**
There's still more to go to add authorization for all the endpoints that require them. We can use the new `require_audit_admin_for_organization` and `set_logged_in_user` helpers to make this fairly easy, though we'll need another helper for jurisdiction admins.

fix: add authorization to a few endpoints

---

arlo_server/__init__.py
tests/test_app.py
tests/test_report.py

Task: #239 
Adds a section labeled "All Sampled Ballots" to the end of the audit report (only for online audits). In this section, there's a row for each ballot containing info about what happened during the audit:
- The ballot id
- The ticket numbers for each round it was sampled in
- Whether it was audited or not
- The result of that audit
- Any comments
**Testing**
Added a few new test cases:
- Reports for offline audits should not have the "All Sampled Ballots" section
- Ballot interpretations for a one-round audit
- Ballot interpretations for a two-round audit
**Progress**
Ready for review. One outstanding question that I'll note with a PR comment.

Add ballot interpretations to audit report

---

arlo_server/__init__.py
tests/helpers.py
tests/test_app.py
tests/test_audit_basic_update.py
tests/test_audit_status.py

Task: #309 
Adds `contest.isTargeted` to two endpoints:
- `/audit/basic` for creating contests
- `/audit/status` for reading contests
`contest.isTargeted` should be `true` for targeted contests, and `false`
for opportunistic contests.
To maintain backwards compatibility, `/audit/basic` does not require
`contest.isTargeted` yet. It defaults to `true`.
Once the frontend starts sending `isTargeted`, it will become required.
**Testing**
Adds two new tests for `/audit/basic`:
- Creating a contest (happy path)
- Creating a contest without specifying `isTargeted` defaults it to true
Adds one test for `/audit/status` that checks the entire response body in a basic audit.
Also adds some test helpers to facilitate comparing large JSON blobs.
**Progress**

Add contest.isTargeted to /audit/basic and /audit/status

---

arlo_server/models.py
arlo_server/routes.py

Following the direction of a new, separate API for multi-jurisdiction, this PR makes it possible to map an audit board to a round, without requiring it. Much simpler change that lets the current flow work with no front-end changes and only minor backend changes.
Then, the new API calls that @jonahkagan is planning can map audit boards to an explicit round. This might require some slightly more complicated JOINs on API calls that are shared between both flows, but that should be trivial compared to trying to remap the single workflow onto the new data model.
Addresses votingworks/arlo#299

add optional round_id to AuditBoard

---

arlo_server/models.py
arlo_server/routes.py
tests/test_app_upload_jurisdictions_file.py

Since it seems likely we're going to have more "file" objects we're going to have to keep track of, this codifies that into a model.
**Testing**
Covered by existing tests.
**Progress**
This was an opportunistic refactor on the road to making the bulk jurisdictions file upload async.

refactor: extract `File` from `Election` jurisdictions file

---

arlo-client/src/components/CreateAudit.test.tsx
arlo-client/src/components/CreateAudit.tsx
arlo_server/routes.py
tests/test_new_election.py

I noticed a snake-case property snuck in recently, and this fixes it.
**Testing**
Covered by existing tests.
**Progress**
Ideally this would be enforced by a development/test-time wrapper that checks JSON requests & responses for snake casing and raises an error.

fix: use camel case in JSON APIs

---

Pipfile
Pipfile.lock
arlo_server/__init__.py
arlo_server/contests.py
arlo_server/models.py
arlo_server/routes.py
mypy.ini
tests/helpers.py
tests/test_contests.py

Task: #309, #326 
Adds new endpoints for getting and creating/updating contests when setting up an audit:
- `GET /election/<election_id>/contest` - gets a list of all contests for the audit
- `PUT /election/<election_id>/contest` - sets the contests for the audit, overwriting any existing contests
Notably, this new API includes a `jurisdictionIds` field to set the contest universe.
The new endpoints use JSON schema to validate the contests.
**Testing**
Added a new test file with quite a few cases.
**Progress**
Ready for review. Left some open questions as PR comments.

Add /election/<election_id>/contest API

---

arlo_server/__init__.py
arlo_server/jurisdictions.py
arlo_server/routes.py
tests/helpers.py
tests/test_jurisdictions.py

Task: #343 
An endpoint to list all of the jurisdictions in an election, including details about their ballot manifest upload.
Also tweaks the existing /election/<election_id>/jurisdiction/<jurisdiction_id>/manifest endpoint to only initiate ballot sampling when used by the single-jurisdiction flow.
**Testing**
Added new test file testing the endpoint with and without uploading the manifest.
**Progress**
Ready to review.

Add GET /election/<election_id>/jurisdiction

---

arlo_server/__init__.py
arlo_server/models.py
arlo_server/routes.py
bgcompute.py
tests/helpers.py
tests/test_app_upload_jurisdictions_file.py
tests/test_jurisdiction_bulk_update.py
tests/test_process_file.py
util/jurisdiction_bulk_update.py
util/process_file.py

In an effort to not block requests on things that could potentially take a long time, this puts the processing of jurisdiction files in the background.
**Testing**
Adds some new tests for the helper function `process_file` and updates tests to use the new backgrounding flow.
**Progress**
This doesn't require any more changes to make the feature work, unless I missed something. Some concerns I have:
- `bgcompute.py` doesn't seem to catch errors. I'm assuming Heroku will run the `worker` process in the `Procfile` again if it dies, but I don't know for sure.
- What happens if a file is being processed and a new file is uploaded while that is happening? In theory that could leave things in an inconsistent state.
- Did I get the `File` and `Election` relationship right?
- We …

feat: process jurisdiction file uploads in the background

---

tests/test_jurisdictions.py

Without this, `jurisdiction_ids` will always be an empty array. This was breaking `master`. This was a logical merge conflict between the test refactor and making the jurisdictions file upload async.
**Testing**
This PR is all about the testing. So much testing.
**Progress**
It's perfect now and always will be.

fix: proess async jurisdictions file upload

---

arlo_server/auth.py
arlo_server/routes.py
tests/helpers.py
tests/test_auth.py
tests/test_jurisdictions.py
tests/test_new_election.py

Pulls most auth-related functionality out of the mega-file `arlo_server.routes` to `arlo_server.auth`.
**Testing**
Covered by existing tests as there should be no changes in behavior.
**Progress**
I would like to start splitting routes out into their own files and this will help unblock that.

refactor: extract auth functions into module

---

arlo-client/src/components/Audit/ResetButton.test.tsx
arlo-client/src/components/Audit/ResetButton.tsx
arlo-client/src/components/Audit/__snapshots__/ResetButton.test.tsx.snap

- Made the reset button not show if the user is authenticated, since it's only useful on the single page flow, and hazardous on the multi jurisdiction flow.
**Testing**
- Testing that it vanishes when it isn't wanted
**Progress**
- Should be good to go!

Hiding reset button when user is authenticated

---

arlo-client/src/types.ts
arlo_server/models.py
arlo_server/routes.py
tests/conftest.py
tests/test_app.py
tests/test_app_upload_jurisdictions_file.py
tests/test_audit_basic_update.py
tests/test_audit_status.py
tests/test_auth.py
tests/test_ballot_list.py
tests/test_contests.py
tests/test_jurisdiction_bulk_update.py
tests/test_jurisdictions.py
tests/test_new_election.py
tests/test_report.py

Task: #345 
Unblocks: #349 
Adds `auditName` as a required field to `POST /election/new`. Also moves `Election.name` to `Election.election_name`.
Note: does not break `/audit/basic`, which still expects the `name` field (which corresponds to `election_name`.
**Testing**
Tests have to be updated everywhere because they all rely on `/election/new` to initialize the election. We pull this out into a universal fixture. Yay dependency injection!
Also adds one test to ensure `auditName` is required.
**Progress**
Ready for review. Sorry for the tedious test changes (just know they were even more tedious to make than they are to review!)

Add Election.audit_name required field

---

arlo-client/src/__snapshots__/App.test.tsx.snap
arlo-client/src/components/Audit/Setup/Contests/index.tsx
arlo-client/src/components/Audit/Setup/Participants/index.tsx
arlo-client/src/components/CreateAudit.test.tsx
arlo-client/src/components/CreateAudit.tsx
arlo-client/src/components/__snapshots__/CreateAudit.test.tsx.snap
arlo-client/src/test/specs/helpers.ts
arlo-client/src/types.ts
arlo_server/models.py
arlo_server/routes.py
tests/conftest.py
tests/test_app.py
tests/test_app_upload_jurisdictions_file.py
tests/test_audit_basic_update.py
tests/test_audit_status.py
tests/test_auth.py
tests/test_ballot_list.py
tests/test_contests.py
tests/test_jurisdiction_bulk_update.py
tests/test_jurisdictions.py
tests/test_new_election.py
tests/test_report.py

- Has the front end post an `auditName` field to the `/election/new` endpoint
**Testing**
- Tests that it passes as expected for both authenticated and unauthenticated users, and is required
- Updates snapshots
**Progress**
- Do we need to verify the uniqueness of the audit name at this time?
- The back end needs to use the value as passed back when creating an audit, still

Audit name

---

docs/api-proposal/proposed-routes.md

I changed the URL to not conflict in #364, so this updates the docs.
**Testing**
Docs-only, no tests.
**Progress**
Should be good to go.

doc: update URL for election settings

---

arlo-client/src/components/CreateAudit.test.tsx
arlo-client/src/components/CreateAudit.tsx
arlo_server/models.py
arlo_server/routes.py
tests/conftest.py
tests/helpers.py
tests/test_app.py
tests/test_audit_status.py
tests/test_auth.py
tests/test_ballot_list.py
tests/test_jurisdiction_bulk_update.py
tests/test_jurisdictions.py
tests/test_new_election.py
tests/test_report.py

Task: #358 
Instead of using the existence of Election.organization_id to tell us whether we're in the old single-jurisdiction flow or the new multi-jurisdiction flow, add a flag that tells us.
**Testing**
Updated existing tests to expect this flag. Specifically, `test_jurisdictions` tests the ballot manifest upload endpoint, which now relies on this flag.
**Progress**
Ready for review. @MorganLove I tried my hand at updating the frontend code to send this flag (and the frontend tests), since I figured it would be a small change. Let me know how you feel about it.

Add Election.is_multi_jurisdiction flag

---

tests/helpers.py

Changes `compare_json` to keep track of the key path that lead to the values being compared and ensures that the path is included in the error message. The original assertion message is still included, but we now include a key path like so: `root["rounds"][0]["startedAt"]`.
**Testing**
`compare_json` doesn't have any tests of its own behavior, but is used in lots of tests.
**Progress**
I made this change while working on #344 since I was changing some deeply-nested fields and wasn't sure exactly which value `compare_json` was complaining about.

test: improve error messages for `compare_json`

---

arlo_server/jurisdictions.py
arlo_server/models.py
arlo_server/routes.py

This will make it easier to process the ballot manifest file in the background (#344), re-using existing background file processing code.
**Testing**
Covered by existing tests as this should not change behavior.
**Progress**
This is progress toward #344.

refactor: extract ballot manifest file fields

---

arlo_server/routes.py
audits/sampler.py
tests/test_sampler.py

The `contest` and `batch_results` parameters are not needed in `draw_sample`, so this PR removes them.
**Testing**
Updated existing tests.
**Progress**

Remove unused params from sampler.draw_sample

---

arlo_server/__init__.py
arlo_server/sample_sizes.py
tests/conftest.py
tests/test_contests.py
tests/test_sample_sizes.py

This endpoint returns the estimated sample size options for the current round (the frontend will only use this for the first round for now, but we'll need the logic for later rounds as well, so it's implemented). This is based on the `compute_sample_sizes` function from the single-jurisdiction flow.
**Testing**
Added some basic tests for the new endpoint - two error cases where we don't have enough of the audit set up done to compute the sample sizes, one happy path.
**Progress**

Add GET /election/<election_id>/sample-sizes

---

API.md
arlo-client/docs/api_sequence.md
arlo-client/src/components/Audit/SelectBallotsToAudit.tsx
arlo_server/jurisdictions.py
arlo_server/models.py
arlo_server/routes.py
audits/sampler.py
bgcompute.py
tests/test_app.py
tests/test_audit_status.py
tests/test_jurisdictions.py
util/ballot_manifest.py
util/isoformat.py
util/process_file.py

This tries to maintain as much backward-compatibility as possible, but one breaking change is that the endpoint changed from POST to PUT. I updated the API docs and the frontend code to use PUT.
**Testing**
Adjusts current tests, but doesn't really add any new ones.
**Progress**
The front-end still needs to be updated to check the `ballotManifest.processing.status` value.

feat: process ballot manifest uploads in the background

---

arlo_server/auth.py
arlo_server/contests.py
arlo_server/election_settings.py
arlo_server/jurisdictions.py
arlo_server/routes.py
arlo_server/sample_sizes.py

Closes #380
Refs #290
Decorating a route using `with_election_access` allows the route to be defined with an `election` parameter that will be be provided only if the election exists and the current user has access to it.
**Testing**
Existing tests should cover this okay, but to really test it I'd have to figure out how to test this more directly. I'm not sure what the right approach is there. Maybe create another Flask app per test that I then add test routes to?
**Progress**
This is a building block toward #290.

refactor: introduce election access route decorator

---

arlo-client/src/components/Atoms/Sidebar.test.tsx
arlo-client/src/components/Atoms/Sidebar.tsx
arlo-client/src/components/Atoms/__snapshots__/Sidebar.test.tsx.snap
arlo-client/src/components/Audit/Setup/Contests/index.test.tsx
arlo-client/src/components/Audit/Setup/Contests/index.tsx
arlo-client/src/components/Audit/Setup/Participants/index.test.tsx
arlo-client/src/components/Audit/Setup/Participants/index.tsx
arlo-client/src/components/Audit/Setup/Review/index.tsx
arlo-client/src/components/Audit/Setup/Settings/index.tsx
arlo-client/src/components/Audit/Setup/_mocks.ts
arlo-client/src/components/Audit/Setup/index.test.tsx
arlo-client/src/components/Audit/Setup/index.tsx
arlo-client/src/components/Audit/index.tsx
arlo-client/src/components/Audit/useSetupMenuItems.tsx

- Lifting up and extracting out state management for the setup stages so we can add in logic for controlling navigation between them based on polling the data.
- Corrected `/jurisdictions/file` to `/jurisdiction/file` to comply with the recent endpoint fix
**Testing**
- Updating snapshots and test implementation
**Progress**
- I'm still working on doing the actual polling logic, but I wanted to get this one pushed up before it got too big and scope creep set in.

Audit setup stages ui management

---

.circleci/config.yml
.pylintrc
Makefile
Pipfile
Pipfile.lock
bgcompute.py
tests/test_app.py
tests/test_app_upload_jurisdictions_file.py
tests/test_audit_basic_update.py
tests/test_election_settings.py
tests/test_new_election.py
tests/test_process_file.py
util/jurisdiction_bulk_update.py
util/process_file.py

This enables a single rule, `singleton-comparison`, which was pretty easy to fix all the violations for. The idea is to add rules over time to the `.pylintrc` and enforce them in CI to ensure we don't regress.
**Testing**
n/a
**Progress**
n/a

test(pylint): enable pylint in CI

---

.pylintrc
arlo_server/contests.py
arlo_server/election_settings.py
arlo_server/jurisdictions.py
arlo_server/models.py
arlo_server/routes.py
arlo_server/sample_sizes.py
audit_math/bravo.py
audit_math/macro.py
audit_math/sampler.py
audit_math/sampler_contest.py
bgcompute.py
tests/conftest.py
tests/test_app.py
tests/test_app_upload_jurisdictions_file.py
tests/test_audit_basic_update.py
tests/test_audit_status.py
tests/test_auth.py
tests/test_ballot_list.py
tests/test_bravo.py
tests/test_contests.py
tests/test_election_settings.py
tests/test_jurisdictions.py
tests/test_macro.py
tests/test_new_election.py
tests/test_sample_sizes.py
util/ballot_manifest.py
util/binpacking.py
util/isoformat.py
util/jurisdiction_bulk_update.py

In most cases I simply removed the unused imports, but in a couple cases I used the imported symbols as type annotations.
**Testing**
n/a
**Progress**
n/a

test(pylint): enforce `unused-import` rule

---

arlo_server/contests.py
tests/routes_tests/test_contests.py

Wraps the /election/<election_id>/contest response array in an object, as agreed upon as a best practice here: https://github.com/votingworks/arlo/pull/377#discussion_r396810023. Should be fine since it's not depended on yet.
Also did some minor code cleanup (in a separate commit).
**Testing**
Modified existing tests to cover.
**Progress**

Wrap /election/<election_id>/contest response array in an object

---

arlo_server/contests.py
arlo_server/election_settings.py
arlo_server/routes.py
mypy.ini
util/jsonschema.py

This ensures that `additionalProperties` and `required` are set on objects, and recursively checks schemas. This will not help with situations such as adding a property but forgetting to add it to `required`, but is better than the status quo.
**Testing**
Tests are covered by validation.
**Progress**
This was just something I noticed and wanted to fix.

refactor: validate JSON schemas thoroughly

---

.pylintrc

We had no violations of this rule, so this did not require any changes other than configuring pylint to look for it.
**Testing**
n/a
**Progress**
n/a

test(pylint): enforce `dangerous-default-value` rule

---

.pylintrc
arlo_server/routes.py
audit_math/macro.py
audit_math/sampler.py
tests/audit_math_tests/test_sampler.py
tests/routes_tests/test_new_election.py
tests/routes_tests/test_sample_sizes.py
tests/test_rounds.py

This fixes the violations in a variety of ways:
- underscore-prefix arguments we want to keep and can change the name
- disable specific instances where we can't fix yet
- remove unused arguments when possible
**Testing**
n/a
**Progress**
n/a

test(pylint): enable `unused-argument` rule

---

Makefile
arlo_server/contests.py
arlo_server/rounds.py
tests/conftest.py
tests/routes_tests/test_contests.py
tests/test_rounds.py

This adds a field `currentRoundStatus` to each contest in the output of
/election/<election_id>/contest. `currentRoundStatus` is null until the
audit starts. Once the audit starts, it is an object with two fields:
- `isRiskLimitMet` - whether the calculated risk measurement for that
contest meets the audit risk limit (or null if we're not done auditing
ballots for that contest yet)
- `numSampledBallots` - how many ballot samples were drawn for this contest
**Testing**
Updating existing tests for the null case. Added a new test to test the status once the round has started.
**Progress**

Add currentRoundStatus to list contests endpoint

---

arlo_server/models.py
tests/routes_tests/test_jurisdictions.py
tests/util_tests/test_jurisdiction_bulk_update.py
tests/util_tests/test_process_file.py
util/process_file.py

`Jurisdiction` names must now be unique per `Election`, and `Batch` names must now be unique per `Jurisdiction`. Since these are handled via database constraints, we'll get an exception whenever we try to commit a session that would violate those constraints. It turns out that capturing and handling such an error correctly in `process_file` required some changes. We now roll back the session on error, then update the file processing metadata.
Closes #389
**Testing**
Adds a new test for `process_file` to ensure database constraint errors are recorded properly.
**Progress**
This puts the raw error database message into `processing_error`, which is probably not suitable for display to an end user. We should consider catching the error at a higher level than `process_file` and …

fix: require uniqueness of jurisdiction & batch names

---

arlo_server/__init__.py

Webpack injects some JavaScript into the HTML when running `react-scripts build`, and the default CSP provided by Talisman is too strict. This changes the CSP to allow unsafe inline scripts, though the longer-term fix is to generate a nonce and provide it to both Webpack and Talisman.
**Testing**
n/a
**Progress**
This was broken by #399.

fix(csp): allow unsafe inline scripts for now

---

arlo_server/models.py

Redefines the base model class to add `created_at` and `updated_at` timestamp fields to all models. Based on: https://flask-sqlalchemy.palletsprojects.com/en/2.x/customizing/#model-class.
**Testing**
Existing tests pass. Also manually checked the fields exist in the db.
**Progress**
Ready to review.

Add created_at and updated_at timestamps to all db models

---

arlo_server/models.py
arlo_server/rounds.py
arlo_server/routes.py

After #404, the fields should have the same value, so no reason to have both around and confuse people. No change to any APIs.
**Testing**
Existing tests pass.
**Progress**

Remove Round.started_at and use Round.created_at

---

.circleci/config.yml
Makefile
package.json

Makefile improvements:
- Pull out the command to run pipenv into a variable
- Add `FILE` and `FLAGS` variables to make test-server
- Use those variables to implement the modularized server test commands
- Name server targets consistently (always use "server", not "python")
- Add a command `make python-shell` to run a python shell
Also adds Python lint and typecheck to the pre-commit hooks
**Testing**
Ran a smattering of the commands
**Progress**

Makefile improvements

---

Makefile

We now have to explicitly set `FLASK_ENV` to something other than `production` if we don't want it to be `production`. This makes `make resetdb` default to `development`, but allows overriding it since `make resettestdb` does exactly that.
**Testing**
n/a
**Progress**
This was broken by #399.

fix: ensure `make resetdb` works

---

arlo_server/contests.py
arlo_server/jurisdictions.py
arlo_server/models.py
tests/routes_tests/test_jurisdictions.py
util/jsonschema.py

Task: #338 
This adds a field `currentRoundStatus` to each jurisdiction in the output of /election/<election_id>/jurisdiction. `currentRoundStatus` is null until the audit starts. Once the audit starts, it is an object with three fields:
- `status`:
- `NOT_STARTED` = the jurisdiction hasn’t set up any audit boards
- `IN_PROGRESS` = the audit boards are set up
- `COMPLETE` = all of the audit boards have signed off on their ballots
- `numBallotsSampled` - how many ballot samples were drawn for this jurisdiction
- `numBallotsAudited` - how many of the drawn ballot samples have been audited so far
Also adds a new field `signed_off_at` to the `AuditBoard` data model, signifying when the audit board members have finalized their audit results.
While I was at it, I wrapped the …

Add currentRoundStatus to list jurisdictions endpoint

---

arlo_server/auth.py
arlo_server/contests.py
arlo_server/election_settings.py
arlo_server/jurisdictions.py
arlo_server/rounds.py
arlo_server/routes.py
arlo_server/sample_sizes.py
tests/conftest.py
tests/helpers.py
tests/routes_tests/test_audit_status.py
tests/routes_tests/test_auth.py
tests/routes_tests/test_ballot_list.py
tests/routes_tests/test_report.py
tests/test_app.py

Adds a route decorator `@with_jurisdiction_access`. This decorator requires jurisdiction admin (JA) authorization, checks that it matches the given election/jurisdiction ids, and loads the election and jurisdiction objects.
Also modifies `@with_election_access` to not take a user type and only accept audit admin (AA) authorization.
To simplify permissions for the time being, AAs and JAs will not share any routes. JA routes will always have a `jurisdiction_id` in the path so we can easily check that they are trying to access the jurisdiction for which they are authorized.
**Testing**
Lots of new tests here, trying to cover every case of incorrect authorization - could use a good review to make sure I'm not missing something.
Here's a summary:
- …

Add @with_jurisdiction_access route decorator

---

arlo-client/src/components/Audit/CalculateRiskMeasurement.test.tsx
arlo-client/src/components/Audit/EstimateSampleSize.test.tsx
arlo-client/src/components/Audit/SelectBallotsToAudit.test.tsx
arlo-client/src/components/Audit/Setup/Contests/index.test.tsx
arlo-client/src/components/Audit/Setup/Participants/index.test.tsx
arlo-client/src/components/Audit/Setup/Settings/index.test.tsx
arlo-client/src/components/Audit/Setup/index.test.tsx
arlo-client/src/components/Audit/_mocks.ts
arlo-client/src/components/Audit/index.test.tsx
arlo-client/src/components/DataEntry/MemberForm.test.tsx
arlo-client/src/components/DataEntry/index.test.tsx
arlo-client/src/components/DataEntry/index_members.test.tsx

- I initially had the sequence of states of return values from the `/status` endpoint as a reference, and then repurposed it as mock data. The problem was that while initially it was fine to have it as an array, it quickly became bloated, unwieldy, and incredibly difficult to maintain and update. So I went back through and converted it to an object with named keys that (hopefully) make more sense.
**Testing**
- Passes existing tests.
**Progress**
- Should be good, though feedback on if the names I used are semantic enough would be nice.

refactoring Audit/_mocks

---

arlo-client/wdio.conf.js

- Theorizing that running the tests in parallel with each other might be causing them to interfere with each other and/or burden the bgcompute script, limiting the `maxInstances` to 1.
- Increasing the timeout length from 10000 to 20000 to give more time for background processes to complete before bailing on the tests.
**Notes**
- My observation is that the test failures have nothing to do with the tests themselves. The parts that fail are invariably passed successfully in other portions of the same test run, and when re-run the failures take place in completely disparate parts of the suite. However, they all tend to be related to waiting on the background processes. Therefore, helping the tests cope with them more patiently should reduce the flakiness. :crossed_fingers:

Stabilize E2E tests

---

mypy.ini
tests/__init__.py
tests/conftest.py
tests/helpers.py
tests/routes_tests/test_audit_basic_update.py
tests/routes_tests/test_audit_status.py
tests/routes_tests/test_ballot_list.py
tests/routes_tests/test_contests.py
tests/routes_tests/test_election_settings.py
tests/routes_tests/test_jurisdictions.py
tests/routes_tests/test_new_election.py
tests/routes_tests/test_report.py
tests/routes_tests/test_sample_sizes.py
tests/test_app.py
tests/test_app_upload_jurisdictions_file.py
tests/test_rounds.py

Adds an `assert_ok` test helper to check for successful API responses.
In order to get the assertion error messages to display well, we have to
do two things:
- Add `__tracebackhide__ = True` to the helper function, which treats it
as an inline assertion in the test error reporting
- Call `pytest.register_assert_rewrite("tests.helpers")`, which passes
through the assert error messages to the test error reporting
The latter change required making creating a `tests/__init__.py` file,
which had the bonus side-effect of causing `mypy` to actually run on the
tests for the first time (who knew?) So we also fix some type errors.
Last, we go and use `assert_ok` in all the appropriate places in existing tests (fairly straightforward find and replace).
**Testing**
Modifies existing …

Add assert_ok test helper and typecheck tests

---

arlo_server/__init__.py
arlo_server/audit_boards.py
arlo_server/models.py
arlo_server/routes.py
tests/conftest.py
tests/helpers.py
tests/routes_tests/test_audit_boards.py
tests/routes_tests/test_audit_status.py
tests/routes_tests/test_jurisdictions.py
tests/routes_tests/test_report.py
util/group_by.py

Adds an endpoint
`POST
/election/<election_id>/jurisdiction/<jurisdiction_id>/round/<round_id>/audit-board`
that jurisdiction admins can use to create audit boards.
When the audit boards are created, the sampled ballots for that round
are divvyed up as fairly as possible between the audit boards.
Also adds a db constraint that audit board names must be unique within a
jurisdiction for each round.
**Testing**
Added a variety of new test cases for the endpoint.
**Progress**

Add endpoint for jurisdiction admins to create audit boards

---

tests/routes_tests/test_audit_boards.py
tests/routes_tests/test_audit_status.py
tests/routes_tests/test_auth.py
tests/routes_tests/test_ballot_list.py
tests/routes_tests/test_contests.py
tests/routes_tests/test_report.py
tests/util_tests/test_binpacking.py

This ensures that mypy will typecheck them. mypy doesn't recursively
check directories without an `__init__` file. See: https://github.com/python/mypy/issues/6385.
**Testing**
N/A
**Progress**

Add __init__ files to test packages

---

arlo_server/audit_boards.py
arlo_server/models.py
tests/routes_tests/test_audit_boards.py

Adds `GET
/election/<election_id>/jurisdiction/<jurisdiction_id>/round/<round_id>/audit-board`, which a jurisdiction admin can use to get the list of audit boards they created for the round, as well as the status (ballots sampled, ballots audited) for each audit board.
**Testing**
Adds new test cases for no audit boards, one audit board, two audit boards, and audit boards in round 2 of the audit. In each test case, tries out various stages (before the audit boards start, once they've audited some ballots, once they've finished auditing ballots and signed off).
**Progress**
Ready to review.

Add list audit boards endpoint for jurisdiction admins

---

.pylintrc

Enables the `syntax-error` rule for pylint. No syntax errors to fix.
**Testing**
N/A
**Progress**
Ready.

pylint: enable syntax-error rule

---

arlo_server/models.py
arlo_server/rounds.py
tests/test_rounds.py

Adds `GET /election/<election_id>/jurisdiction/<jurisdiction_id>/round` to list audit rounds when logged in as a jurisdiction admin.
This is pretty much the only piece of functionality that is identical for audit admins and jurisdiction admins, but instead of reusing the same endpoint, we make a new one. This has two benefits:
- All jurisdiction admin endpoints follow the same url scheme, which includes the jurisdiction id. So we can always check that the user is requesting info about district they are authorized for.
- Permissions are simpler to think about and implement. Every endpoint can only be accessed by one user type.
**Testing**
Updated the test cases to also try the same requests as a JA and expect the same results. It would be a bit nicer to have separate test …

Add list rounds endpoint for jurisdiction admins

---

arlo-client/src/components/Audit/Setup/Contests/__snapshots__/index.test.tsx.snap
arlo-client/src/components/Audit/Setup/Contests/_mocks.ts
arlo-client/src/components/Audit/Setup/Contests/index.test.tsx
arlo-client/src/components/Audit/Setup/Contests/index.tsx
arlo-client/src/components/Audit/Setup/Contests/schema.ts
arlo-client/src/components/Audit/Setup/Contests/types.ts
arlo-client/src/components/Audit/Setup/Contests/useContestsApi.ts
arlo-client/src/components/Audit/Setup/Participants/index.tsx
arlo-client/src/components/Audit/Setup/__snapshots__/index.test.tsx.snap
arlo-client/src/components/Audit/Setup/index.test.tsx
arlo-client/src/components/Audit/_mocks.ts
arlo-client/src/components/Audit/index.tsx
arlo-client/src/components/Audit/useSetupMenuItems/getJurisdictionFileStatus.test.ts
arlo-client/src/components/Audit/useSetupMenuItems/getJurisdictionFileStatus.ts
arlo-client/src/components/Audit/useSetupMenuItems/getRoundStatus.test.ts
arlo-client/src/components/Audit/useSetupMenuItems/getRoundStatus.ts
arlo-client/src/components/Audit/useSetupMenuItems/index.ts
arlo-client/src/components/CreateAudit.tsx
arlo-client/src/components/DataEntry/Ballot.test.tsx
arlo-client/src/components/__snapshots__/CreateAudit.test.tsx.snap
arlo-client/src/setupProxy.js
arlo-client/src/types.ts
arlo_server/routes.py
tests/routes_tests/test_audit_status.py

- Using the dedicated endpoints for GETting and PUTting contests to the backend from the AA setup screens for targeted and opportunistic contests using a custom hook.
**Testing**
- ~TODO~ Test all api interactions and states
**Progress**
- Ready for review!
- The component for selecting the jurisdictions will be in another PR to maintain manageable sizes

Adding contests api to AA setup 

---

arlo-client/src/components/CreateAudit.test.tsx
arlo-client/src/components/CreateAudit.tsx
arlo-client/src/types.ts

- The title in the buttons for the list on the Create Audit page of already-created audits associated with the authenticated user was still just `name` instead of either `auditName` or `electionName`, so I changed it to `auditName` as is proper.
**Testing**
- Updated the api mocks to reflect the change
**Progress**
- All good!

Changing to display audit names on audit list

---

arlo_server/auth.py
arlo_server/routes.py
tests/conftest.py
tests/helpers.py
tests/routes_tests/test_auth.py
tests/routes_tests/test_new_election.py

Adds a user type for audit boards. This user type is a bit different for a couple of reasons:
- It doesn't correspond to one real world person, it corresponds to the entire audit board.
- It's not represented by a User record in the database, but rather by the AuditBoard record
- The audit board logs in by hitting `GET /auditboard/<passphrase>`, instead of using auth0 with email/password.
This PR:
- Adds the new user type
- Implements the login flow for audit boards
- Adds a `with_audit_board_access` decorator for routes that
should be restricted to audit board users
- Updates the session data format and auth helper functions to accommodate the differences outlined above
**Testing**
Adds a bunch of new test cases:
- test_audit_board_log_in
- test_auth_me_audit_board
- …

Authorization for audit boards

---

arlo_server/__init__.py
config/__init__.py

`Request.trusted_hosts` expects a hostname (e.g. foo.com), and was previously being given a full url (e.g. https://foo.com). This resulted in the app returning the error: `Host \"foo.com\" is not trusted"` when trying to access `request.host` in the audit admin login endpoint handler.
Also added a fix to the configuration of the `HTTP_ORIGIN` env var for the Heroku Review Apps flow.
**Testing**
Manually tested on this branch's staging deploy, which now works.
**Progress**

Fix Request.trusted_hosts to take host, not entire http origin url

---

arlo_server/__init__.py

When our app is deployed on Heroku, the Heroku router terminates https
and sends requests to our app using http. This meant that our app
thought its url was using the http scheme rather than https, so when it
constructed redirect_uris for auth0, they used http.
Luckily, Heroku sets the `X-Forwarded-Proto` header to `https`, and this
middleware reads that header and configures the Flask app accordingly.
https://flask.palletsprojects.com/en/1.1.x/deploying/wsgi-standalone/?highlight=proxyfix#proxy-setups
**Testing**
Manually tested I could log in via auth0 on this PR's staging deploy (and locally).
**Progress**

Add ProxyFix middleware to set app http scheme to https

---

arlo_server/audit_boards.py
tests/routes_tests/test_audit_boards.py

Adds `POST /election/<election_id>/jurisdiction/<jurisdiction_id>/round/<round_id>/audit-board/<audit_board_id>/sign-off` (whew, that's a mouthful). This endpoint allows an audit board to finalize their audit results. When the last audit board in all the jurisdictions with sampled ballots signs off, the round ends and the risk measurements are calculated for each contest.
**Testing**
Added some new tests to check:
- The endpoint works
- Validation for the POST body (proper format, contains the right names)
- The audit board can't sign off til they finish auditing their ballots
- The round doesn't end until all jurisdictions set up audit boards and all audit boards sign off
**Progress**

Add audit board sign-off endpoint

---

arlo_server/audit_boards.py
tests/routes_tests/test_audit_boards.py

The passphrase is needed for the frontend to create the audit board login PDFs.
**Testing**
Updated existing tests.
**Progress**

Return audit board passphrase in JA audit board list endpoint

---

arlo-client/package.json
package.json

`tsc` is pretty slow. We shouldn't have to wait for it to typecheck the whole client if we only make changes to the server.
Note: we have to use `bash -c tsc` instead of just `tsc` because `lint-staged` passed in an array of filenames to `tsc` but `tsc` has to run on the whole project, so we want to ignore the arguments.
**Testing**
Manually tested that a staged tsx file with a type error causes tsc to fail on commit.
**Progress**

Only run tsc pre-commit hook when ts/tsx files change

---

arlo_server/ballots.py
tests/conftest.py
tests/routes_tests/test_audit_boards.py
tests/routes_tests/test_ballots.py

Adds a new endpoint `GET /election/<election_id>/jurisdiction/<jurisdiction_id>/round/<round_id>/ballot-draws` that requires jurisdiction admin authorization (based on the `/ballot-list` endpoint).
**Testing**
Added some new tests.
**Progress**

Add ballot draws endpoint for jurisdiction admins

---

arlo_server/audit_boards.py
arlo_server/routes.py
arlo_server/sample_sizes.py
audit_math/bravo.py
tests/audit_math_tests/test_bravo.py

The `sample_results` argument in some places had an unnecessary level of nesting, and it was confusing me. All of the functions only use results for a single contest, so we standardize around that format.
Though maybe there's a reason for this that I'm missing...
**Testing**
Existing tests cover.
**Progress**

Refactor audit math sample results

---

arlo-client/package.json

Previously, they were set to have a coverage threshold of 0%, which
was a bit confusing because they still showed up in the coverage report
as uncovered.
**Testing**
Ran coverage
**Progress**
Ready

Ignore wdio specs in test coverage

---

arlo_server/ballots.py
arlo_server/contests.py
arlo_server/jurisdictions.py
arlo_server/models.py
arlo_server/rounds.py
arlo_server/routes.py
tests/test_rounds.py

Instead of using `SampledBallot.batch_id` and `SampledBallot.ballot_position` as a primary key, use a new field, `SampledBallot.id`. `SampledBallotDraw` is updated to reference this new primary key.
This is trading off having to do a few more joins for an easier to understand data model.
This sets up my next PR which adds a new model that references `SampledBallot`.
Also replaced some calls to `joinedload` with the even cooler `contains_eager`, which just tells Sqlalchemy that the joins needed for accessing relationship properties on the returned model instances are already in the query.
**Testing**
Existing tests cover (with minor modifications)
**Progress**

Replace SampledBallot composite primary key with SampledBallot.id

---

.circleci/config.yml
.coveragerc
.gitignore
Makefile
Pipfile
Pipfile.lock

Sets up `pytest-cov`, and then locks in the coverage at a 97.47% coverage
threshold. Any regressions below that threshold will fail the tests on
CI.
**Testing**
N/A
**Progress**
Ready

Add test coverage to backend

---

arlo_server/__init__.py
tests/test_app.py

`static_url_path` is set to the directory name of `static_folder` by
default. But our app already expects static files to be served from
root. This was working fine before
https://github.com/votingworks/arlo/pull/450/files.
**Testing**
Reset the existing test case to previous behavior (shouldn't have changed in the first place)
**Progress**

Fix static url path

---

.coveragerc

Messed up the blob for excluding test files themselves from coverage checking.
Had to update the coverage percentage as well because a lot more code just got
excluded (previously, the tests were accidentally getting checked and
included in the total number of lines, which made the coverage
percentage appear higher than it actually was).
**Testing**
N/A
**Progress**
Ready

Fix test coverage blob to exclude tests

---

arlo_server/routes.py
tests/routes_tests/test_auth.py

The audit board flow needs to load the audit board info as its first request when the page loads, so we implement `/auth/me` for audit board users.
**Testing**
Modified existing test and added new test for not logged in users hitting /auth/me.
**Progress**
Ready.

Audit board /auth/me

---

arlo-client/src/setupProxy.js
arlo_server/auth.py
arlo_server/routes.py
arlo_server/superadmin.py
config/__init__.py
tests/routes_tests/test_auth.py

Same approach we've taken for OAuth URLs, now for superadmins, with its own independent tenant. Difference is this manages a separate session variable and sends the user to a different URL, `/superadmin/`.

added auth0 integration for superadmins

---

arlo_server/routes.py

This is better for security, and also solves the annoying issue where logging in as a jurisdiction admin that isn't in the database means we were stuck in a loop.

require fresh logins from oauth providers

---

arlo_server/ballots.py
tests/routes_tests/test_ballots.py

Previously, we just returned an empty list. But the "create audit boards" screen needs to show how many ballots were sampled for the jurisdiction.
**Testing**
Updated test case.
**Progress**
Ready

Allow JA to list ballots before audit boards created

---

arlo-client/src/components/Audit/Setup/Participants/index.tsx

- Tweaked condition for editing/replace state of form for jurisdictions upload and used `useEffect` instead of setting it from props.
**Testing**
- none yet
**Progress**
- This seems like it fixes things

bugfix in jurisdictions upload

---

arlo-client/src/setupProxy.js

#491 introduced a bug because the new route it created for JAs `/election/:electionId/jurisdiction/:jurisdictionId` matched the proxy patterns. This updates the proxy patterns to exclude that route.
**Testing**
Manual test
**Progress**
Ready

Fix jurisdiction url proxy patterns

---

arlo-client/src/components/CreateAudit.tsx

- Made the create new form only appear for unauthenticated and audit admin users
**Testing**
- not touched
**Progress**
- It works, but tests aren't updated

Removing create audit form from ja flow

---

arlo-client/src/components/Audit/RoundManagement/QRs.tsx
arlo-client/src/components/Audit/RoundManagement/generateSheets.ts
arlo-client/src/components/Audit/RoundManagement/index.tsx

- Added in the invisible QR code element so it could be grabbed and injected into the sheet.
- Corrected the expected return from `/ballot-draws` to have `{ ballotDraws: [] }` instead of `{ ballots: [] }` so the other sheets would generate.
**Testing**
- none yet
**Progress**
- It works for me.

Fixing the download sheets

---

arlo_server/ballot_manifest.py
arlo_server/routes.py
tests/routes_tests/test_jurisdictions.py
tests/test_app_upload_jurisdictions_file.py
util/process_file.py

Adds two new endpoints, both with AA permissions:
- `GET /election/<election_id>/jurisdiction/file/csv` - downloads the jurisdictions file
- `GET /election/<election_id>/jurisdiction/<jurisdiction_id>/ballot-manifest/csv` - downloads the jurisdiction's ballot manifest file
**Testing**
Added tests to cover
**Progress**
Ready

Download paths for jurisdictions file and ballot manifest in API

---

arlo_server/models.py
tests/test_app_upload_jurisdictions_file.py

This ensures that they will always match the emails we get back from
auth0, which are all lowercased.
**Testing**
Added a test case
**Progress**
Ready

Lowercase all user emails

---

arlo_server/__init__.py
arlo_server/routes.py
arlo_server/static.py

I think we should move to all APIs served from `/api` to make this easier to manage over time, but I believe this approach will work just fine for now.

default to serving react

---

arlo_server/__init__.py

Mixing our static handling and Flask's was a bad idea. Turning off Flask's.

remove default static folder handling

---

arlo_server/ballots.py
arlo_server/models.py
tests/helpers.py
tests/routes_tests/test_ballots.py

A new endpoint that returns the sampled ballots, not sampled ballot draws, for an audit board. They only need to know about the unique ballots, not the samples (which might include the same ballot multiple times).
**Testing**
Added new tests
**Progress**
Ready

Audit board list ballots endpoint

---

tests/util_tests/test_csv_parse.py
util/csv_parse.py

Previously, we used whatever headers were passed in (which could have a
different case), which could cause the consuming code to break.
**Testing**
Updated tests and added new test case
**Progress**
Ready

Use normalized headers when converting to dicts in parse_csv

---

arlo-client/src/components/Audit/RoundManagement/generateSheets.ts
arlo-client/src/components/Audit/RoundManagement/index.tsx

`ballot.auditBoard` is null until the audit boards get created, so we
need to reload the ballots after we create the audit boards.
**Testing**
**Progress**
Ready

Reload ballots after audit board creation

---

arlo-client/src/App.tsx
arlo-client/src/CreateSingleJurisdictionAudit.tsx
arlo-client/src/components/CreateAudit.tsx

Now the single-jurisdiction flow create audit form lives at `/audit`.
**Testing**
**Progress**
Ready

Remove create audit form on login screen

---

arlo-client/src/components/utilities.ts

Not all errors come back in the same format from the server.
`4xx` errors have a body of the format: `{ errors: [{ message: "..." }]}`
`404` errors have an HTML body with a 404 page
`500` errors have an HTML body with a stack trace
This at least makes sure we can catch all of them, toast a relevant
message, and log the full response body to the console for debugging.
**Testing**
**Progress**
Ready

Improve frontend api request error handling

---

arlo-client/src/components/Audit/useSetupMenuItems/getJurisdictionFileStatus.ts
arlo-client/src/components/Audit/useSetupMenuItems/index.ts
arlo-client/src/components/utilities.ts

- Make sure the polling stops when an error happens on the backend 
- Bubble up the error to somewhere where it can get toasted
Doesn't get rid of the spinners on error, but that would take more refactoring.
**Testing**
**Progress**
Ready

Jurisdiction file upload error handling

---

tests/util_tests/test_csv_parse.py
util/csv_parse.py

We now ignore trailing empty columns in CSVs. We assume that all headers with no names will mean the entire column should be empty. If we later find that isn't true, we raise a helpful error message.
**Testing**
Took some sample CSVs from the Michigan RLA happening now.
**Progress**
n/a

fix: ignore trailing empty CSV columns

---

arlo_server/audit_boards.py
arlo_server/ballots.py
tests/helpers.py
tests/routes_tests/test_audit_boards.py
tests/routes_tests/test_ballots.py

Since audit boards only know about ballots, not sample draws, we also want JAs to only know about ballots, not sample draws.
This changes two JA endpoints:
- The `/audit-board` endpoint, which reports stats on the ballots assigned to each audit board
- The `/ballot-draws` endpoint (renamed to `/ballots`), which lists all the ballots for the jurisdiction
**Testing**
Updated existing tests.
**Progress**
Ready

JA sees ballots, not sample draws

---

arlo-client/src/components/MultiJurisdictionAudit/StatusBox.tsx
arlo-client/src/setupProxy.js

Follow up to #527. Note that the correct URL was already being used for the jurisdiction admin report, so we didn't have to update anything.
**Testing**
**Progress**
Ready

Audit report - use new endpoints on frontend

---

Pipfile
Pipfile.lock
mypy.ini
tests/util_tests/test_csv_parse.py
tests/util_tests/windows1252-encoded.csv
util/csv_parse.py

This allows files that do not have UTF-8 encoding to be uploaded. The check for confidence greater than zero is probably not needed, but I figured it wouldn't hurt since in that case we probably want to just try UTF-8.
**Testing**
Added the `windows-1252`-encoded CSV that triggered this bug as a test case.
**Progress**
I'm sure there are more CSV and encoding issues lurking, but we'll squash them as we find them.

fix: detect CSV file encoding

---

arlo_server/ballot_manifest.py
bgcompute.py
tests/routes_tests/test_ballot_manifest.py
tests/routes_tests/test_jurisdictions.py
tests/util_tests/test_csv_parse.py
util/csv_parse.py
util/jurisdiction_bulk_update.py

Previously, we were relying on the db unique constraint on `Batch.name`,
which produced a gnarly error message. So we implement uniqueness
checking in our own csv validation module in order to provide a useful
error message.
**Testing**
Added new tests and updated existing
**Progress**
Ready

Better error message for duplicate batch names in ballot manifest

---

arlo-client/src/components/DataEntry/Ballot.tsx
arlo-client/src/components/DataEntry/BallotReview.tsx
arlo-client/src/components/DataEntry/index.tsx

- Scroll to top when switching between ballots
- Change the back button from the ballot review screen to go back to the ballot audit screen (before it went to the previous ballot)
**Testing**
**Progress**
Ready

Audit navigation fixes

---

arlo-client/src/components/MultiJurisdictionAudit/Setup/Review/index.tsx
arlo_server/rounds.py

After launch, we were redirecting to the audit progress screen before the round got created/the ballots got sampled. This adds an `await` to the request to create the round before redirecting.
Also, while I was investigating, I realized that the backend was accidentally using two db transactions to create the round and sample the ballots, so I combined them into one.
**Testing**
**Progress**
Ready

After audit launch, wait for round to get created before redirecting

---

arlo-client/src/components/CreateAudit.tsx
arlo-client/src/components/MultiJurisdictionAudit/Progress/index.tsx
arlo-client/src/components/MultiJurisdictionAudit/StatusBox.tsx
arlo-client/src/components/MultiJurisdictionAudit/index.tsx

In order to make this change, we hoist data loading up to the top level AuditAdminView component. Note that we don't pass data down into the `Setup` component because it has it's own way of doing things and I don't wanna mess with it in this PR.
**Testing**
**Progress**
Ready

Default to progress screen for AAs when audit setup complete

---

arlo-client/src/components/MultiJurisdictionAudit/Setup/Review/index.tsx

Otherwise you can try to launch the audit once the first round is already in progress, which is not allowed.
**Testing**
**Progress**
Ready

Disable launch button when screen is locked

---

arlo_server/ballots.py
arlo_server/routes.py
tests/routes_tests/test_ballots.py

Users' computers didn't know how to open the file because it lacked a filetype suffix.
**Testing**
Updated existing test
**Progress**
Ready

Add .csv suffix to ballot retrieval list

---

arlo-client/src/components/CreateAudit.tsx

If you're logged in as an audit board, you don't have access to any screens besides the audit board screens. All of the other screens except the home screen (at the root path( are protected routes, so it's not an issue.
Previously, we had a janky 404 message at the root path for audit board users. Now, we show the log in screen (though the audit board user is still logged in - which is a little odd).
**Testing**
**Progress**
Ready

Show login screen if logged in as audit board at root path

---

README.md

When running `make resetdb` on a Chromebook Crostini virtual environment with
the default Debian 10.2 Linux, I ran into the `fe_sendauth: no password supplied`
error noted in the README. But changing to `trust` for just IPv4 in 
`/etc/postgresql/11/main/pg_hba.conf` didn't resolve the issue.
When I changed to `trust` for IPv6 also, the make succeeded.
So I guess connections are being made via IPv6 in some configurations.
Note also that this was with Postgresql version 11, default on Debian.
The troubleshooting tip now also describes one way to reload the postgres configs,
which is also necessary.
**Testing**
Documentation-only change

docs: fe_sendauth issue can require IPv6 trust

---

arlo-client/src/components/DataEntry/MemberForm.tsx
arlo-client/src/components/DataEntry/SignOff.tsx
arlo-client/src/components/DataEntry/index.tsx
arlo_server/audit_boards.py
tests/routes_tests/test_audit_boards.py
tests/routes_tests/test_reports.py

The audit board member sign in form currently allows you to only sign in one member (either member 1 or member 2), but the sign off form expects both members.
This was causing the sign off form to break.
Two changes here:
- Only allow signing in for the first member _or_ both members
- If only one member signed in, only expect one member to sign out
**Testing**
Added some new API tests. Manually tested the frontend in both cases.
**Progress**
Ready

Allow only one audit board member

---

arlo-client/package.json
arlo-client/yarn.lock

Google Chrome released v83, so we need to update chromedriver so that the wdio tests can pass on CI. Hopefully we can figure out a better long term solution (some ideas in #558).

chromedriver v83.0.0

---

tests/audit_math_tests/test_bravo.py
tests/audit_math_tests/test_macro.py
tests/audit_math_tests/test_sampler.py
tests/audit_math_tests/test_sampler_contest.py
tests/conftest.py
tests/routes_tests/test_audit_status.py
tests/routes_tests/test_single_jurisdiction_ballot_list.py
tests/routes_tests/test_superadmin.py
tests/test_app.py
tests/util_tests/test_binpacking.py

For some reason, we all thought that fixtures had to yield their
results. But really they can return results - yielding is only necessary
if you want to do some teardown after the test runs.

Remove unnecessary generators from test fixtures

---

package.json
yarn.lock

Before I figured out what was going on, on three different occasions, when I was just trying to `git commit` some files, the `lint-staged` pre-commit hook had an error and **threw away most files in an untracked subdirectory**.  Damn....
Fixes #543.
See also [Files lost after EISDIR: illegal operation on a directory, unlink - in version 10.0.8](https://github.com/okonet/lint-staged/issues/866)
**Testing**
I don't know of any git-related tests in this repo, but `git commit` stopped throwing away most of the files in my untracked subdirectory after I upgraded to lint-staged 10.2.2
**Progress**
I'm not sure what is needed to put this into effect, but I naively just manually did `npm up lint-staged`.  I was a bit surprised that it didn't seem to happen automagically, but I'm …

Update lint-staged to avoid file lossage

---

Makefile
package.json
run-dev.sh

`pipenv` knows what version of Python to run due to this line in Pipfile:
```
[requires]
python_version = "3.7"
```

Run pipenv directly (no more `python3.7 -m pipenv`)

---

arlo-client/src/components/MultiJurisdictionAudit/RoundManagement/CreateAuditBoards.test.tsx
arlo-client/src/components/MultiJurisdictionAudit/RoundManagement/CreateAuditBoards.tsx

This won't fix any existing audit board names, but for new ones it will ensure that sorting lexicographically also sorts numerically. This was the simplest fix I could think of since the client controls the names, but the server does the sorting.
**Testing**
Adds some unit tests for `CreateAuditBoards` to make sure the names are as expected.
**Progress**
n/a

fix: ensure audit board names are sorted correctly

---

.vscode/settings.json

Better to set it on your own using your pipenv virtualenv (which is a
path specific to your computer). That way VSCode can find imports from the virtualenv. Instructions here: https://code.visualstudio.com/docs/python/environments

Remove Python path from vscode workspace settings

---

arlo_server/audit_boards.py
tests/routes_tests/test_audit_boards.py

Whenever an audit board signs off, we check if the round is complete. This change modifies the check to omit any audit boards that didn't have any ballots assigned to them.
We might also want to change the UI, but this is the basic change needed.

Don't require audit boards with no ballots assigned to sign off

---

arlo-client/src/__snapshots__/App.test.tsx.snap
arlo-client/src/components/DataEntry/Ballot.tsx
arlo-client/src/components/DataEntry/BoardTable.tsx
arlo-client/src/components/DataEntry/__snapshots__/BoardTable.test.tsx.snap
arlo-client/src/components/DataEntry/__snapshots__/index.test.tsx.snap
arlo-client/src/components/DataEntry/index.test.tsx
arlo-client/src/components/DataEntry/index.tsx
arlo_server/ballots.py
tests/routes_tests/test_ballots.py

This endpoint replaces the ballot_set/ballot_set_not_found endpoints
with a new endpoint that handles all of the requests that an audit board
needs to make to audit a ballot, remove the audit record for a ballot,
and mark a ballot not found.
Most importantly, this endpoint checks for authorization!
It also updates the frontend to use this new endpoint, and improves some styling on the audit board table view.

Add endpoint for audit board to audit ballot

---

arlo_server/sample_sizes.py
tests/routes_tests/test_sample_sizes.py

This endpoint is only used for the audit setup flow. Currently, if you
navigate back to the Review & Launch screen after starting an audit, the
sample sizes shown will reflect the current state of the audit. This fix
ensures that they will always show the initial sample size options that
the user chose from for round 1 when starting the audit.

/sample-sizes always return round one sample size options

---

arlo-client/src/components/DataEntry/MemberForm.tsx
arlo-client/src/components/DataEntry/index.test.tsx
arlo-client/src/components/DataEntry/index.tsx
arlo-client/src/types.ts
arlo_server/audit_boards.py
arlo_server/models.py
arlo_server/reports.py
tests/routes_tests/test_audit_boards.py
tests/routes_tests/test_audit_status.py
tests/routes_tests/test_reports.py
tests/test_app.py

Adds a new endpoint that requires audit board authorization to set up
the audit board members (name and party affiliation). Updates the frontend to use this endpoint.
Also creates an Affiliation enum to lock in the values we expect.

Endpoint to set audit board members

---

Makefile
pytest.ini
tests/conftest.py

Adds a pytest.ini config file so that we don't have to put all the default settings in the Makefile command. This allows running `pipenv run pytest` if you want to add more flags to the command (`make` doesn't allow you to pass in more flags, so we had a hacky way to work around it before).

Simplify pytest command using pytest.ini

---

.slugignore
arlo-client/tsconfig.json

Allow ts to typecheck test files locally but ignore them when building
on Heroku.

Move ts excludes to .slugignore

---

client/src/__snapshots__/App.test.tsx.snap
client/src/components/Atoms/Table.tsx
client/src/components/MultiJurisdictionAudit/Progress/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/Progress/index.test.tsx
client/src/components/MultiJurisdictionAudit/Progress/index.tsx
client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/_mocks.ts
client/src/components/MultiJurisdictionAudit/useJurisdictions.ts
server/api/jurisdictions.py
server/tests/api/test_jurisdictions.py
server/tests/helpers.py

JA and AB users only know about the ballot counts. AA users get to know about both the ballot counts and the sample counts.
This PR adds a toggle to the jurisdiction progress view to let the AA user switch which count they want to see.
Also updates the API to return both counts (previously just returned sample counts).

Toggle to show sample vs ballot counts on jurisdiction progress screen

---

server/api/contests.py
server/api/election_settings.py
server/api/routes.py
server/tests/api/test_contests.py
server/tests/api/test_election_settings.py
server/tests/api/test_jurisdictions_file.py

The frontend already disables these forms, but we also want guards in
the backend API to prevent this from happening.

Don't allow updating jurisdictions/contests/settings after audit starts

---

scripts/create-admin.py
scripts/create-org.py

flask-sqlalchemy requires a Flask app context to interact with the db

Import Flask app in scripts

---

client/package.json
client/src/App.test.tsx
client/src/components/DataEntry/index.test.tsx
client/src/components/Header.test.tsx
client/src/components/MultiJurisdictionAudit/Setup/Contests/index.test.tsx
client/src/components/MultiJurisdictionAudit/Setup/Participants/index.test.tsx
client/src/components/MultiJurisdictionAudit/Setup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/Setup/Settings/index.test.tsx
client/src/components/MultiJurisdictionAudit/Setup/index.test.tsx
client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/index.test.tsx
client/src/components/MultiJurisdictionAudit/useAuditSettings.test.ts
client/src/components/MultiJurisdictionAudit/useSetupMenuItems.test.ts
client/src/components/ResetButton.test.tsx
client/src/components/SingleJurisdictionAudit/CalculateRiskMeasurement.test.tsx
client/src/components/SingleJurisdictionAudit/index.test.tsx
client/src/components/testUtilities.ts
client/yarn.lock

Some package upgrades:
- @testing-library/react-hooks v3.3.0
- @testing-library/react v10.3.0
I started these upgrades to get some performance optimizations that I hoped would speed up some tests I was writing.
These broke some tests, specifically the ones using `asyncActRender`, since `act` no longer supports taking an async function (caused a type error).
Looking into this deeper, I discovered that since many of our components make some API calls when they render, we often need the tests to wait for those calls to get made before we can assert anything about the resulting DOM. I think `asyncActRender` was causing this to happen.
Reading some docs, I found out that testing-library's `render` already calls `act` internally, so that part wasn't necessary. So I replaced the calls to …

Upgrade testing-library and fix all test warnings

---

client/src/components/Atoms/LinkButton.tsx
client/src/components/DataEntry/BoardTable.test.tsx
client/src/components/DataEntry/BoardTable.tsx
client/src/components/DataEntry/__snapshots__/BoardTable.test.tsx.snap
client/src/components/DataEntry/__snapshots__/index.test.tsx.snap
client/src/components/DataEntry/index.test.tsx

Adds a LinkButton component that renders a React Router Link using a
BlueprintJS Button component. This makes the link look like a button and
allows it to be disabled.
Two advantages:
- If we just used AnchorButton from BlueprintJS, we can't actually test
clicking it, since our testing environment doesn't support actual
browser navigation, just React Router navigation.
- Anchor links can't actually be disabled, so before we had to hack around that
to test that they were getting disabled.

LinkButton component

---

server/models.py
server/tests/api/test_contests.py

Task: #611 
In order to preserve the order that contests and choices are entered in the by the audit admin, we order by `created_at` when we pull them from the db.

Preserve contest and choice order that audit admin enters

---

client/src/__snapshots__/App.test.tsx.snap
client/src/components/Atoms/Form/FormButtonBar.tsx
client/src/components/Atoms/Form/FormWrapper.tsx
client/src/components/Atoms/SpacedCard.tsx
client/src/components/MultiJurisdictionAudit/Setup/Contests/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/Setup/Contests/index.test.tsx
client/src/components/MultiJurisdictionAudit/Setup/Contests/index.tsx
client/src/components/MultiJurisdictionAudit/Setup/Participants/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/Setup/Review/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/Setup/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap
client/src/components/SingleJurisdictionAudit/__snapshots__/CalculateRiskMeasurement.test.tsx.snap
client/src/components/SingleJurisdictionAudit/__snapshots__/EstimateSampleSize.test.tsx.snap
client/src/components/SingleJurisdictionAudit/__snapshots__/SelectBallotsToAudit.test.tsx.snap
client/src/components/SingleJurisdictionAudit/__snapshots__/index.test.tsx.snap

- Uncommented and updated the code related to adding and removing contests on the multi jurisdiction flow.
**Testing**
- Updated snapshots and unskipped the test related to adding and removing contests
**Progress**
- The backend sorts the contests alphabetically by name from what I can tell, so contests don't come back in the same order they were entered in. This might confuse end users, if they put a contest as 'contest one' but then it comes back as the second contest. Not sure if this is an issue or not, @mcchilders ?

Activating multiple contests

---

bgcompute.py

This version of #624 goes into the branch for our current deploy.

Hotfix: bgcompute: only compute sample sizes for single-jurisdiction audits

---

server/api/audit_boards.py
server/models.py
server/tests/api/test_audit_boards.py
server/tests/helpers.py

Previously, we counted votes for targeted and opportunistic contests the
same way - using the sample draws. This was incorrect. For targeted
contests, we should count the sample draws. For opportunistic, we should
count distinct ballots.
This will make more a difference when we have multiple contests with
distinct sample draws that may refer to the same ballots.

Count ballots not sample draws for opportunistic contests

---

Pipfile
Pipfile.lock
client/package.json
client/src/components/MultiJurisdictionAudit/Setup/Review/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/Setup/Review/_mocks.ts
client/src/components/MultiJurisdictionAudit/Setup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/Setup/Review/index.tsx
client/src/components/MultiJurisdictionAudit/Setup/Review/useSampleSizes.ts
client/src/components/MultiJurisdictionAudit/Setup/__snapshots__/index.test.tsx.snap
client/src/components/SingleJurisdictionAudit/SelectBallotsToAudit.tsx
client/src/types.ts
server/api/audit_boards.py
server/api/contests.py
server/api/rounds.py
server/api/sample_sizes.py
server/audit_math/bravo.py
server/tests/api/snapshots/snap_test_reports.py
server/tests/api/snapshots/snap_test_sample_sizes.py
server/tests/api/test_contests.py
server/tests/api/test_jurisdictions.py
server/tests/api/test_rounds.py
server/tests/api/test_sample_sizes.py
server/tests/conftest.py
server/tests/snapshots/snap_test_multiple_targeted_contests.py
server/tests/test_multiple_targeted_contests.py

- Updated the types to reflect api changes
- Updated the review and launch stage to have multiple sample size selection boxes for the targeted contests
- Updated launch process to use the format expected by the api changes
**Testing**
- None yet, waiting for review
**Progress**
- It looks like it works, need to double check with @jonahkagan that it all makes sense.

Supporting sample sizes for multiple independently targeted contests

---

Pipfile
Pipfile.lock
client/package.json
client/src/components/MultiJurisdictionAudit/Setup/Review/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/Setup/Review/_mocks.ts
client/src/components/MultiJurisdictionAudit/Setup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/Setup/Review/index.tsx
client/src/components/MultiJurisdictionAudit/Setup/Review/useSampleSizes.ts
client/src/components/MultiJurisdictionAudit/Setup/__snapshots__/index.test.tsx.snap
client/src/components/SingleJurisdictionAudit/SelectBallotsToAudit.tsx
client/src/types.ts
server/api/audit_boards.py
server/api/contests.py
server/api/rounds.py
server/api/sample_sizes.py
server/audit_math/bravo.py
server/tests/api/snapshots/snap_test_reports.py
server/tests/api/snapshots/snap_test_sample_sizes.py
server/tests/api/test_contests.py
server/tests/api/test_jurisdictions.py
server/tests/api/test_rounds.py
server/tests/api/test_sample_sizes.py
server/tests/conftest.py
server/tests/snapshots/snap_test_multiple_targeted_contests.py
server/tests/test_multiple_targeted_contests.py

Task: #622
Adds support for multiple independently targeted contests by drawing a separate sample for each targeted contest.
Removes support for jointly targeted contests because we decided we don't need to implement it right now.
Breaking changes to two APIs:
- GET /sample-sizes now returns a map from targeted contest ids to sample size options
- POST /round now requires a map from targeted contest id to sample size, rather than just one sample size
Also fixes an issue in the audit report where we were reporting a sample size for opportunistic contests. This doesn't make sense when there are multiple targeted contests, because the number of ballots we count for the opportunistic contests doesn't necessarily match the sample size. Instead, we don't report a sample size for opportunistic …

Independently targeted contests

---

Pipfile
Pipfile.lock

We were all of a sudden getting an error on CI when installing deps via pip. Googling the error took me to this issue:
https://github.com/bigchaindb/bigchaindb/issues/1848#issuecomment-642088842. It recommended removing uuid from the dependency list because it's already bundled in Python.

Remove uuid from Pipfile

---

client/src/components/MultiJurisdictionAudit/RoundManagement/generateSheets.ts

- Enclosed the addition of the url to the pdf in the same wrapping function as the instructions.
**Testing**
- Doesn't change current tests, tested manually though and it works.
**Progress**
- All done!

Wrapping passphrase url if too long

---

README.md

There was no link to `docs/auth0.md` in the project, so this PR adds a link to it from the README.
**Testing**
**Progress**
Note that neither the README nor auth0.md have very much to say about the practicalities of the relatively complex matter of setting up auth0, which is now the only way to log in and run Arlo.
So please augment the documentation.
But merging this doesn't have to wait on that.

Note auth0.md in README, but need more doc

---

server/api/contests.py
server/api/election_settings.py
server/tests/api/test_contests.py
server/tests/api/test_election_settings.py

In offline data entry audits, the jurisdiction admin needs to enter results for each contest. So JAs need to be able to load the election settings (to see if the audit is online/offline) and load the contests (to know which contests/choices to enter results for).
This adds two new endpoints to support those use cases:
- /election/<election_id>/jurisdiction/<jurisdiction_id>/contest
- /election/<election_id>/jurisdiction/<jurisdiction_id>/settings
The contests returned are scoped to the jurisdiction's contest universe.

Add contests and settings endpoints for jurisdiction admins

---

.circleci/config.yml
Makefile
Pipfile
Pipfile.lock
README.md
mypy.ini
server/api/ballot_manifest.py
server/bgcompute.py
server/tests/api/snapshots/snap_test_reports.py
server/tests/api/test_ballot_manifest.py
server/tests/api/test_contests.py
server/tests/api/test_jurisdictions.py
server/tests/api/test_jurisdictions_file.py
server/tests/api/test_new_election.py
server/tests/api/test_reports.py
server/tests/api/test_superadmin.py
server/tests/conftest.py
server/tests/helpers.py
server/tests/single_jurisdiction/test_app.py
server/tests/single_jurisdiction/test_ballot_list.py
server/tests/snapshots/snap_test_multiple_targeted_contests.py
server/tests/snapshots/snap_test_offline_data_entry.py
server/tests/test_auth.py
server/tests/test_migrations.py
server/tests/test_multiple_targeted_contests.py
server/tests/util/test_jurisdiction_bulk_update.py

Uses pytest-xdist to run the server tests in parallel. We use one database throughout most of the tests, which also simulates the real-world a bit better and helps ensure we are scoping data correctly.
In working on this PR, I found a race condition in bgcompute - when computing sample sizes, we can accidentally sample ballots twice for the same contest (for round > 1). So I copied the locking pattern from `process_file` to lock the RoundContest object.

Parallel tests

---

server/api/__init__.py
server/api/ballots.py
server/api/offline_results.py
server/tests/test_offline_data_entry.py

When a JA loads the data entry page, we need to know if they've sent in results already or not (and if so, display the results). We add a new endpoint to load the results:
GET /election/<election_id>/jurisdiction/<jurisdiction_id>/round/<round_id>/results
We also move the offline results endpoints (now there are two) to their own module. They deserve it!

Endpoint for JA to get offline results

---

client/package.json
client/src/__snapshots__/App.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/RoundDataEntry.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/RoundDataEntry.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/RoundDataEntry.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/_mocks.ts
client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/useAuditSettingsJurisdictionAdmin.ts
client/src/components/MultiJurisdictionAudit/RoundManagement/useContestsJurisdictionAdmin.ts
client/src/components/MultiJurisdictionAudit/RoundManagement/useResults.ts
client/src/components/MultiJurisdictionAudit/Setup/Contests/index.tsx
client/yarn.lock

- Renders the RoundDataEntry component instead of the RoundProgress component when the audit is offline
- Added the forms for data entry
**Testing**
- So far just the bare basics, needs more
**Progress**
- Doesn't work as of yet because this requires the JA to have access to the settings and contests apis, which they didn't need on the online flow.

Offline data entry [FE]

---

Pipfile
Pipfile.lock
Procfile

Adds a Heroku Release Phase task to migrate to the current db state
before deploying a new build. See https://devcenter.heroku.com/articles/release-phase

Run db migrations on deploy

---

README.md
client/cypress/end-to-end/ballot-polling-basic.spec.js
client/cypress/seed-test-db.sh
client/package.json
scripts/cleardb.py
server/database.py

Previously, we used the existing `resetdb` script to prepare the db for
seed data in Cypress tests. The problem with this approach is that it
hangs when a Flask app is already running, since that app has an open db
session, so SQLAlchemy gets blocked trying to drop the tables.
Instead, we add a new script `cleardb` that iterates over the tables and
deletes all the data from them. This does not block if the Flask app is
already running.
With this block removed, we can move the seeding of data into the actual
Cypress test spec so that it runs every time we run the tests, instead
of trying to run it via bash scripts for test running (much simpler and
less error-prone).

Clear data instead of dropping tables when seeding data for Cypress

---

server/migrations/versions/9ed660c31c0a_election_audit_type.py

This was failing on staging because it required the `Election.audit_type` field to have a value but didn't set any value for existing audits in the database.

Fix Election.audit_type migration to set value for existing audits

---

scripts/resetdb.py
server/migrations/README.md

Whenever we reset the database schema, we need to mark in the database
the version of the schema we're using in order for Alembic to be able to
tell where to start from when running migrations on the database. I'd
been doing this ad hoc whenever I encountered a db without a revision
stamp, but I realized that would be less likely to happen if we stamp
every time we reset (or create) a database.

scripts.resetdb: stamp db with latest migration revision

---

scripts/create-admin.py

Sometimes we want users to be able to be audit admins for multiple orgs,
so we modify the create-admin script to find or create the user, then
make them an admin for the org.

scripts.create-admin: support existing audit admins

---

client/src/__snapshots__/App.test.tsx.snap
client/src/components/Header.test.tsx
client/src/components/Header.tsx
client/src/components/__snapshots__/Header.test.tsx.snap

Closes #693 
@mcchilders It looks like we currently support multiple jurisdictions under the same login, so I made it so that it will display all the jurisdiction names associated with the current login.
**Testing**
**Progress**
- LGTM
- I think this part of the code might be covered in my wip coverage PR, so instead of redoing it all over here, I'd rather merge this then update that PR to reflect this relatively simple change.

Adding jurisdiction names to header for JA views

---

server/api/batches.py
server/tests/batch_comparison/conftest.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/snapshots/snap_test_batches.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/batch_comparison/test_batch_tallies.py
server/tests/batch_comparison/test_batches.py

- Add a separate endpoint to get batch results
- When no results are recorded, return full results object (with choice
ids) instead of null
- Filter out batches that were sampled in previous rounds in batches and
results endpoints

Update batch results

---

server/api/batch_tallies.py
server/api/batches.py
server/api/contests.py
server/api/reports.py
server/api/rounds.py
server/tests/api/test_contests.py
server/tests/batch_comparison/test_batch_comparison.py

Task: #684 
- Validate batch tallies files
- Check that all jurisdictions have uploaded a file before computing
sample sizes/starting a round
- Check that the total tallies for each choice don't exceed the
reported vote count for that choice
- Only allow one contest

Batch audit guards

---

client/src/__snapshots__/App.test.tsx.snap
client/src/components/MultiJurisdictionAudit/AASetup/Contests/index.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/AASetup/Review/_mocks.ts
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Settings/index.tsx
client/src/components/MultiJurisdictionAudit/AASetup/index.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/BatchRoundDataEntry.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/BatchRoundDataEntry.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/BatchRoundDataEntry.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/_mocks.ts
client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/useBatchResults.ts
client/src/components/MultiJurisdictionAudit/RoundManagement/useResults.ts
client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/index.tsx

- Adding a new component and hook for batch data entry.
**Testing**
- Duplicated the tests from the regular data entry, and added a couple more to both to help with the coverage cause.
**Progress**
- This seems to work just fine with the first round, but the second round is displaying some really weird behavior. But I think that's from the backend.
- There's a react warning because the source of truth for the results (the batches endpoint) returns null instead of the expected structure of batch ids and choice ids with null values, which means the form is switching from uncontrolled to controlled components when we first interact with the fields. Ideally, the results object would contain the expected structure instead of null, and this would clean up the FE code quite a …

Batch offline data entry

---

.pylintrc
server/bgcompute.py
server/tests/test_errors.py

Task: #708 
Use the Flask application logger to log info and exceptions in
bgcompute.
Open question: where else could we benefit from beefing up our error logging before the next live audits?

Log exceptions in bgcompute

---

client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/generateSheets.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/generateSheets.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/generateSheets.ts
client/src/components/MultiJurisdictionAudit/RoundManagement/index.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx
server/api/ballots.py
server/api/batches.py
server/api/reports.py
server/tests/api/test_ballots.py
server/tests/api/test_reports.py
server/tests/batch_comparison/test_batches.py
server/tests/helpers.py
server/util/csv_download.py

Task: #692 
- Backend: add jurisdiction name to retrieval list/audit report filename (also switched election name to audit name)
- Frontend: add jurisdiction name and audit name to labels/placeholders/audit board creds filenames

Add jurisdiction name to filenames

---

server/audit_math/macro.py
server/audit_math/sampler.py
server/tests/audit_math/test_macro.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/test_batch_comparison.py

Opening a new PR because github is bugging out.
Description
Modifies the MACRO math to make more informed sample size estimates based on previously drawn samples. Notably, this doesn't change the conservative nature of the statistics, since the new computation will always require sampling at least one batch. Leaves the conservative math up to p-value computations.
Testing
Adds test for get_sample_sizes which we really should have had anyways.
Progress
Ready to go.

Implements more intelligent subsequent round MACRO sample size computation

---

client/src/__snapshots__/App.test.tsx.snap
client/src/components/Atoms/Wrapper.tsx
client/src/components/DataEntry/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/BatchRoundDataEntry.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/BatchRoundDataEntry.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/CreateAuditBoards.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/CreateAuditBoards.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/RoundDataEntry.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/RoundDataEntry.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/RoundProgress.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/RoundProgress.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/BatchRoundDataEntry.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/RoundDataEntry.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/RoundProgress.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/index.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/useAuditSettingsJurisdictionAdmin.ts
client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/index.tsx
client/src/components/SingleJurisdictionAudit/__snapshots__/index.test.tsx.snap
client/src/components/SingleJurisdictionAudit/index.tsx

- Ensure there's always a heading at the top of the page
- Pull the num ballots message out of the CreateAuditBoards component so that
it still shows during data entry
- Remove unnecessary props from CreateAuditBoards
- Put the buttons in a ButtonGroup and add icons so they look nice (this
will be useful when we reuse those buttons in the AA Audit Progress
view)
- Shrink the page width so that lines of text aren't super long
- Remove the special-case styles from the Wrapper class, since they are
only used in this page and the single-jurisdiction flow
I separated out the snapshot updates into a separate commit because there were so many of them.

Restyle/refactor JA RoundManagement screen

---

client/src/components/Atoms/Table.tsx
client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/index.tsx

Two problems were happening:
1. Every time the useInterval that checks if it's time to refresh
ticked, the whole Progress component (including the table) was getting
re-rendered. (The React DevTools profiler is amazing and highlights each
component as it renders, so it was easy to figure out). I solved this by
isolating the state for the refresh tag in its own component.
2. When the Progress component re-rendered, the Table reset its sort
state. This was originally happening every second, but after fixing the
above problem, was still happening when the data actually refreshed
every 5 minutes. I fixed this by passing `autoResetSortBy: false` to the
Table config.

Save table state on refresh

---

server/api/__init__.py
server/api/contests.py
server/api/standardized_contests.py
server/bgcompute.py
server/migrations/versions/5acbd2f95b9f_standardized_contests_file.py
server/models.py
server/tests/ballot_comparison/conftest.py
server/tests/ballot_comparison/test_ballot_comparison.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/ballot_comparison/test_standardized_contests.py

Task: #766 
For ballot comparison audits, the AA uploads a standardized contests
file and then selects the target/opportunistic contests based on the
options in that file.
This change:
- Adds new endpoints for uploading the standardized contests file,
parsing it, storing it in Election.standardized_contests, and returning
the parsed data to the AA
- Modifies the endpoint for creating contests to allow creating contests
without metadata (since the standardized contests file doesn't include
that data - we parse it later from the CVRs)

Standardized contests file

---

server/api/cvrs.py
server/api/sample_sizes.py
server/tests/ballot_comparison/conftest.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/snapshots/snap_test_cvrs.py
server/tests/ballot_comparison/test_ballot_comparison.py

- Parse the contest metadata out of Jurisdiction.cvr_contests_metadata
where we stashed it
- Use that contest metadata to call supersimple.get_sample_sizes to get
the estimated sample sizes for ballot comparison audits
Still todo in a future PR: come back and compute the sample results for
previous rounds so we can draw samples for later rounds.

Ballot comparison sample size

---

server/api/jurisdictions.py
server/tests/ballot_comparison/test_cvrs.py

Task #781 
Same pattern as ballot manifest and batch tallies files. Used for the
audit setup flow to figure out when all the CVRs have been uploaded and
also to show upload status in the progress view.

Add CVRs file status to AA jurisdictions endpoint

---

server/api/cvrs.py
server/api/rounds.py
server/api/sample_sizes.py
server/audit_math/supersimple.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison.py

In ballot comparison audits, for rounds after the first round, the
sampler needs to know the results from the previous round in terms of
the discrepancies found.

Pass discrepancies into sample size calculator

---

server/audit_math/supersimple.py
server/tests/audit_math/test_supersimple.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py

Exposes discrepancies between the sampled ballots and the CVRs via the `supersimple.find_discrepancies` function. Also refactors a bit to take advantage of the new function call. Closes #761.
**Testing**
Adds two new test cases to verify the new discrepancy finding is correct and doesn't monkey with the p-value calculations.
**Progress**
Ready.

Exposes discrepancies from math code. 

---

server/tests/api/test_ballot_manifest.py
server/tests/api/test_jurisdictions.py
server/tests/util/test_csv_parse.py
server/util/csv_parse.py

For ballot comparison audits, we are changing the ballot manifest to
have composite unique keys on the Tabulator and Batch Name columns -
i.e. each row must be uniquely identified by Tabulator+Batch Name.
This PR modifies the csv_parse module to support this case. Since we
never actually want two columns to both be independently required to be
unique (and I can't think of a situation in which we will), we modify
the behavior to make a composite unique key out of any columns which are
specified as `unique=True`.
While I was at it, I also removed the constraint that columns must in a
particular order, since I figured people might add the
Tabulator/Container columns at the beginning or at the end. We only
required ordered columns because there were some assumptions that the
columns were …

csv_parse: support composite unique keys

---

client/src/components/MultiJurisdictionAudit/AASetup/Settings/index.tsx
server/api/routes.py
server/models.py
server/tests/api/test_election_settings.py
server/tests/api/test_new_election.py

Ballot polling audits are the only ones that have the configurable
online setting. This change sets online to the correct value for ballot
comparison and batch comparison audits on audit creation. It removes
setting of the online value from the frontend, except in the case of
ballot polling audits.

Set Election.online based on audit type

---

client/src/components/MultiJurisdictionAudit/Progress/JurisdictionDetail.tsx
client/src/components/MultiJurisdictionAudit/Progress/index.tsx

Task: #768 
Followed the pattern used by batch tallies file to put the CVR file in
the progress table and the jurisdiction detail modal.
Tests to be added in a separate PR

CVR file status in Audit Progress screen

---

client/package.json
client/src/components/MultiJurisdictionAudit/AASetup/Contests/_mocks.ts
client/src/components/MultiJurisdictionAudit/AASetup/Review/ConfirmLaunch.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx
client/src/components/MultiJurisdictionAudit/StatusBox/index.test.tsx
client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx
client/src/components/MultiJurisdictionAudit/index.tsx

Task: #758 
Status box
- Includes the CVR file when computing the status messages
- Also includes the batch tallies file (which we should have included before)
Review screen
- Add checks for all CVR/batch tallies files being uploaded to isSetupComplete
- Use isSetupComplete to decide when we load sample sizes as well as when we enable the launch button
- In the confirmation popup, only show a warning about how many jurisdictions uploaded ballot manifests for ballot polling audits (since in other audit types, all jurisdictions will have to have uploaded their manifests to get to this point)
- Change isSetupComplete and that warning to only factor in participating jurisdictions (i.e. ones that are part of a selected contest universe)
Misc
- Fix everywhere that we checked for …

CVR file in status box

---

server/audit_math/supersimple.py
server/tests/audit_math/test_supersimple.py

Fixes #806 
Adds condition in supersimple discrepancy finding to handle this case
**Testing**
Adds two test cases for when the CVR or sampled ballot have contests
that is not on the sampled ballot or CVR, respectively
**Progress**
Ready.

Adds code to handle different contests appearing in audit than expected.

---

client/src/components/MultiJurisdictionAudit/Progress/index.test.tsx
client/src/components/MultiJurisdictionAudit/Progress/index.tsx

Basically, big numbers need a comma in them.

Format numbers in audit progress table

---

server/api/rounds.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py

Task: #741 
Currently, when constructing the `sample_cvr` object to pass to the
`supersimple` audit math, we omit any ballot that the audit board did
not record any interpretation for (i.e. the contest was missing from
that ballot).
This impacts `supersimple.compute_risk`, since it iterates over the
`sample_cvr` to compute the p-value.

Include ballots that are missing contest in sample_cvr

---

server/api/reports.py
server/api/rounds.py
server/audit_math/supersimple.py
server/tests/audit_math/test_supersimple.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison.py

Task: #741 
If an audit board can't find a ballot, the research says we should
conservatively count that as a two-vote overstatement.
We pass `None` as the `sample_cvr` value for this case, and then
interpret that in `compute_discrepancies`.
Note: the typechecker is not smart enough to deal with this change to
the type, so there are also some other changes to accommodate that.

Count not found ballots as two-vote overstatement

---

client/src/App.test.tsx
client/src/__snapshots__/App.test.tsx.snap
client/src/components/HomeScreen.test.tsx
client/src/components/HomeScreen.tsx
client/src/components/testUtilities.tsx
client/src/components/utilities.ts
server/app.py
server/tests/test_auth.py

Task: #850 
Configures Flask to expire session cookies after 2 hours of inactivity. Also updates
the frontend to display a message when this happens (note: we just
display the message when the frontend gets a 401, which could also
happen from trying to access a route while not logged in for some other
reason, but this is the most common case so I figured why not).

Expire sessions

---

client/src/components/MultiJurisdictionAudit/AASetup/Contests/ContestForm.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Contests/ContestSelect.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx
client/src/components/MultiJurisdictionAudit/AASetup/index.test.tsx
client/src/components/MultiJurisdictionAudit/index.tsx
client/src/components/MultiJurisdictionAudit/useJurisdictions.ts

This is the pattern used by all our other data fetching hooks.
Previously, there was no way to check if the jurisdictions list was
empty or still loading, which meant that components were being rendered
that depended on the jurisdictions list before it was loaded.

useJurisdictions return null while still loading

---

client/src/__snapshots__/App.test.tsx.snap
client/src/components/HomeScreen.tsx
server/api/elections.py

Rather than implement a feature flag, we simply disable the Minerva math
selection in production. Since we don't really need a lot of
configurability, this is a quick solution for today.
Replaces #877

Enable Minerva math in dev/staging but not production

---

client/src/components/HomeScreen.test.tsx
client/src/components/HomeScreen.tsx
client/src/components/utilities.ts
client/src/index.tsx
server/auth/routes.py
server/tests/test_auth.py

Task: #876 
If something goes wrong in the OAuth flow, Auth0 sends an error message
to the callback. We catch those errors and redirect the user to the
login screen, displaying the error.
Two changes to make this possible:
- Standardize the way we show pass messages to the login screen
- Change the auth tests to use the `patch` method of the mocking module,
which automatically clears the mocks out once the test is done
(previously, they were carrying over between tests)

Show Auth0 login errors to users

---

client/src/components/MultiJurisdictionAudit/AASetup/Contests/ContestForm.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Contests/index.test.tsx
client/src/utils/objects.test.ts
client/src/utils/objects.ts

Closes #836 
- On Opportunistic Contests doesn't submit or trigger validation of the form if the fields aren't touched or match the existing values
- Don't do this on Targeted Contests, and keep current behavior
**Testing**
- Testing the utilities created for deep equals and empty object testing
- Adding tests for above behavior
**Progress**
- Done

Opportunistic contests should not be required

---

client/src/components/HomeScreen.tsx
client/src/index.tsx

The NODE_ENV variable is set to `production` whenever a built version of
the client is running (as opposed to running with `npm start`), so it
doesn't actually distinguish our different deployment environments.
Instead, we'll use a new env var, REACT_APP_ENV, which will correspond
to FLASK_ENV. (To pass env vars to the frontend, you need to prefix them
with REACT_APP_)

Use REACT_APP_ENV instead of NODE_ENV to toggle Minerva 

---

client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx

Basically decided to just bail for now since we don't have great status
info available, nor a good audit report (it's currently empty).

Fix JA status box when all ballots sampled

---

client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx
server/api/offline_batch_results.py
server/tests/test_sample_all_ballots.py

- Disable finalizing when form is unsaved
- Validate that total results don't exceed number of ballots in manifest (also defends against integer overflow errors)
- Don't allow saving results after finalizing
- Test and improve basic request validation

Offline batch results form improvements

---

client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx
server/api/offline_batch_results.py
server/tests/helpers.py
server/tests/test_sample_all_ballots.py

- max length of 200 characters for batch names
- wrap words in cells
- use a timezone for finalized_at
- disable finalizing when no results recorded

Offline batch results: assorted fixes

---

server/api/standardized_contests.py
server/tests/ballot_comparison/test_standardized_contests.py

Standardized contests wasn't stripping out `(Vote For=X)`, but cvrs.py was. This fixes it. 
**Testing**
Adds test that verifies that standardized contest names can have `(Vote For=X)` or not and it gets handled appropriately. 
**Progress**
Ready to go.

Fix mismatched names

---

client/package.json
client/src/components/MultiJurisdictionAudit/Progress/JurisdictionDetail.tsx
server/api/offline_batch_results.py
server/tests/test_sample_all_ballots.py

Sometimes JAs finalize the batch results prematurely. We give the AAs
the ability to unfinalize results for a jurisdiction.

Offline batch results: Unfinalize endpoint for AA

---

server/api/cvrs.py
server/api/jurisdictions.py
server/tests/util/test_csv_parse.py
server/util/csv_parse.py

If you use Excel and export Mac CSV format, the newlines are delimited
by single carriage returns. Previously, that caused a parsing error:
"new-line character seen in unquoted field - do you need to open the
file in universal-newline mode?"
By passing newline=None to io.StringIO it enables universal newlines
mode: https://docs.python.org/3/glossary.html#term-universal-newlines

Parse CSVs with carriage return newlines

---

server/models.py

When polling for file processing status, particularly in the case of CVR files (which can be large), we were previously loading the entire File database object, which implicitly loads the file contents. This was causing memory spikes (and potentially leaks). This change defers loading File.contents to when that property is accessed.

Defer loading of File.contents

---

client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx

We store UTC timestamps in the db, but they don't have timezone info attached. This changes the frontend to interpret the timestamps with the UTC timezone.
Note that there's an additional bug: even though we create our timestamps with the UTC timezone, the way they get stored in the database actually depends on the local timezone of the servers. It appears that Heroku has UTC as the local timezone, whereas my machine has PT:
On Heroku:
```
>>> datetime.now().isoformat()
'2020-11-16T22:10:24.927692'
```
On my machine:
```
>>> datetime.now().isoformat()
'2020-11-16T14:10:24.927692'
```
We should probably resolve this at the database level eventually.

Fix display of finalized timestamp

---

client/src/components/MultiJurisdictionAudit/CSVForm/index.tsx

- Show a spinner on the upload button while uploading the file to the
server, not just while processing the file on the backend
- Show the file name in the file selector while processing
Before:
After:

CSV file upload improvements

---

client/package.json
client/src/components/Atoms/CopyToClipboard.test.tsx
client/src/components/Atoms/CopyToClipboard.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx
client/yarn.lock

The empty table header above the edit buttons wasn't getting copied, so
the header row was one shorter than the body rows, which meant the
headers were off by one when pasting the results into a spreadsheet.
So we just exclude the whole column from copy/paste.
Also adds a "Copy to clipboard" button

Fix offline batch results copy/paste

---

client/src/index.tsx
server/app.py

We don't want to send every transaction to Sentry (both because it's
expensive in perf and money), instead we sample a proportion. This is a
recommended change that I forgot to make earlier.

Sentry: lower traces sample rate

---

client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx
server/api/audit_boards.py
server/api/ballot_manifest.py
server/api/batch_tallies.py
server/api/cvrs.py
server/api/jurisdictions.py
server/api/rounds.py
server/api/standardized_contests.py
server/models.py
server/tests/api/test_audit_boards.py
server/tests/api/test_jurisdictions.py
server/tests/helpers.py
server/tests/test_migrations.py
server/tests/util/test_process_file.py
server/util/csv_download.py
server/util/process_file.py

Because we store timestamps with no timezone info in the db, they were getting read from the db without timezone info, and therefore getting misinterpreted as local time by the frontend (instead of UTC time).
Here we make a few changes to fix this without modifying the database schema or changing timezones already in the database:
- Change everywhere we create datetimes from `datetime.utcnow` (which doesn't have timezone info) to use `datetime.now(timezone.utc)` (which does)
- Require that every datetime written to the db has timezone info
- When reading timezones from the db, set the timezone info to UTC
The latter two changes are accomplished with a custom sqlalchemy column type.
Lastly, we remove the workaround on the frontend that was appending `Z` to the timestamps to interpret them …

Add UTC timezone to all timestamps

---

server/api/rounds.py
server/audit_math/sampler.py
server/tests/audit_math/test_sampler.py

Change the interface to the sampler to take a list of ballot positions
instead of just a number of ballots. This will allow us to use the CVR
to generate the actual list of ballot positions (which aren't always
consecutive) and prevent sampling ballots that don't have the given
contest on them.

Sampler manifest list of ballot positions

---

client/src/components/MultiJurisdictionAudit/AASetup/Review/ConfirmLaunch.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx
client/src/components/MultiJurisdictionAudit/Progress/index.tsx

- Fix a bug on the audit progress screen where it would crash right
after launching the audit since the jurisdiction data hadn't been
refreshed yet (so currentRoundStatus wasn't populated yet)
- Add a spinner to the launch button until the request finishes
- Change the "Close without launching" button to just say "Cancel" (more
conventional language) and disable it while launching

Improve launching audit UX

---

server/app.py
server/auth/lib.py
server/auth/routes.py
server/config.py
server/superadmin.py
server/tests/helpers.py
server/tests/test_auth.py

Since Flask's permanent session feature only supports one timeout, we build our own expiration scheme on top of the session.
The session has two fields, _created_at (set on login) and _last_request_at (set on request, only if authorization is successful). We check these fields and corresponding timeouts every request when authorizing.
There's a small wrinkle for superadmins: since they can log in as other users, we ensure _created_at doesn't get set when they log in as other users, since that would allow someone with a superadmin cookie to keep the cookie alive by logging in as other users repeatedly.
We also update the test helpers for auth to use the actual session manipulation code rather than try to replicate it, since it's getting more complex.

Expire session based on inactivity or lifetime

---

server/bgcompute.py
server/models.py
server/tests/api/test_audit_boards.py
server/tests/api/test_ballot_manifest.py
server/tests/api/test_ballots.py
server/tests/api/test_contests.py
server/tests/api/test_election_settings.py
server/tests/api/test_elections.py
server/tests/api/test_jurisdictions.py
server/tests/api/test_jurisdictions_file.py
server/tests/api/test_reports.py
server/tests/api/test_rounds.py
server/tests/api/test_superadmin.py
server/tests/ballot_comparison/conftest.py
server/tests/ballot_comparison/test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison_manifests.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/ballot_comparison/test_standardized_contests.py
server/tests/ballot_polling/test_minerva_ballot_polling.py
server/tests/batch_comparison/conftest.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/batch_comparison/test_batch_tallies.py
server/tests/batch_comparison/test_batches.py
server/tests/conftest.py
server/tests/helpers.py
server/tests/test_auth.py
server/tests/test_errors.py
server/tests/test_offline_data_entry.py
server/tests/test_sample_all_ballots.py

Add an optional election_id filter to bgcompute functions so that they can be isolated to the specific election being processed in each test case. This will prevent race conditions when running the tests in parallel (one test would run a bgcompute function that would prematurely process a file from another test).
Also add the election_id to the jurisdiction admin emails created for each test case to avoid clashes when creating the users (which now happens more often as a result of the change to bgcompute).

Fix bgcompute test race condition

---

client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx

They might not have selected the first sample size option, so this is
misleading.
Ideally, we'd send back the option they selected when launching the
audit, but currently we're only storing the sample size number, not
which option they picked (and the options aren't guaranteed to have a
unique number), so this would be a bigger change.

Don't default a sample size option as selected after audit launches

---

client/src/components/HomeScreen.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Participants/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Participants/index.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx
client/src/components/MultiJurisdictionAudit/AASetup/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/index.test.tsx
client/src/components/MultiJurisdictionAudit/useCSV.ts
server/api/standardized_contests.py
server/tests/ballot_comparison/test_standardized_contests.py

- Endpoint to download standardized contests file
- Standardized contests file download link in Review screen
(Also change useStandardizedContestsFile to only make API requests if it's a ballot comparison audit.)
(Also fix a small bug so we don't show a % sign in the risk limit field until the risk limit is set)

Download standardized contests file

---

client/src/components/Atoms/Table.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Contests/ContestSelect.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Contests/ContestSelect.tsx
client/src/components/MultiJurisdictionAudit/useContestsBallotComparison.ts
client/src/components/MultiJurisdictionAudit/useStandardizedContests.ts
server/api/contests.py
server/api/cvrs.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison_manifests.py

Task: #954 (also fixes #926)
- Updates the /contest endpoint to accept numWinners
- Reworks the ContestSelect component to key contests by name to avoid issues with filtering by index
- Adds a "Winners" column to the ContestSelect table
- Adds filtering contests by jurisdiction name (an outstanding TODO in the code)

Add num winners field to contest select for ballot comparison

---

server/bgcompute.py

For bgcompute tasks that are specific to a jurisdiction, filtering the
file query on Election.id doesn't actually do anything because Election
isn't joined in the query. Why doesn't SQLAlchemy error in this case? I
do not know.

Filter bgcompute file query by Jurisdiction.election_id

---

server/auth/routes.py
server/tests/test_auth.py

Updated: originally just wanted to remove this field from the frontend, but instead decided to add it to /api/me so that the frontend can continue to use it.

Audit board jurisdiction name in /api/me response

---

client/src/App.test.tsx
client/src/App.tsx
client/src/__snapshots__/App.test.tsx.snap
client/src/components/DataEntry/BoardTable.tsx
client/src/components/DataEntry/MemberForm.tsx
client/src/components/DataEntry/SignOff.tsx
client/src/components/DataEntry/_mocks.ts
client/src/components/DataEntry/index.tsx
client/src/components/Header.tsx
client/src/components/HomeScreen.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx
client/src/components/MultiJurisdictionAudit/index.test.tsx
client/src/components/MultiJurisdictionAudit/timers.test.tsx
client/src/components/UserContext.tsx
client/src/types.ts

- Use `null` to represent data still being loaded (our standard pattern)
- Put the `/me` response in a `{ user }` object so that we can easily
extend it with superadmin user info (in a PR coming soon)
- Remove `isAuthenticated`, since it's redundant with `user`, which is
`null` when not authenticated (plus, the meaning of this field will be
less clear once we also have superadmin user info).
- Move the relevant types into the UserContext module

Change UserContext data format

---

server/auth/routes.py
server/tests/test_auth.py

Currently, using an invalid audit board passphrase leads to a database exception. This has happened a few times in production: https://sentry.io/organizations/votingworks/issues/2028541746/.
Instead, we redirect to the login screen with an error message.

Handle invalid audit board passphrases

---

client/src/components/MultiJurisdictionAudit/AASetup/Contests/ContestSelect.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Contests/ContestSelect.tsx

Task: #978 
The standardized contests selection form was breaking when a contest had a dot in its name. This is because Formik uses dot notation field names to access fields, both in the Field `name` prop and in `setFieldValue`.
The recommended fix in the Formik docs is to use the bracket notation: `['field']`, but this won't work if the field name has apostrophes in it.
This fix removes uses of the `name` prop and replaces `setFieldValue` with `setValues`.

Fix bug for standardized contests with a dot in their name

---

client/src/components/Header.test.tsx
client/src/components/Header.tsx
server/auth/lib.py
server/auth/routes.py
server/tests/test_auth.py

Adds a separate logout endpoint for superadmins that logs out both the superadmin and AA/JA (if the superadmin has logged in as an AA/JA). Modifies the existing logout endpoint to not log out the superadmin.

Separate logout for superadmins

---

Pipfile
Pipfile.lock
client/package.json
client/src/App.tsx
client/src/__snapshots__/App.test.tsx.snap
client/src/components/Header.test.tsx
client/src/components/Header.tsx
client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/SupportTools.tsx
client/src/components/SupportTools/index.tsx
client/src/components/SupportTools/support-api.tsx
client/src/components/utilities.ts
client/yarn.lock
mypy.ini
server/api/__init__.py
server/api/support.py
server/auth/routes.py
server/models.py
server/tests/api/test_support.py
server/tests/test_auth.py
server/util/jsonschema.py

Adds a new Support Tools interface (formerly known as the superadmin interface) built in React.
Features:
- Home screen with list of organizations
- Org screen with list of audits, list of audit admins (with login buttons), and form to create new audit admin (including integrating with Auth0)
- Audit screen with list of jurisdictions and list of jurisdiction admins (with login buttons)
I took this opportunity to test out two new libraries to help with data loading (react-query) and forms (react-hook-form).
https://user-images.githubusercontent.com/530106/103838547-31e3ac00-5042-11eb-9fb3-41588a7d9e26.mov

Support Tools interface

---

server/tests/conftest.py

It was incorrectly catching the case where the tests weren't being run
in parallel.

Fix test fixture that resets db

---

client/src/App.tsx
client/src/components/Atoms/Confirm.tsx
client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/SupportTools.tsx
client/src/components/SupportTools/support-api.tsx
server/api/support.py
server/tests/api/test_support.py

- Backend endpoint to clear audit boards
- Button next to each jurisdiction in Support Tools to clear audit boards
- Reusable confirm dialog component + hook
Gonna come back and add unit tests for the Confirm component separately, because I want to get this feature out.
https://user-images.githubusercontent.com/530106/104634119-0d488f00-5655-11eb-866f-a5e48c9dd507.mov

Support Tools - clear audit boards

---

server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

Task: #986 
Adds user-facing error messages for three issues we've seen so far:
- Empty CVR file
- Invalid contest name format (missing the "(Vote For=1)" suffix)
- Tabulator/batch name that doesn't match manifest

Better CVR parsing error messages

---

client/src/components/MultiJurisdictionAudit/RoundManagement/RoundProgress.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/RoundProgress.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/RoundProgress.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/StatusBox/index.test.tsx
client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx

- Fix the status box to only show audit boards complete once they're
signed off
- Add tags/intent to the progress bars for individual audit boards in
order to differentiate which boards have signed off

JA audit board status improvements

---

client/src/__snapshots__/App.test.tsx.snap
client/src/components/Header.tsx
client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/SupportTools.tsx
client/src/components/SupportTools/support-api.tsx
server/api/support.py
server/tests/api/test_support.py

- Reorganize support tools to have a separate screen for each jurisdiction with a list of audit boards and JAs
- Add a button to reopen an audit board after it has signed off
https://user-images.githubusercontent.com/530106/105403986-485f3b00-5bde-11eb-8b2a-1e9b7d050d2f.mov

Support Tools: Reopen audit board

---

server/app.py

This enables us to use `gunicorn --preload` without causing duplicated
db connection errors.

Dispose database engine after app loading

---

.circleci/config.yml

To unblock main until we get it passing reliably.

Disable cypress on CI

---

server/worker/bgcompute.py

Migrations would often hang when the worker was running. The `pg_stat_activity` table would show an "idle in transaction" query coming from bgcompute. Committing the transaction before sleeping seems to solve it!

bgcompute: commit before sleeping

---

client/cypress/end-to-end/ballot-comparison-happy-path.spec.js
client/cypress/end-to-end/ballot-polling-happy-path.spec.js
client/cypress/end-to-end/batch-comparison-happy-path.spec.js
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx
client/src/components/MultiJurisdictionAudit/AASetup/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/index.tsx
client/src/components/MultiJurisdictionAudit/index.tsx

Previously, the progress screen would render briefly after launching the audit before the spinner would get rendered. This happened because the old round data (an empty array) hadn't been updated from the backend yet. To fix this, we use the `startNextRound` function from the same hook that loaded that data, so that it will invalidate and reload the data automatically before resolving the `startNextRound` promise.

Fix progress screen flash when drawing sample

---

client/src/__snapshots__/App.test.tsx.snap
client/src/components/Header.tsx

Previously the header would overflow if you resized the screen to a narrow width.
Before:
After:

Wrap header on narrow screens

---

server/api/audit_boards.py
server/tests/api/test_audit_boards.py

Both on creation of the audit board, and on sign off.

Strip whitespace from audit board member names

---

client/cypress/end-to-end/ballot-comparison-failure-cases.spec.js
client/cypress/end-to-end/ballot-comparison-happy-path.spec.js
client/cypress/end-to-end/ballot-polling-happy-path.spec.js
client/cypress/end-to-end/batch-comparison-happy-path.spec.js
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx

- Disabling audit launch until sample sizes are loaded
**Testing**
- Waiting for the audit launch to be not disabled before clicking in cypress
**Progress**
- It should work, but the cypress tests aren't behaving yet

Waiting for sample sizes before launching

---

server/api/contests.py
server/api/cvrs.py
server/api/rounds.py
server/api/sample_sizes.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison.py

Previously, we computed contest metadata (e.g. total votes, votes for each
choice) based on the CVRs at read time: either when computing the sample size
options or finally when starting the round.
Two issues with this:
1. A bug! There was a guard to make sure we only computed the contest metadata once, which meant that if a jurisdiction changed their CVR after the first time sample sizes were computed, it wouldn't be taken into account.
2. The upcoming redesign to the Review screen shows this computed contest metadata via the /contests endpoint. That meant that both the sample sizes endpoint and the contests endpoint, which both get called by the review screen, were going to need to invoke this computation, so it seemed simpler to just move it to be computed on write so that we didn't …

Set contest metadata from CVRs on write

---

server/api/cvrs.py
server/models.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison.py

Now that we're computing the contest metadata from the CVRs on write, it's possible that it will need to be updated after a CVR is changed. The previous code didn't account for that case.

Fix bug with CVR contest choice metadata

---

client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx

After #1069, the contest metadata needed for sample size validation (total ballots cast) will be available on the contest object in ballot comparison audits, so we can simplify the custom sample size validation.

Simplify custom sample size validation

---

server/api/ballot_manifest.py
server/api/contests.py
server/api/cvrs.py
server/tests/api/test_elections.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison.py

In all audit types except ballot polling, we want the total ballots cast to be independent of the results being audited. This mainly matters in ballot comparison/hybrid, where we were previously computing total ballots cast from the CVR.
Future work:
- Remove the total ballots cast field from the contest setup screen (except in ballot polling)
- In ballot polling, validate the total ballots cast set on the contest setup screen

Set total ballots cast from manifest

---

server/api/standardized_contests.py
server/tests/ballot_comparison/test_standardized_contests.py
server/util/jurisdiction_bulk_update.py
server/util/process_file.py
server/worker/bgcompute.py

Modifies process_file to use a nested transaction so that multiple files can be processed in the same transaction.

Reprocess standardized contests on jurisdiction file change

---

server/models.py
server/tests/ballot_comparison/test_standardized_contests.py

Without the cascade delete-orphan setting, a contest that is removed from the election.contests relationship will have a null election_id, which violates the not null constraint. This setting will cause that orphan contest to get deleted, which is what we want.

Allow deleting contests through election.contests relationship

---

server/api/sample_sizes.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison.py

We were giving the math the number of previously sampled ballots across all
contests, instead of just for the given contest.

Fix ballot comparison round 2 sample sizes

---

server/api/rounds.py
server/tests/hybrid/test_hybrid.py

Task: #1109 
Needed to tweak some data passed into the suite math so that it would keep returning round 1 sample sizes.

Hybrid: fix /sample-sizes after audit launches

---

client/src/components/MultiJurisdictionAudit/index.test.tsx
client/src/components/MultiJurisdictionAudit/timers.test.tsx

Since the test relies on polling, it needs fake timers, otherwise there are timeouts that execute after the test has ended, which messes up other tests.

Move spinner test to timers.test.tsx

---

server/api/ballot_manifest.py
server/tests/batch_comparison/conftest.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/batch_comparison/test_batch_tallies.py

Task: #1130 
Since the batch tallies file depends on the batches created from the manifest, if the manifest changes, we need to reprocess the batch tallies file.

Reprocess batch tallies file when ballot manifest reuploaded

---

server/api/standardized_contests.py
server/tests/ballot_comparison/test_standardized_contests.py

Task: #1125 
If any contests were created based on a previous version of the standardized contests, we need to update them based on the new standardized contests. We delete any contests that are no longer in the standardized contests, and update the contest universe for any that are still there.

Update contests on standardized contests reupload

---

server/util/jurisdiction_bulk_update.py

Now that we are updating the contests when reprocessing the standardized contests file, we don't need to clear them beforehand.

Don't clear contests on jurisdictions file reupload

---

server/api/cvrs.py
server/api/sample_sizes.py
server/tests/hybrid/test_hybrid.py

Task: #1139 
Use the Batch.has_cvrs field (based on the ballot manifest) to avoid loading non-CVR ballots from the CVR.

Hybrid: filter out non-CVR ballots from CVR

---

server/audit_math/suite.py
server/tests/audit_math/test_suite.py

`suite.get_sample_size` now errors if a recount of either strata is expected. 
**Testing**
Modified test cases accordingly. 
**Progress**
Ready.

Now throwing an error if we need to do a full recout before we do it

---

client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx

If there's a CVR validation error (which is returned by the sample size endpoint), the CVR/non-CVR vote totals returned by the contests endpoint will be null, which was causing an error. In that case, we just show empty cells in the vote counts table until the validation error is resolved.

Hide CVR/non-CVR vote counts when CVRs invalid

---

server/migrations/versions/f44bbbb8b076_cvrballot_ballot_position_and_record_id.py
server/migrations/versions/f8e901e92f0a_background_sample_size_options.py

I messed up when rebasing the background sample sizes pull request and put its migration before the CVR ballot migrations in the migration ordering. That meant that it didn't get run automatically on deploy to staging. This should put the background sample sizes migration at the end of the ordering, so it should get run.

Fix migration order

---

server/api/rounds.py
server/api/sample_sizes.py
server/tests/batch_comparison/test_batch_comparison.py

When moving sample size option computation to a background task, I forgot to change the error type for batch tallies validation, since it was hidden in the batch_tallies function. I moved it out to a separate function and changed the error type so that it will be correctly stored and shown to the user (instead of crashing the background task).

Change batch tallies validation errors to UserErrors

---

server/api/sample_sizes.py
server/tests/api/test_sample_sizes.py

Existing audits that were launched before we made a background task for samples sizes won't have a background task. We now expect that after the audit launches, we can load the previously computed sample size options from the cached value from the background task.
This PR changes the sample sizes endpoint to start a background task after the audit launches if there isn't one already in order to backfill this data for existing audits.

Make background sample sizes backwards compatible

---

client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx
client/src/components/MultiJurisdictionAudit/index.test.tsx
client/src/components/MultiJurisdictionAudit/index.tsx
client/src/components/MultiJurisdictionAudit/useRoundsAuditAdmin.ts

We want the review screen to still be viewable, so instead of blocking the whole screen with an error message, we move the error message to the status bar. We also hide the progress table, since it won't be accurate in this state.

Show error drawing sample in the status bar

---

client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx

The conditions here were in the wrong order, causing a loading spinner to be shown instead of the error.

Bugfix: show sample sizes error

---

client/cypress/end-to-end/ballot-comparison-failure-cases.spec.js
client/cypress/end-to-end/batch-comparison-failure-cases.spec.js
client/cypress/support/commands.js

Tests were failing because the (expected) toasts for error message were covering up the user menu that we need to click on for logout.

Cypress: close toasts

---

client/cypress/end-to-end/offline-batch-data-entry-tests.spec.js
client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/OfflineBatchRoundDataEntry.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/_mocks.ts
client/src/components/MultiJurisdictionAudit/RoundManagement/useOfflineBatchResults.ts

- Console warning issue: initial values to be set so that it stops complaining about fields changing between controlled and uncontrolled. For choice results, it was just assigning blank array and there was no values initially. So added code to fetch the choices and assigned a blank value to it. This then required changing the data type of choice results value to `number | string` so that `''` can be assigned. (We could assign 0 as well, but it will then display 0 by default.)
- Dialogs were opening still after results finalized: once the results are finalized, made changes so that when buttons are clicked, the popup doesn’t open.
**Testing**
- Added a cypress test for handling offline batch data entry paths

Batch data entry fixes

---

server/api/rounds.py
server/api/sample_sizes.py
server/tests/api/test_sample_sizes.py

Previously, we needed to be able to compute the round one sample sizes at any time in order to show the round one sample sizes on the Review screen even after the audit launched. Now, since we store the round one sample sizes after computing them in the background, we don't need this anymore.

Remove special case for round one sample sizes

---

Makefile
client/src/components/MultiJurisdictionAudit/Progress/JurisdictionDetail.tsx
client/src/components/MultiJurisdictionAudit/Progress/index.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/_mocks.ts
client/src/components/MultiJurisdictionAudit/RoundManagement/index.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/useBallots.ts
client/src/components/MultiJurisdictionAudit/RoundManagement/useBatchResults.ts
client/src/components/MultiJurisdictionAudit/_mocks.ts

Task: #1213 
Changes the `useBallotCount` hook to `useBallotOrBatchCount`, conditioning on the audit type. Under the hood, we use the existing endpoint to load batches and count them on the frontend, since the number of sampled batches should be small enough that this will be performant (unlike with ballots, where we count them server-side).
Also adds a special case for when no ballots/batches were sampled for that jurisdiction, hiding the usual actions they can take and showing a message instead.

Show batch count, not ballot count, in batch comparison audit

---

client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx

The old language only made sense for more than one ballot/batch. This new language works for one or more ballots/batches.

Tweak JA ballot/batch count to avoid pluralization issues

---

client/cypress/end-to-end/ballot-comparison.spec.js
client/cypress/end-to-end/batch-comparison.spec.js
server/api/jurisdictions.py
server/tests/api/test_jurisdictions_file.py

Remove CSV validation in the endpoint, since the CSV parsing (which happens in the background job) checks the same things.

Clean up jurisdictions file endpoint

---

server/tests/api/test_jurisdictions_file.py
server/util/jurisdiction_bulk_update.py

We were getting an internal database error. Instead, we use our CSV parsing validation to provide a useful error message.

Improve error on duplicate row in jurisdictions file

---

client/src/components/MultiJurisdictionAudit/Progress/index.test.tsx
client/src/components/MultiJurisdictionAudit/Progress/index.tsx
client/src/components/MultiJurisdictionAudit/useJurisdictions.ts
client/src/components/MultiJurisdictionAudit/useSetupMenuItems/_mocks/index.ts
server/api/ballot_manifest.py
server/api/jurisdictions.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/batch_comparison/test_batch_tallies.py
server/tests/hybrid/test_hybrid.py
server/tests/hybrid/test_hybrid_manifests.py

Task: #1214 
Adds a few new columns to the jurisdiction progress screen based on audit type:
- Batch Comparison: Ballots in Manifest, Valid Voted Ballots in Batches
- Ballot Comparison: Ballots in CVR
- Hybrid: Non-CVR Ballots in Manifest, CVR Ballots in Manifest, Ballots in CVR
These new columns are only shown during audit setup.

Jurisdiction progress improvements

---

client/src/components/Atoms/Table.tsx
client/src/components/MultiJurisdictionAudit/Progress/index.test.tsx
client/src/components/MultiJurisdictionAudit/Progress/index.tsx
client/src/components/utilities.test.ts
client/src/components/utilities.ts

Task: #1214 
Adds a button to download the progress table as a CSV. In order to get the data out of the table to download, we read it directly from the DOM. While it would be a bit cleaner and more flexible to generate the CSV directly from React state data, there's not a reasonably straightforward way to access the rendered state of the table component, so we'd have to duplicate the logic that renders the columns (the status column in particular is thorny). The upside of this approach is that users shouldn't be surprised at all - what they see on the page is exactly what they'll get in the CSV (minus formatting).

Audit progress download button

---

client/src/App.test.tsx
client/src/components/HomeScreen.test.tsx
client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx
client/src/components/MultiJurisdictionAudit/_mocks.ts
client/src/components/MultiJurisdictionAudit/index.test.tsx
client/src/components/MultiJurisdictionAudit/index.tsx
client/src/components/MultiJurisdictionAudit/useAuditBoards.ts
client/src/components/MultiJurisdictionAudit/useRoundsAuditAdmin.ts

Task: #1179 
When the sample is being drawn or if drawing the sample errors, the audit hasn't started yet, and the JA can't begin their auditing. So we keep them on the setup screen.

Show JA setup screen while drawing sample/if sample errors

---

server/api/reports.py
server/api/rounds.py
server/audit_math/ballot_polling.py
server/tests/api/snapshots/snap_test_reports.py
server/tests/audit_math/snapshots/snap_test_bravo.py
server/tests/audit_math/test_bravo.py
server/tests/ballot_polling/snapshots/snap_test_ballot_polling.py
server/tests/ballot_polling/test_ballot_polling.py
server/tests/ballot_polling/test_bravo_ballot_polling.py
server/tests/snapshots/snap_test_multi_winner_contest.py
server/tests/snapshots/snap_test_multiple_targeted_contests.py

Task: #1230 
This change only applies to ballot polling audits with online data entry. We count the number of ballots not found by the audit boards and pass that into the ballot polling math, which counts those ballots as a vote for every loser. We also add a note to the audit report about not found ballots.

Ballot polling: count not found ballots for the loser

---

client/src/components/MultiJurisdictionAudit/AASetup/Review/ConfirmLaunch.tsx
client/src/components/MultiJurisdictionAudit/StatusBox/index.test.tsx
client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx
client/src/components/MultiJurisdictionAudit/index.test.tsx
client/src/components/MultiJurisdictionAudit/index.tsx
client/src/components/MultiJurisdictionAudit/timers.test.tsx
client/src/components/MultiJurisdictionAudit/useRoundsAuditAdmin.ts
client/src/components/MultiJurisdictionAudit/useSetupMenuItems/_mocks/index.ts
server/api/rounds.py
server/tests/api/test_rounds.py
server/tests/batch_comparison/test_batch_comparison.py

Task: #1219 
Adds a button to undo launching the audit as long as no jurisdiction has started auditing yet.
https://user-images.githubusercontent.com/530106/122292420-d5b36c80-ceaa-11eb-9420-41d64e95fbd6.mov

Undo audit launch button

---

client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/SupportTools.tsx
client/src/components/SupportTools/support-api.tsx

- When a query errors, catch it using the react-query `onError` handler instead of using the `isError` flag while rendering. Triggering a toast side-effect while rendering can cause duplicate toasts, since rendering might happen more than once.
- Refactor the tests so that we can type check the mock data
- Reorder tests so the error cases are paired with the success cases

Support tools API and test cleanup

---

server/activity_log/slack_worker.py
server/app.py
server/sentry.py
server/worker/bgcompute.py

`slack_worker` wasn't configuring Sentry at all, and `bgcompute` was only configuring it implicitly by importing `app`.

Configure Sentry in all processes

---

client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/SupportTools.tsx
client/src/components/SupportTools/support-api.tsx
server/api/support.py
server/tests/api/test_support.py
server/tests/batch_comparison/test_batch_comparison.py

For ballot polling audits, clear jurisdiction results. For batch comparison audits, clear batch results.
https://user-images.githubusercontent.com/530106/123299573-871b5900-d4ce-11eb-899d-887b1a6a03ea.mov

Support tools: button to clear offline results

---

.coveragerc
server/api/reports.py
server/audit_math/macro.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/snapshots/snap_test_batches.py

Task: #1222 
Reworks `macro.compute_error` to return a `BatchError` dict so that we can return both the raw error in votes and the weighted error (mirroring what we do in `supersimple` for ballot comparison). Then adds the raw error to the audit report, along with the reported results from the batch tallies file. We count and report negative errors as 0, while batches with no error are counted as 0 but reported as blank.

Reported batch results and discrepancies in audit report

---

client/src/components/MultiJurisdictionAudit/StatusBox/index.test.tsx
client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx
client/src/components/MultiJurisdictionAudit/index.tsx

Closes #1238 
**Testing**
- Currently no test updates
**Notes**
So the bug was in JA login after Batch Audit is launched. Basically, for Batch Comparison, as it's about batches, the Audit Board API has numSampledBallots & numAuditedBallots both always as 0. Due to that it shows "1 of 1 Audit Boards complete."
For now, this is a frontend fix by popping "1 of 1 Audit Boards complete" from the details & not thus showing this line for Batch Comparison.
As a backend fix, we would need to update the API to calculate numSampledBallots based on total numBallots across all Batches.

Statusbox fix for batch comparison

---

client/src/components/Atoms/AsyncButton.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Contests/index.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/RoundProgress.test.tsx

- Cleans up some unused variable lint warnings that have been in the codebase for a while but haven't gotten cleaned up yet
**Testing**
- None needed
**Progress**
- All clean now!

Minor cleanups for warnings

---

client/src/components/SupportTools/support-api.tsx
client/src/components/testUtilities.tsx
client/src/components/utilities.ts
mypy.ini
poetry.lock
pyproject.toml
server/app.py
server/tests/test_auth.py

Use the flask_seasurf library (recommended by the docs of flask_talisman, which we already use in Arlo) to implement CSRF protection for all POST/PUT/DELETE API endpoints using a token set in a cookie.

CSRF protection

---

client/src/App.test.tsx
client/src/components/HomeScreen.test.tsx
client/src/components/MultiJurisdictionAudit/index.test.tsx
client/src/components/MultiJurisdictionAudit/index.tsx
client/src/components/MultiJurisdictionAudit/useCSV.ts

Previously we tried loading the ballot manifest, batch tallies, and CVRs for all audit types. This removes unnecessary API calls to load files that don't apply for a specific audit type.

Load only JA files used for audit type

---

client/src/components/MultiJurisdictionAudit/CSVForm/index.tsx

Previously, the CSVFile component was set up to use a key to force the form to rerender every time we reloaded a new file from the server. This was proving to be problematic in some other changes to the form I was working on, so I figured out a way to preserve the existing behavior without rerendering the entire form on every server file reload.

Refactor CSVFile component  to prevent extra rerenders 

---

client/src/components/MultiJurisdictionAudit/AASetup/Participants/_mocks.ts
client/src/components/MultiJurisdictionAudit/AASetup/Participants/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Participants/index.tsx
client/src/components/MultiJurisdictionAudit/index.test.tsx
client/src/components/MultiJurisdictionAudit/index.tsx
client/src/components/MultiJurisdictionAudit/useCSV.ts

Task: #1262 
After a file gets reprocessed due to a file it depends on being changed, we need to reload that file to see what happened (specifically, we need to show errors).

Reload files on frontend after reprocessing

---

.circleci/config.yml

On test failures, Cypress produces screenshots and videos of the test run. We store these as artifacts in CircleCI so that we can go see what happened.

Store Cypress screenshots/videos in CircleCI

---

server/activity_log/slack_worker.py
server/api/ballot_manifest.py
server/api/batch_tallies.py
server/api/cvrs.py
server/tests/api/test_activity.py
server/tests/snapshots/snap_test_slack_worker.py
server/tests/test_slack_worker.py

Since file uploads happen in the background worker, they don't have access to the session of the request that initiated the upload, so when recording the file upload activity, they couldn't report which user uploaded the file. To fix this, we pass the user info in as arguments to the background task.

Record user info in file upload activity

---

client/src/App.test.tsx
client/src/App.tsx
client/src/__snapshots__/App.test.tsx.snap
client/src/components/Header.test.tsx
client/src/components/HomeScreen.test.tsx
client/src/components/HomeScreen.tsx
client/src/components/MultiJurisdictionAudit/ActivityLog.test.tsx
client/src/components/MultiJurisdictionAudit/ActivityLog.tsx
client/src/components/MultiJurisdictionAudit/_mocks.ts
client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/support-api.tsx
client/src/components/UserContext.tsx
client/src/components/testUtilities.tsx
server/api/elections.py
server/auth/routes.py
server/models.py
server/tests/api/test_elections.py
server/tests/api/test_support.py
server/tests/test_auth.py

Previously, we loaded the list of an audit admin's audits with their user data. This caused complications in a few different places, which we previously hacked around. A bug appeared when leaving an audit admin page open when logged in as a different user type, and then trying to load the home screen for the audit admin page again.
To fix this, we create a separate endpoint for loading the list of audits and decouple that from loading the user data. This impacts:
- loading the list of audits on login
- reloading the list of audits after deleting an audit
- *not* reloading the list of audits after creating an audit, since we immediately redirect to the setup page

Bugfix: load audits separately from user data

---

server/api/rounds.py
server/tests/test_sample_all_ballots.py

When we moved drawing the sample to the background, this error should have been converted from an HTTP Conflict error to a UserError. But I missed it due to no test coverage.

Fix error sampling all ballots with multiple targeted contests

---

server/api/support.py
server/tests/api/test_support.py

Task: #1329 
While we were saving the email as lowercase (due to the validator on User.email), we weren't finding existing audit admins with lowercase emails.

Bugfix: Create audit admins with email case-insensitity

---

server/api/ballot_manifest.py
server/api/contests.py
server/api/cvrs.py
server/api/jurisdictions.py
server/api/standardized_contests.py
server/tests/ballot_comparison/test_ballot_comparison.py
server/tests/ballot_comparison/test_standardized_contests.py

If standardized contests/jurisdictions are reuploaded and change after contests are already created, the contest universe for those contests will change (which we already handled). If the contest universe changes, however, that means that any contest metadata that was computed from files uploaded in that universe (manifests, CVRs) also needs to be updated.
This change ensures that we recompute that metadata in those two cases. It also factors out the recomputing of metadata functionality into one function to make sure that it happens consistently whenever any dependencies change.

Recompute contest metadata when standardized contests/jurisdictions change

---

client/cypress/end-to-end/full-hand-tally.spec.js
client/src/components/MultiJurisdictionAudit/Progress/JurisdictionDetail.tsx
client/src/components/MultiJurisdictionAudit/Progress/index.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/FullHandTallyDataEntry.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/FullHandTallyDataEntry.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/FullHandTallyDataEntry.test.tsx.snap
client/src/components/MultiJurisdictionAudit/RoundManagement/_mocks.ts
client/src/components/MultiJurisdictionAudit/RoundManagement/index.test.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx
client/src/components/MultiJurisdictionAudit/RoundManagement/useFullHandTallyResults.ts
server/api/__init__.py
server/api/full_hand_tally.py
server/api/jurisdictions.py
server/api/reports.py
server/migrations/versions/266fba5a5c8a_rename_offlinebatchresult_to_.py
server/models.py
server/tests/snapshots/snap_test_full_hand_tally.py
server/tests/test_full_hand_tally.py

The previous naming for this feature "offline batch results" was confusingly similar to two other parts of Arlo - "offline results" for ballot polling audits, and "batch results" for batch comparison audits.
In order to make it clear that this feature is meant specifically for full hand tallying, we rename it just that: full hand tally batch results.
This will make things clearer alongside some upcoming changes to how we detect and flag full hand tallies.

Rename offline batch results -> full hand tally batch results

---

client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx
server/api/rounds.py
server/tests/hybrid/test_hybrid.py

Previously, we didn't require the frontend to compute the total sample size based on the custom CVR/non-CVR strata sample sizes. In order to ensure that every selected RoundContest sample size stored in the database has a correct `size` field, we make things uniform by requiring this edge case behave like every other case.

Compute total hybrid custom sample size on frontend

---

.coveragerc
client/src/components/MultiJurisdictionAudit/RoundManagement/_mocks.ts
client/src/components/MultiJurisdictionAudit/StatusBox/index.test.tsx
client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx
client/src/components/MultiJurisdictionAudit/useRoundsAuditAdmin.ts
client/src/components/MultiJurisdictionAudit/useSetupMenuItems/_mocks/index.ts
server/api/rounds.py
server/tests/api/test_rounds.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/test_full_hand_tally.py

Task: #1335 
When the sample size selected indicates we need a full hand tally in later rounds of the audit, we want to display that to the AA. In order to differentiate this from when we're in full hand tally mode intentionally, we introduce a new flag: needsFullHandTally

Status box message when full hand tally is needed in later rounds

---

client/cypress/end-to-end/ballot-comparison.spec.js
client/src/components/DataEntry/Ballot.test.tsx
client/src/components/DataEntry/Ballot.tsx

Added a green confirmation toast for when a ballot data entry is completed and when the next ballot is shown to provide clear and unambiguous direction to audit board members that the next ballot is there to be audited.
**Testing**
- Updated cypress to account for the toast
**Progress**
Manually tested and works on web and mobile.

Adding confirmation toast for ballot data entry

---

client/src/components/MultiJurisdictionAudit/AASetup/Review/__snapshots__/index.test.tsx.snap
client/src/components/MultiJurisdictionAudit/AASetup/Review/_mocks.ts
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx
client/src/components/MultiJurisdictionAudit/timers.test.tsx

- We were using the total ballots cast instead of the total batches to check if the sample size was a full hand tally, which was incorrect
- Also, we were validating the custom sample size in terms of the participating jurisdictions for the entire audit, not the specific contest (though since we only allow 1 contest for batch comparison audits, it was the same, it seemed like a latent bug waiting to happen).
Since the two pieces of logic use the same calculation (the total ballots/batches in the contest) I did a little refactoring to clean that up.

Fix full hand tally warning for batch comparison audit

---

client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx
client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx
server/api/rounds.py
server/tests/ballot_comparison/test_ballot_comparison.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/hybrid/test_hybrid.py

We decided to show a warning but not disallow starting batch comparison audits that sample all batches.

Allow batch comparison full hand tally

---

server/api/ballot_manifest.py
server/api/batch_tallies.py
server/api/cvrs.py
server/api/jurisdictions.py
server/api/standardized_contests.py
server/tests/api/test_activity.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/util/test_csv_parse.py
server/util/csv_parse.py

While most of our CSV parsing code already uses a streaming framework, there were a few places where we cheated and loaded the whole file into memory, namely:
- Decoding
- Validating that the file is not empty
- Tracking parsing progress (getting the total lines)
This PR changes each of these pieces to be streaming-compatible (but doesn't actually stream the file contents, since there's no way to stream it out of one field in the database). This sets us up for streaming file contents from external storage.

Remove CSV streaming obstacles

---

server/api/ballot_manifest.py
server/api/ballots.py
server/api/batch_tallies.py
server/api/batches.py
server/api/cvrs.py
server/api/jurisdictions.py
server/api/reports.py
server/api/standardized_contests.py
server/util/csv_download.py

Prep work for external file storage. Change our CSV download endpoint helper to take a stream (even though we just use an in-memory buffer for the time being).

Enable streaming for CSV download endpoints

---

scripts/migrate-files-to-s3.py

Doing this separately from our regular database migrations since it relies on an external service, so it doesn't really make sense to run it automatically for anyone who is using the migrations.
Ran locally and completed in a few minutes with no errors. Notably, found 10 orphan files that were no longer attached to any audit.

Script to migrate files from database to s3

---

client/cypress.json

Default timeout is 4 seconds, increasing to 10 seconds. It seemed like there were some intermittent failures related to file uploads, which might take a few seconds.

Increase default Cypress timeout

---

scripts/migrate-files-to-s3.py

Don't try to compare file contents in S3 and the database for files that were written after the first S3 deploy and therefore were never stored in the db.

Fix S3 migration script

---

server/api/ballot_manifest.py
server/api/batch_tallies.py
server/api/cvrs.py
server/api/jurisdictions.py
server/api/standardized_contests.py
server/tests/util/test_file_storage.py
server/util/file.py

This is a more generic interface that matches retrieve_file. And it will be useful when we start zipping multiple uploaded files together before storing.

Change store_file to take a stream instead of FileStorage

---

client/src/components/MultiJurisdictionAudit/index.test.tsx

These tests were failing every once in a while. I'm not 100% sure why, but I think it had something to do with polling for file processing status. So I just modified the tests so that they don't have any polling loops (by changing the API response to not have a "processing" phase and skip straight to "processed"). The test should still test the same thing, but hopefully not flake out.

Fix flaky file upload tests

---

server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

Previously, we just concatenated the ballots files in the order they were uploaded. Instead, we should order the files by the first CVR number in each file (since the ballots are ordered by CVR number within the file).

ES&S CVRs: ensure ballots files are parsed in order of CVR number

---

client/cypress/end-to-end/ballot-comparison.spec.js
client/src/components/DataEntry/index.test.tsx
client/src/components/DataEntry/index.tsx

Task: #1408 
After confirming a ballot selection, the audit board should be taken to
the next unaudited ballot.

Skip to next unaudited ballot

---

server/api/ballots.py
server/tests/api/snapshots/snap_test_ballots.py
server/tests/api/test_ballots.py

Task: #1408 
- Don't return them in the AB ballot list API call
- Don't allow auditing them again

Hide ballots audited in previous rounds from audit board

---

server/api/rounds.py
server/audit_math/macro.py
server/audit_math/sampler.py
server/tests/audit_math/test_macro.py

Task: #1371 
Change `macro.compute_risk` to take an ordering of the sampled batches by ticket number instead of just the number of times each batch got sampled. Compute the p-value by evaluating batch taints in sample order, bailing once we get below the risk limit.
Also added type checking to test_macro.py by adding a `None` return type to the test functions.

Macro: Compute p-value using sample order

---

server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

Task: #1421 
We previously assumed the ballots files would be ordered by the "Cast Vote Record" column, but it turns out that's not true. So we sort each one in memory for now, since the files we've seen so far seem to be small enough that it's not an issue.

ESS CVRs: sort ballots files

---

client/src/components/Atoms/CSVForm.tsx
client/src/components/AuditAdmin/AuditAdminView.test.tsx
client/src/components/AuditAdmin/Setup/Participants/Participants.test.tsx
client/src/components/AuditAdmin/Setup/__snapshots__/Setup.test.tsx.snap
client/src/components/JurisdictionAdmin/JurisdictionAdminView.test.tsx
client/src/components/JurisdictionAdmin/__snapshots__/JurisdictionAdminView.test.tsx.snap
client/src/components/__snapshots__/HomeScreen.test.tsx.snap

Previously, all files uploaded were CSVs, now for Hart CVRs, we also
accept a zip, so we just change the copy to be generic.

Change JA file upload form copy to "file" instead of "csv"

---

server/tests/audit_math/test_minerva.py

I set up a new computer and some of the test assertions started failing due to tiny differences in floats. I saw that some tests already used `approx` to deal with this, so I added that where necessary to pass.

Use approximate comparison in Minerva tests

---

server/audit_math/supersimple.py
server/tests/audit_math/test_supersimple.py

`supersimple.nMin` expects the number of expected discrepancies, not the rate. We were passing the number of expected one-vote discrepancies but the rate of expected two-vote discrepancies.

Fix ballot comparison round 2 sample size

---

server/audit_math/minerva.py
server/tests/audit_math/test_minerva.py

Some Minerva doctests need pytest.approx to account for precision issues. Doctests don't support this, so we move them to the test_minerva.py test file.

Move Minerva doctests to test file to use approx

---

server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

Windows seems to use mimetype `application/x-zip-compressed` instead of `application/zip`.

Allow Windows zip mimetype for Hart CVR uploads

---

client/src/components/Atoms/StatusBox.test.tsx
client/src/components/Atoms/StatusBox.tsx
client/src/components/AuditAdmin/AuditAdminView.tsx
client/src/components/AuditAdmin/Setup/Review/Review.test.tsx
client/src/components/AuditAdmin/Setup/Review/Review.tsx
client/src/components/AuditAdmin/Setup/Review/useSampleSizes.ts
client/src/components/AuditAdmin/useRoundsAuditAdmin.ts
client/src/components/_mocks.ts
server/api/rounds.py
server/api/sample_sizes.py
server/tests/api/snapshots/snap_test_sample_sizes.py
server/tests/api/test_ballots.py
server/tests/api/test_jurisdictions.py
server/tests/api/test_rounds.py
server/tests/api/test_sample_sizes.py
server/tests/api/test_support.py
server/tests/ballot_comparison/test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison_manifests.py
server/tests/ballot_comparison/test_contest_name_standardizations.py
server/tests/ballot_polling/test_minerva_ballot_polling.py
server/tests/batch_comparison/conftest.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/batch_comparison/test_batches.py
server/tests/conftest.py
server/tests/hybrid/snapshots/snap_test_hybrid.py
server/tests/hybrid/test_hybrid.py
server/tests/test_full_hand_tally.py
server/tests/test_multi_winner_contest.py
server/tests/test_multiple_targeted_contests.py
server/tests/test_offline_data_entry.py

Task: #1438 
Best reviewed commit-by-commit.
- First, we add the ability for the /sample-sizes endpoint to compute later round sample sizes
- Second, we use that new ability to show the sample sizes in the AA status box before starting another round
- Last, we remove the code in the backend that computed and chose the sample size for later rounds while drawing the sample, instead sending it from the frontend (this matches the round 1 sample size data flow and also sets us up to allow the user to modify later round sample sizes if we ever want that)
Due to some constraints with what the StatusBox component currently supports, I didn't do much fancy design for now. Ultimately, I think it would make sense to rethink this UI entirely so that viewing/editing sample sizes looks the same in the …

Show sample sizes to audit admin in later rounds

---

client/src/components/AuditBoard/AuditBoardView.test.tsx
client/src/components/AuditBoard/Ballot.test.tsx
client/src/components/AuditBoard/Ballot.tsx
client/src/components/AuditBoard/BallotAudit.tsx
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/Ballot.test.tsx.snap
client/src/components/__snapshots__/HomeScreen.test.tsx.snap

Issue link: https://github.com/votingworks/arlo/issues/1434
This PR adds batch name and ballot number to the audit board confirmation modal header, allowing audit board users to confirm not only contest selections but also that they've entered information for the correct ballot.
_Before (left) and after (right)_
_With a long batch name_
Confirmed with Ginny that we're happy with this design! 🎨 ✅
While I was at it, I also made an unrelated tweak to the "Blank vote" button, switching it to title case ("Blank Vote") for consistency with other buttons and instructional copy.

Add batch name and ballot number to audit board confirmation modal header

---

server/tests/util/test_csv_parse.py
server/util/csv_parse.py

We have some logic to auto-detect total rows (which aren't allowed) if the last row in the CSV has a value that is the sum of all the other rows for that column. This logic shouldn't apply for columns with all 0s, since that doesn't indicate a total row. This case won't happen often (probably only for batch tallies where a candidate got 0 votes - very rare). But still good to guard against.

CSV parse: don't detect total row for column that sums to 0

---

.gitignore
client/src/components/AuditAdmin/AuditAdminView.test.tsx
client/src/components/AuditAdmin/AuditAdminView.tsx
client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/AuditAdmin/Progress/Progress.tsx
client/src/components/AuditAdmin/Setup/Contests/ContestForm.tsx
client/src/components/AuditAdmin/Setup/Contests/ContestSelect.tsx
client/src/components/AuditAdmin/Setup/Review/Review.tsx
client/src/components/AuditAdmin/Setup/Setup.test.tsx
client/src/components/AuditAdmin/timers.test.tsx
client/src/components/useJurisdictions.ts

This will enable file uploads/downloads on the progress screen (coming up in the next PR) to invalidate and reload the jurisdictions status using react-query's query invalidation functionality. It's also a step towards the bigger project of moving to react-query. In this case, to keep scope small, I only migrated the necessary component and left the old hook around but marked it deprecated.

Use react-query for useJurisdictions hook on progress screen

---

client/src/components/AuditBoard/Ballot.tsx

Fix audit board confirmation modal title wrapping

---

client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/JurisdictionAdmin/RoundManagement.test.tsx
client/src/components/JurisdictionAdmin/RoundManagement.tsx
client/src/components/JurisdictionAdmin/__snapshots__/RoundManagement.test.tsx.snap

All in the PR title! We concluded that the "Aggregated" in the copy felt redundant
-----
_Before and after_
-----
Made the same change to the ballot retrieval buttons for non-batch audits
```
$ git grep "Aggregated"
$
```

Remove redundant "Aggregated" from batch/ballot retrieval list buttons

---

server/api/sample_sizes.py
server/tests/hybrid/test_hybrid.py

If the audit admin enters total vote counts for a contest choice that are less than the number of votes for that choice in the CVRs, something is wrong!

Hybrid: validate CVR votes aren't more than contest settings votes

---

client/src/components/AuditAdmin/Setup/Participants/Participants.test.tsx

We have a test that sporadically fails in CircleCI. Jonah has also seen it fail locally.
Our best theory right now is that the default `findByText` timeout (1000ms) is too short for one of the lookups in the test. Dropping the timeout to 500ms, I was able to consistently repro the error locally, giving credence to this theory!
I'm bumping the relevant timeout in this test (and another very similar test to be safe) to 2000ms accordingly.

Bump findByText timeout to decrease test flakiness

---

client/src/App.tsx
client/src/components/Atoms/FileUpload.test.tsx
client/src/components/Atoms/FileUpload.tsx
client/src/components/AuditAdmin/AuditAdminView.test.tsx
client/src/components/AuditAdmin/Progress/JurisdictionDetail.test.tsx
client/src/components/AuditAdmin/Progress/JurisdictionDetail.tsx
client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/AuditAdmin/Setup/Review/__snapshots__/Review.test.tsx.snap
client/src/components/AuditAdmin/useSetupMenuItems/_mocks.ts
client/src/components/JurisdictionAdmin/BatchRoundDataEntry.test.tsx
client/src/components/JurisdictionAdmin/_mocks.ts
client/src/components/__snapshots__/HomeScreen.test.tsx.snap
client/src/components/_mocks.ts
client/src/components/testUtilities.tsx
client/src/components/useFileUpload.ts
client/src/components/useJurisdictions.ts
server/api/ballot_manifest.py
server/api/batch_tallies.py
server/api/cvrs.py
server/tests/api/test_ballot_manifest.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/batch_comparison/test_batch_tallies.py

Task: #1439 
Gives audit admins the ability to upload jurisdiction files in the jurisdiction detail modal on the progress screen.
Details of the changes are in each commit.
Demo video (seemed to be too large for Github): https://drive.google.com/file/d/1ovUio7uelbb7Or82N23IQb6RZk8IzowB/view?usp=sharing

Allow audit admins to upload jurisdiction files

---

client/src/components/AuditAdmin/Progress/JurisdictionDetail.test.tsx
client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/JurisdictionAdmin/RoundManagement.test.tsx
client/src/components/JurisdictionAdmin/generateSheets.test.tsx

We've been seeing console errors during tests that cover our use of jspdf-autotable.
Despite the above error, our PDF tables are fitting on the page and rendering fine.
This is because we aren't always passing options through to the jsPDF mock used by tests. So while we're [using pt units when creating batch tally sheets](https://github.com/votingworks/arlo/blob/2d90eb4dc394a2f77c7607ba59925a4a55f55843/client/src/components/JurisdictionAdmin/generateSheets.ts#L217), some tests are [using the default mm units](https://github.com/votingworks/arlo/blob/2d90eb4dc394a2f77c7607ba59925a4a55f55843/client/src/components/AuditAdmin/Progress/JurisdictionDetail.test.tsx#L38). Our [table cell min width of 100](https://github.com/votingworks/arlo/blob/2d90eb4dc394a2f77c7607ba59925a4a55f55843/client/src/ …

Pass options through to jsPDF mock

---

client/src/components/AuditAdmin/Progress/JurisdictionDetail.test.tsx
client/src/components/AuditAdmin/Progress/JurisdictionDetail.tsx
client/src/components/AuditAdmin/Progress/Progress.tsx
client/src/components/useFileUpload.ts

There was a small bug where after deleting a CVR file/reuploading a new
CVR file, the latest file state wasn't showing up in the detail modal, which
was causing the CVR file type dropdown to be incorrectly
enabled/disabled.
The root cause of this was that the jurisdiction progress screen was
storing the entire jurisdiction object in state for whichever
jurisdiction's detail modal was open. When the jurisdictions list was
refetched, that stale object was sticking around. I fixed that by
switching to only storing the jurisdiction id in state.
Then, I realized that it would be snappier to not even use that
jurisdiction list data in the modal, but to instead rely entirely on the
useCVRs response (which updates quicker). This is also cleaner and
better matches the data pattern we use for the …

Fix AA uploading jurisdiction files form state bug

---

server/audit_math/bravo.py
server/tests/audit_math/test_bravo.py

If any of the bravo sample sizes is 0, we shouldn't return it. That way, we never end up in a broken state with a 0 sample size.

Bugfix: Don't return 0 sample size from BRAVO math

---

server/tests/ballot_comparison/test_cvrs.py
server/tests/test_background_tasks.py
server/worker/tasks.py
server/worker/worker.py

Any error that occurs during a task that we can catch and save to the
database, we should send to Sentry but not crash the worker, since it's
safe to continue working. Any error that happens in the rest of the
worker outside of the task context can still crash as before.

Don't crash worker on caught task errors

---

arlo.code-workspace

For some reason, the existing setting of prettier as the default formatter all of a sudden made Python formatting stop working. This was the suggested fix.

chore: Add default formatter for python

---

scripts/fix-ess-cvr-quotes.py
scripts/manifest-for-cvr.py
server/api/cvrs.py
server/tests/ballot_comparison/snapshots/snap_test_cvrs.py
server/tests/ballot_comparison/test_cvrs.py

A new version of ES&S creates different ballots files than we previously expected. This PR updates the CVR parsing to handle this new file format.
Also adds a script to fix misquoted fields in ES&S ballots and CVR files.

Parse updated ES&S ballots files

---

client/src/components/Atoms/CSVForm.tsx
client/src/components/Atoms/FileUpload.test.tsx
client/src/components/Atoms/FileUpload.tsx
client/src/components/AuditAdmin/Progress/JurisdictionDetail.test.tsx
client/src/components/AuditAdmin/Progress/JurisdictionDetail.tsx
client/src/components/JurisdictionAdmin/JurisdictionAdminView.test.tsx
server/api/cvrs.py
server/tests/ballot_comparison/snapshots/snap_test_cvrs.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/helpers.py
server/util/csv_parse.py
server/util/file.py

_Commit-by-commit reviewing recommended_
Issue link: https://github.com/votingworks/arlo/issues/1505
This PR updates Hart CVR parsing to handle scanned ballot information CSVs for Washington and potentially others down the road. Lots of additional context can be found in the linked issue!
As you can see in these screencaptures, providing a scanned ballot information CSV is optional. In the first upload, we provide both a CVRs ZIP and a scanned ballot information CSV. In the second upload, we only provide a CVRs ZIP. And in the third upload, we only provide a scanned ballot information CSV, which results in an error. Both jurisdiction managers and audit admins can upload scanned ballot information CSVs.
_Jurisdiction manager UI_
https://user-images.githubusercontent.com/12616928/180813935-7 …

Update Hart CVR parsing to handle scanned ballot information CSVs

---

server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

This PR addresses an alert for a Clear Ballot CVR file that actually turned out not to be a Clear Ballot CVR file at all. More specifically, the file had no contest columns (columns beginning with `"Choice_"`), resulting in this "find" operation raising a `StopIteration` exception:
```python
first_contest_column = next(
i for i, header in enumerate(headers) if header.startswith("Choice_")
)
```
There's a broader bucket of errors here: uploading the wrong file. We typically catch these errors downstream and surface them as user errors. Once in a while, though, a wrong file triggers a non-user error, as happened here. It's not yet clear to me what a generalized fix for this would look like. We could as a matter of habit encode more assumptions about headers for each CVR file type upfront.

Verify that Clear Ballot CVR file has contest columns

---

.circleci/config.yml

Issue link: https://github.com/votingworks/arlo/issues/1562
This PR updates Arlo CI to use CircleCI browser tools to install Chrome for Cypress tests. Arlo CI currently installs Chrome manually. This approach recently broke, and the new approach should be more robust. The new approach also mirrors what we do in vxsuite.

Use CircleCI browser tools to install Chrome for Cypress tests

---

server/api/audit_boards.py
server/api/support.py
server/tests/api/test_audit_boards.py

A first step for https://github.com/votingworks/arlo/issues/1499, this PR adds an audit admin endpoint for reopening an audit board. We currently only have an endpoint for support users.

Add audit admin endpoint for reopening an audit board

---

server/api/support.py
server/tests/api/test_support.py

Another step for https://github.com/votingworks/arlo/issues/1499, this PR adds a support user endpoint for reopening the current audit round. We currently only have [a script](https://github.com/votingworks/arlo/blob/main/scripts/reopen-round.py) for this.

Add support user endpoint for reopening current round

---

server/api/rounds.py
server/api/support.py
server/tests/api/test_support.py

Another step for https://github.com/votingworks/arlo/issues/1499, this PR adds a support user endpoint for undoing the start of an audit round. We currently only have an endpoint for audit admins.
Should be the last new endpoint needed for https://github.com/votingworks/arlo/issues/1499!

Add support user endpoint for undoing round starts

---

client/src/components/Atoms/StatusBox.test.tsx
client/src/components/Atoms/StatusBox.tsx
client/src/components/SupportTools/RoundsTable.tsx
client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/SupportTools.tsx
client/src/components/SupportTools/support-api.tsx
client/src/components/__snapshots__/HomeScreen.test.tsx.snap
server/api/support.py
server/tests/api/test_support.py

_Commit by commit reviewing recommended_
The last in a series of PRs for https://github.com/votingworks/arlo/issues/1499!
This PR gives support users buttons for undoing round starts and reopening rounds through a new round summary table. This closes the loop on a flow for rolling back from round 2 to correct mistakes from round 1.
_Round 2 started but not yet completed_
_Round 2 start undone, Round 1 not yet reopened_
_Audit not yet started_
_In action, undoing Round 2 start and reopening Round 1_
https://user-images.githubusercontent.com/12616928/187302082-45fa46e7-33a9-45f9-a184-53ff25c6b8e5.mov

Give support users buttons for undoing round starts and reopening rounds

---

Makefile
client/package.json
client/src/App.test.tsx
client/src/components/Atoms/Form/FormField.tsx
client/src/components/Atoms/Form/__snapshots__/FormField.test.tsx.snap
client/src/components/AuditAdmin/timers.test.tsx
client/src/components/AuditAdmin/useSetupMenuItems/_mocks.ts
client/src/components/SupportTools/SupportTools.tsx
client/src/components/useContestsBallotComparison.ts
client/yarn.lock

Task: #1528 
Arlo was on Node v12. Vite requires Node v14+. Node 16 is the latest LTS version.
Required small upgrades to @testing-library/react and typescript in order to get past some errors. I tried to make the smallest possible version upgrades that would fix the errors for now, since upgrading TypeScript especially will be a much bigger task. These upgrades in turn caused some new lint errors, which were mostly auto-fixable.

Upgrade to Node v16

---

app.json

Poetry 1.2 was released, deprecating the old Poetry install script used by the python-poetry-buildpack. Here we temporarily use a forked version that is waiting to be merged into the main buildpack repo: https://github.com/moneymeets/python-poetry-buildpack/pull/44.

Temporarily use forked poetry buildback to work around deprecation

---

client/src/components/AuditAdmin/Progress/JurisdictionDetail.test.tsx
client/src/components/AuditAdmin/Progress/JurisdictionDetail.tsx

I recently realized that https://github.com/votingworks/arlo/pull/1573, which moved the ability to reopen audit boards from support users to audit admins, resulted in a loss of functionality, namely the ability to reopen audit boards _before_ all audit boards in a jurisdiction have signed off. This PR restores that ability!

Allow AAs to reopen audit boards before all have signed off

---

client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/SupportTools.tsx
server/api/support.py
server/tests/api/test_support.py

One of many support user improvements that we're considering for https://github.com/votingworks/arlo/issues/1433, this PR adds a support user button for logging in to an audit directly as an arbitrary audit admin. (Ginny has confirmed that picking any arbitrary audit admin in the relevant organization is fine and even desirable.)
Prior to this PR, there was no login button on the individual audit screen for support users, and support users still had to select an audit after logging in as an audit admin, making a number of support user flows clunky.
https://user-images.githubusercontent.com/12616928/188958673-b7483ce1-250a-49c8-a94f-dc619ccedc6b.mov

Add support user button for logging in to audit directly as arbitrary audit admin

---

client/src/App.tsx
client/src/components/Atoms/Wrapper.tsx
client/src/components/AuditAdmin/__snapshots__/AuditAdminView.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/Ballot.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/BoardTable.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/SignOff.test.tsx.snap
client/src/components/JurisdictionAdmin/__snapshots__/JurisdictionAdminView.test.tsx.snap
client/src/components/PublicPages/AuditPlanner.tsx
client/src/components/PublicPages/NotFound.tsx
client/src/components/PublicPages/PublicPages.tsx
client/src/components/__snapshots__/HomeScreen.test.tsx.snap

A first step for https://github.com/votingworks/arlo/issues/1440 (the new public audit planner), this PR sets up scaffolding for public Arlo pages.
Once we deploy this, it will be possible to navigate to https://arlo.voting.works/planner and see the incomplete audit planner. I don't believe that this is a big deal but correct me if I'm wrong - happy to introduce some sort of gating logic for prod!
https://user-images.githubusercontent.com/12616928/188966061-892f14c0-5544-4ab3-88c2-6154faa51a8b.mov

Set up scaffolding for public Arlo pages

---

server/api/support.py
server/auth/routes.py
server/tests/api/test_support.py
server/util/redirect.py

To ensure that login links always redirect to the frontend dev server at port 3000 (rather than backend dev server at 3001), we use the same fix we used for auth redirects when migrating to Vite.

Use correct port for support login links in development

---

client/src/components/PublicPages/AuditPlanner/AuditPlanner.test.tsx
client/src/components/PublicPages/AuditPlanner/ElectionResultsCard.tsx
client/src/components/__snapshots__/HomeScreen.test.tsx.snap

Some simple UI polish that I decided to move into its own PR since it's unrelated to the other PR I'm working on to complete the second half of the audit planner UI! Specifically decreases the size of the input labels in the election results card, moves the candidate remove buttons such that the empty space on the right of the card is no more, and tweaks the uneditable state.
Reviewing with [`?w=1`](https://github.com/votingworks/arlo/pull/1596/files?w=1) recommended
https://user-images.githubusercontent.com/12616928/190547570-2999902e-cc41-4a27-b373-49c843adc7e2.mov
Regarding the smaller input labels, I did look ahead to the "Audit Plan" card and verified that the smaller labels will look okay more generally.

Polish audit planner election results card

---

client/src/components/Atoms/Count.test.tsx
client/src/components/Atoms/Count.tsx
client/src/components/PublicPages/AuditPlanner/AuditPlanner.test.tsx
client/src/components/PublicPages/AuditPlanner/ElectionResultsCard.tsx
client/src/components/PublicPages/AuditPlanner/SampleSize.test.tsx
client/src/components/PublicPages/AuditPlanner/SampleSize.tsx

_Reviewing by commit recommended_
Issue link: https://github.com/votingworks/arlo/issues/1440
A quick piece of audit planner UI polish, this PR adds commas to make large numbers more readable. This includes sample sizes and election results numbers (the latter only after submission).
https://user-images.githubusercontent.com/12616928/192352255-1441f101-bb8d-49ac-90b2-4d8b4f938062.mov

Add commas to make large numbers in audit planner more readable

---

client/src/components/PublicPages/AuditPlanner/AuditPlanner.test.tsx
client/src/components/PublicPages/AuditPlanner/ElectionResultsCard.tsx
server/api/public.py
server/tests/api/test_public.py

Issue link: https://github.com/votingworks/arlo/issues/1605
There's a natural human impulse when provided a calculation tool to enter the largest numbers possible 😆
As much as I feel this impulse too, these super large numbers can crash our underlying sample size math. Rather than playing whack-a-mole with all the places that large numbers can break our sample size math, this PR limits the size of numbers provided to the audit planner. I've settled on a limit of `1e15` (1 quadrillion), which should, as noted in the code:
> Leave enough buffer to support an election of galactic scale while making it hard for users to crash the sample size math by holding down the 0 key :D

Limit size of numbers provided to audit planner

---

client/src/components/Atoms/SegmentedControl.tsx
client/src/components/PublicPages/AuditPlanner/AuditPlanCard.tsx
client/src/components/PublicPages/AuditPlanner/AuditPlanner.test.tsx
client/src/components/PublicPages/AuditPlanner/ElectionResultsCard.tsx
client/src/utils/responsiveness.ts

Issue link: https://github.com/votingworks/arlo/issues/1614
This PR makes the audit planner mobile friendly in the most basic way possible (still leaving plenty of room for improvement but at least ensuring that the page isn't broken on mobile).
It also adds utils for responsive design that'll hopefully come in handy with upcoming work to make the audit board screens mobile friendly / responsive! I'm excited about these! [`window.matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia), which the utils use under the hood, is magic 🪄 and basically brings the power of CSS media queries to JS.
https://user-images.githubusercontent.com/12616928/193356028-7a6b61fd-c452-45ed-92bf-7c81ea0bef9e.mov

Make audit planner mobile friendly and add utils for responsive design

---

client/src/components/Atoms/Steps.test.tsx
client/src/components/Atoms/Steps.tsx
client/src/components/JurisdictionAdmin/BatchInventory.test.tsx
client/src/components/JurisdictionAdmin/BatchInventory.tsx

_Review by commits_
Extract a new Steps component from the batch inventory flow. This will be useful in some upcoming auditing flows.
I also made a few tweaks to the component structure and styling to prepare for more general usage (including thinking about making it possible to add links in the step list at the top).
Tweaked styles:

Steps atom component

---

.husky/pre-commit

I noticed that the top level lint-staged command seems to run on files nested in `client` and uses the correct config from `client/package.json`, so there's no reason to also run the lint-staged command again within `client`. This might have been a result of upgrading lint-staged.

Only run lint-staged at top level in pre-commit hook

---

server/auth/lib.py
server/auth/routes.py
server/migrations/versions/244744c21027_tally_entry_accounts.py
server/models.py
server/tests/conftest.py
server/tests/helpers.py
server/tests/test_auth.py

Task: #1531
Backend API for tally entry user login for batch comparison audits.
Includes several new endpoints:
- `GET /tallyentry/<passphrase>` - The login link that a JM shares with tally entry users. This is the login entry point.
- `POST /auth/tallyentry/code` - Endpoint to for a tally entry user to request a confirmation code, submitting member names/party affiliations.
- `GET /auth/tallyentry/election/<election_id>/jurisdiction/<jurisdiction_id>` - Endpoint for a JM to check for login requests from tally entry users
- `POST /auth/tallyentry/election/<election_id>/jurisdiction/<jurisdiction_id>/confirm` - Endpoint for a JM to submit a login confirmation code for a tally entry user to log them in
As well as an update to `/api/me` to include tally entry users (most importantly, their …

Tally entry accounts (backend)

---

client/src/App.test.tsx
client/src/components/JurisdictionAdmin/BatchRoundDataEntry.test.tsx
client/src/components/JurisdictionAdmin/BatchRoundDataEntry.tsx
client/src/components/JurisdictionAdmin/RoundManagement.tsx
client/src/components/TallyEntryUser/TallyEntryLoginScreen.tsx
client/src/components/TallyEntryUser/TallyEntryScreen.test.tsx
client/src/components/TallyEntryUser/TallyEntryScreen.tsx
client/src/components/TallyEntryUser/TallyEntryUserView.test.tsx
client/src/components/TallyEntryUser/TallyEntryUserView.tsx
client/src/components/UserContext.tsx
client/src/components/_mocks.ts
server/api/batches.py
server/api/contests.py
server/auth/routes.py
server/tests/batch_comparison/conftest.py
server/tests/batch_comparison/test_batches.py
server/tests/test_auth.py

_Review by commits_
- Uses the existing `BatchRoundDataEntry` component to allow tally entry users to enter tallies. Hides the ability to copy or finalize. I didn't put a ton of effort into making this nice (from both a design perspective and a code perspective) since it will be replaced for #1623.
- Also updates the permissions on the necessary API endpoints. Since a tally entry user can edit all of the batches that a JM can edit, I just reused the same endpoints.

Tally entry users - tally entry screen

---

client/package.json
client/src/components/Atoms/FileUpload.test.tsx
client/src/components/Atoms/StatusTag.tsx
client/src/components/Atoms/Steps.tsx
client/src/components/JurisdictionAdmin/BatchRoundDataEntry.tsx
client/src/components/JurisdictionAdmin/JurisdictionAdminView.test.tsx
client/src/components/TallyEntryUser/TallyEntryLoginScreen.tsx
client/src/components/TallyEntryUser/TallyEntryScreen.test.tsx

Mostly just unused variables and a few other small things. Also added `--cache` to the eslint command to make it faster.

Fix outstanding lint warnings

---

client/src/components/Atoms/Steps.test.tsx
client/src/components/Atoms/Steps.tsx
client/src/components/JurisdictionAdmin/BatchInventory.tsx

I realized that the approach of marking one `StepListItem` with a `current` prop was brittle - if the `StepListItem` wasn't a direct child of `StepList`, there was no way to access the `current` prop in `StepList`.
Also, upon using the components more, I think they will be easier to reason about if they are purely graphical and completely controlled.

Remove all state logic from Steps component

---

client/src/App.test.tsx
client/src/components/TallyEntryUser/TallyEntryUserView.test.tsx
client/src/components/TallyEntryUser/TallyEntryUserView.tsx
server/auth/auth_routes.py
server/tests/test_auth.py

Adds an error screen for two cases:
1. The user types in their login link incorrectly
2. Someone tries to go to /tally-entry without being logged in

Tally entry login error screen

---

client/src/components/AuditAdmin/Progress/JurisdictionDetail.test.tsx
client/src/components/AuditAdmin/Progress/JurisdictionDetail.tsx
client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundSteps.test.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/DownloadBatchRetrievalListButton.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/DownloadBatchTallySheetsButton.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/PrepareBatchesStep.tsx
client/src/components/JurisdictionAdmin/generateSheets.test.tsx
client/src/components/JurisdictionAdmin/generateSheets.ts

- Add back the batch retrieval list/tally sheet buttons
- Rename the section "Current Audit Round"
- Change "Results finalized" -> "Tallies finalized"
- Add the jurisdiction name and audit name to the tally sheet file name to match the naming convention of other file downloads

Improve AA jurisdiction progress detail for batch comparison

---

client/cypress.config.ts

It takes extra time to record and compress the videos, and we very rarely need them. We can always turn it back on as needed.

Turn off video recording in Cypress tests

---

client/src/App.tsx
client/src/components/Atoms/FileUpload.test.tsx
client/src/components/AuditAdmin/AuditAdminView.test.tsx
client/src/components/AuditAdmin/Progress/JurisdictionDetail.test.tsx
client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/Contests.test.tsx.snap
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/HybridContestForm.test.tsx.snap
client/src/components/AuditAdmin/Setup/__snapshots__/Setup.test.tsx.snap
client/src/components/AuditAdmin/__snapshots__/ActivityLog.test.tsx.snap
client/src/components/AuditAdmin/timers.test.tsx
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/JurisdictionAdmin/BatchInventory.test.tsx
client/src/components/JurisdictionAdmin/BatchRoundDataEntry.test.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundSteps.test.tsx
client/src/components/JurisdictionAdmin/FullHandTallyDataEntry.test.tsx
client/src/components/JurisdictionAdmin/RoundDataEntry.test.tsx
client/src/components/JurisdictionAdmin/RoundManagement.test.tsx
client/src/components/JurisdictionAdmin/__snapshots__/FullHandTallyDataEntry.test.tsx.snap
client/src/components/JurisdictionAdmin/__snapshots__/RoundManagement.test.tsx.snap
client/src/components/PublicPages/AuditPlanner/AuditPlanner.test.tsx
client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/TallyEntryUser/TallyEntryLoginScreen.test.tsx
client/src/components/TallyEntryUser/TallyEntryScreen.test.tsx
client/src/components/TallyEntryUser/TallyEntryUserView.test.tsx
client/src/components/testUtilities.tsx

We have been using the same queryClient instance from App.tsx in all tests. This has been mostly fine, but sometimes there can be weird interactions between tests since they are using the same query cache. I started to run into problems with this (honestly surprised it didn't become an issue sooner), so decided to change to creating a new QueryClient per test case.

QueryClient test helper

---

server/tests/batch_comparison/snapshots/snap_test_sample_extra_batches_by_counting_group.py
server/tests/batch_comparison/test_sample_extra_batches_by_counting_group.py

Depending on which test case ran first, the org name in the db would be different (since it was based on the test case name). This org name shows up in the audit report snapshot, which was causing flakiness.

Fix non-deterministic test

---

client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundSteps.test.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/TallyEntryAccountsStep.tsx
client/src/components/_mocks.ts
server/auth/auth_routes.py
server/tests/test_auth.py

It can get a little annoying to have no way to clean up unused login requests. Maybe this won't be an issue in real audits, but I figured it's always nice to have a way to say no.
https://user-images.githubusercontent.com/530106/198161974-5d14ca35-18f1-4bb2-afff-32cd2373f7cb.mov

Button to reject tally entry login request

---

server/api/batches.py
server/models.py
server/tests/batch_comparison/test_batches.py

Two root causes here:
- There was no ordering defined on the `Batch.results_tally_sheet` relationship
- We were using SQLAlchemy's `contains_eager` loading helper, which uses the ordering defined in the query's existing join expression. We needed to switch to using `joinedload`, which uses the relationship definition for ordering

Ensure consistent batch tally sheet ordering

---

app.json

We were temporarily using a fork to work around a poetry deprecation: https://github.com/votingworks/arlo/pull/1579. I confirmed that the main buildpack now works using a review app.

Restore main python-poetry-buildpack

---

server/api/batch_tallies.py
server/api/sample_sizes.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/hybrid/test_hybrid.py
server/tests/util/test_strings.py
server/util/string.py

I noticed an incorrect pluralization in an error message on a file upload, so decided to fix that and look through all UserErrors and fix any other potential issues.
To do so, I added a `format_count` helper function.

Format counts correctly in server user errors

---

server/api/support.py

Will add a more comprehensive test to ensure that all routes have auth separately

Restrict access to support endpoint to permanently delete audit

---

server/audit_math/bravo.py
server/tests/audit_math/test_bravo.py

Occasionally, in our sample size probability computation, some of the internal variables can become NaN (due to the way the stats math works, if the numbers are too big/small). This makes sure that we gracefully handle that case.

Added handling for if Decimal is NaN

---

client/src/components/JurisdictionAdmin/BatchInventory.test.tsx
client/src/components/JurisdictionAdmin/BatchInventory.tsx
fixtures/tabulator-status.xml

Fixes #1668 
If a user clears and reuploads a file after signing off, we undo the sign off on the backend, since they will need to re-inventory their batches. The frontend didn't reload the sign off status when this happened, so the frontend ended up in an inconsistent state. Easy enough to fix by invalidating the query cache for sign off status.
Also added a test tabulator status file to fixtures.

Batch inventory: reload sign off status when files change

---

client/src/components/AuditAdmin/Setup/Contests/__snapshots__/Contests.test.tsx.snap
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/HybridContestForm.test.tsx.snap
client/src/components/AuditAdmin/Setup/__snapshots__/Setup.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundSteps.test.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundTallyEntry/BatchDetail.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundTallyEntry/BatchRoundTallyEntry.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/EnterTalliesStep.tsx
client/src/components/TallyEntryUser/TallyEntryScreen.tsx

Fixes #1677 
_Review by commits_
A bunch of UI polish for batch tally entry. More details in the commits.
https://user-images.githubusercontent.com/530106/200915577-46fe0f89-242d-4d55-9c60-f65bccbd8d6a.mov

Tally entry polish

---

client/src/components/Atoms/CSVForm.tsx
client/src/components/JurisdictionAdmin/JurisdictionAdminView.test.tsx
server/api/cvrs.py
server/tests/ballot_comparison/snapshots/snap_test_cvrs.py
server/tests/ballot_comparison/test_cvrs.py

Issue link: https://github.com/votingworks/arlo/issues/1446
This PR updates Hart CVR parsing to support multiple CVR ZIP files, one for each tabulator, for Orange County but also others down the road who:
- Don't have unique batch names across tabulators
- Don't have tabulator info in their XML files
- Can easily export CVRs by tabulator
As noted in a code comment:
> When multiple files are provided, we use zip file names (with ".zip" removed) as tabulator names. (These tabulator names need to match the ballot manifest, of course.)

Update Hart CVR parsing to support multiple CVR ZIP files

---

server/audit_math/bravo.py
server/tests/audit_math/test_bravo.py

Fixes #1678 
Here's the line that had the divide-by-zero error: https://github.com/votingworks/arlo/blob/015c7fba37457933de77894e74628f2cd8d4314d/server/audit_math/bravo.py#L530

BRAVO: Fix division-by-zero error

---

server/api/batch_inventory.py
server/tests/batch_comparison/snapshots/snap_test_batch_inventory.py
server/tests/batch_comparison/test_batch_inventory.py

Write-ins might be specified in the CVR as "Write-in" or "Write-in \<candidate name\>", so we aggregate those votes into one choice (as specified by the audit admin).

Batch inventory: aggregate write-ins from CVRs

---

scripts/batch-inventory-progress.py

A script to track the progress of jurisdictions moving through the batch inventory flow. Outputs a CSV to stdout.
Example output:
```
Jurisdiction,CVR File,Tabulator Status File,Signed Off
County 1,NOT_UPLOADED,NOT_UPLOADED,NO
County 2,UPLOADED,ERROR,NO
County 3,UPLOADED,UPLOADED,YES
```

Batch inventory progress script

---

server/api/ballot_manifest.py
server/tests/ballot_comparison/test_ballot_comparison_manifests.py

The CVR column is only used in hybrid audits. Providing it in other audit types causes weird behavior, since the rest of Arlo assumes it doesn't exist (specifically the sampling code).

Disallow CVR column in ballot manifest for non-hybrid audits

---

server/api/batch_inventory.py
server/tests/batch_comparison/test_batch_inventory.py

There are a few different version of the tabulator status file that are exported by the EMS. Here, we add a few checks to detect the wrong version that Arlo doesn't know how to parse (an Excel version and an HTML version).

Batch inventory: improve error messages for wrong tabulator status file type

---

server/api/batch_inventory.py
server/tests/batch_comparison/test_batch_inventory.py

Rely on built in ElementTree.parse and catch parsing errors, returning a generic error message. Also, if the parsing succeeds (i.e. it's valid XML) but we can't find the data we want, it's also the wrong file.

Batch inventory: use more generic parsing error message

---

server/auth/auth_routes.py
server/tests/test_auth.py

We store emails in the db as lowercase in order to avoid case-sensitivity issues. We missed this one query though.

Bugfix: Ignore case when looking up JA email on login

---

server/tests/util/test_csv_parse.py
server/util/csv_parse.py

Our total row detection logic is flagging a false positive in Clay County. We currently raise an error if any numeric column's last value looks like a total. After this PR, we'll only raise an error if _all_ numeric columns' last value looks like a total. Other forms of total row detection, like checking for the word "total", are still in place and unaffected by this PR.

Make total row detection more rigorous (Clay County fix)

---

client/src/components/Atoms/StatusBox.test.tsx
client/src/components/AuditAdmin/AuditAdminView.test.tsx
client/src/components/AuditAdmin/AuditAdminView.tsx
client/src/components/AuditAdmin/Setup/Review/Review.test.tsx
client/src/components/AuditAdmin/Setup/Review/Review.tsx
client/src/components/AuditAdmin/Setup/Review/_mocks.ts
client/src/components/AuditAdmin/Setup/Setup.test.tsx
client/src/components/AuditAdmin/timers.test.tsx
client/src/components/AuditAdmin/useRoundsAuditAdmin.ts
client/src/components/_mocks.ts

There were two issues going on:
1. After launching the audit, the review screen would immediately redirect to the progress screen. This redirect could occur before the rounds query updated, which would lead to a flash of the rounds screen before showing the drawing sample message.
2. When drawing the sample completed, the jurisdictions query didn't reload, meaning the progress screen wouldn't show the sampled ballots for each jurisdiction until the user refreshed.
We fix both of those issues by moving the logic for redirecting/reloading into the onSuccess callback of the rounds query.

Improve data fetching/redirect on audit launch

---

server/api/rounds.py
server/audit_math/sampler.py
server/tests/audit_math/snapshots/snap_test_sampler.py
server/tests/audit_math/test_sampler.py

Issue link: https://github.com/votingworks/arlo/issues/1525, https://github.com/votingworks/arlo/issues/1679
One of many pieces of https://github.com/votingworks/arlo/issues/1525 (improved full hand tally escalation) and https://github.com/votingworks/arlo/issues/1679 (round 2+ stuck jurisdictions), this PR cleans up the escalation pathway for batch audits (in many ways the easiest kind of audit to escalate to a full hand tally since a full hand tally is now just a batch audit with all batches).
The PR specifically makes it such that, when escalating a batch audit to a full hand tally, all batches _minus those already audited in previous rounds_ are selected (as opposed to all batches without any exclusion - what we do today).
Note that, when batches _are_ reselected across rounds, the UI …

Batch audit full hand tally escalation fixes and improvements

---

client/src/components/AuditAdmin/AuditAdminView.test.tsx
client/src/components/AuditAdmin/Setup/Review/Review.test.tsx
client/src/components/AuditAdmin/timers.test.tsx

These stopped working during the Vite upgrade so I skipped them to unblock myself.
When trying to fix them, I realized only one test actually relied on the fake clock (which is different from relying on fake timers - the logic looks at Date.now). So I moved the two other tests back into regular test files and then fixed that one test.

Fix broken timers tests

---

client/src/components/Atoms/ListAndDetail.tsx
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/Contests.test.tsx.snap
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/HybridContestForm.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundTallyEntry/BatchRoundTallyEntry.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/EnterTalliesStep.tsx

- Fix overflow handling so the list of batches scrolls, but the table of candidates sets the overall height (I noticed that before, the height of the list of batches was setting the overall height)
- Add some borders

Tweak batch tally entry styles

---

server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

The check that this PR removes seems to be unnecessary and will in fact interfere with Orange County's upcoming CVR upload, which will contain CVRs for ballots that span multiple sheets. Our current process for OC involves converting their Hart CVRs to Dominion CVRs, ignoring sheet number. The end result is a separate CVR record in the DB per sheet. The math handles this fine, recognizing that many CVR records will be not contain the targeted contests. With this change, we'll allow for the same when parsing Hart CVRs.
*By running this code in conjunction with https://github.com/votingworks/arlo/pull/1726 and making some manual tweaks to account for some CVRs not having a `BatchNumber` (which won't be the case in OC's final files)

Hart CVR parsing: Remove sheet number check

---

server/api/cvrs.py
server/util/file.py

In testing with Orange County's close-to-ready CVR files, I found myself hitting "Too many open files" errors locally. My local ulimit matches the ulimit on our prod servers (`ulimit -n` --> 1,024 * 1,024 = 1,048,576). Rather than finding a way to bump the ulimit even higher, which may not even be possible in prod (unless a higher tier of Heroku Dyno comes with a higher limit), I've modified the Hart CVR parsing code to open CVR files one at a time instead of all at once.
I also uncovered and fixed a fun bug involving a misuse of `.strip` in the process!
*By running this code in conjunction with https://github.com/votingworks/arlo/pull/1712 and making some manual tweaks to account for some CVRs not having a `BatchNumber` (which won't be the case in OC's final files)

Hart CVR parsing: Mitigate "Too many open files" errors

---

client/src/components/Atoms/StatusBox.test.tsx
client/src/components/Atoms/StatusBox.tsx

We weren't refetching the sample size response, so it could be in a loading state forever, which would cause the button to break.
Also added a guard in the button to prevent premature clicks from triggering an error.

Fix sample size loading in status box

---

client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundTallyEntry/BatchDetail.tsx

A minor piece of cleanup 🧹. The current code isn't causing any bugs but could cause confusion down the road. Also includes a rename for clarity.

Avoid stale IDs in newAndUnsavedSheetId state field

---

server/api/batch_inventory.py
server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/batch_comparison/snapshots/snap_test_batch_inventory.py
server/tests/batch_comparison/test_batch_inventory.py

Issue link: https://github.com/votingworks/arlo/issues/1736
Dominion sometimes exports CVR CSVs with equal signs in front of certain columns' values, e.g.
```
="3",="1002",="1",="10",="1002-1-10","Mail-in",...
```
We currently have customers open these CSVs in an editor like Excel and resave, which removes the leading equal signs. But this case is becoming common enough that we've decided to just handle it in code.

Handle Dominion CVR CSVs with equal signs in front of values

---

client/src/components/AuditAdmin/Setup/Contests/__snapshots__/Contests.test.tsx.snap
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/HybridContestForm.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundTallyEntry/BatchDetail.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundTallyEntry/BatchRoundTallyEntry.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/EnterTalliesStep.tsx
client/src/components/TallyEntryUser/TallyEntryScreen.tsx

While we've always known that the new batch tally entry UI isn't great when there are lots of sheets, it was previously possible to see everything that you needed to see with horizontal scroll. We've since lost that ability. This PR restores that ability, once again just focusing on basic usability and not necessarily the ideal long-term solution.
_Before this PR_
_After this PR_
https://user-images.githubusercontent.com/12616928/205988422-ada7f18e-afc6-464a-a0a6-c45ab3adf6e4.mov
_Before this PR_
_After this PR_
https://user-images.githubusercontent.com/12616928/205988424-c78b686f-5c04-46f5-bba2-d383137efa69.mov

Fix batch tally entry scroll behavior when lots of sheets

---

client/src/components/AuditAdmin/Setup/Review/Review.tsx
server/api/rounds.py
server/tests/batch_comparison/test_sample_extra_batches_by_counting_group.py

The Peach State has requested this slight modification to the extra batch selection logic that we implemented for their general audit, for their upcoming runoff audit.
We'll now not only be guaranteeing that every county has to audit at least 2 batches but also that every county has to audit at least 2% of their ballots. This shouldn't change the number of batches that small counties have to audit but will definitely increase the number of batches that large counties have to audit, creating for an even more compelling public narrative.
As part of this PR, I also tweaked the logic that determines whether or not the audit is complete since the notion of a round 2 is irrelevant for these extra batch, non-RLA audits.
From a process perspective for the runoff audit, we're going to have Georgia …

Update extra batch selection logic to select at least 2% of batches in each jurisdiction

---

client/src/components/AuditAdmin/Setup/Settings/states.ts

Related to: https://github.com/votingworks/arlo/issues/1568
This should fix a bug that was originating in `/workspaces/arlo/client/src/components/AuditAdmin/Progress/ProgressMap.tsx`. Basically, there's a string comparison looking for a matching state name and DC should be `District of Columbia`, not `District Of Columbia` with a capitalized "of".
Another option to fix this would be to change the string comparison to be case insensitive. But given that "District of Columbia" is the correct way, I figured this made more sense.

Fix dc audit

---

README.md
client/src/components/HomeScreen.tsx

Oliver raised some concerns about how we use random seeds for Providence. Until we can sort out a solution, we should disable Providence on the frontend.

Remove providence from frontend per Oliver's concerns

---

client/package.json
client/run-cypress-tests.sh
client/yarn.lock

Cypress tests were failing consistently, hanging at the start of the tests when trying to do the initial audit admin login. These changes seemed to help, though I'm not totally sure what the root cause was.

Fix Cypress tests

---

client/src/App.css
client/src/components/Atoms/StatusBox.test.tsx
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/Contests.test.tsx.snap
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/HybridContestForm.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/JurisdictionAdmin/__snapshots__/FullHandTallyDataEntry.test.tsx.snap
client/src/components/SupportTools/Breadcrumbs.tsx
client/src/components/SupportTools/List.tsx
client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/SupportTools.tsx
client/src/components/SupportTools/support-api.tsx
client/src/components/utilities.test.ts
server/api/support.py
server/tests/api/test_support.py

Fixes: #1433, #1750 
Improves navigation in Support Tools by adding:
- A list of active audits on the home screen (where an "active" audit has had some activity in the past 2 weeks)
- A "Log in" button for each jurisdiction on the audit screen
- Breadcrumb navigation for audit/jurisdiction screens
_Review by commit_
https://github.com/votingworks/arlo/assets/530106/b3933283-c57a-41f2-aef4-82faaa6cb590

Support Tools: Improved navigation

---

server/api/rounds.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison.py

We used to express when a contest wasn't on a ballot by not recording an interpretation for that contest. At some point we changed to having an explicit interpretation type, but forgot to update one piece of code
that handled this case. This function translates our interpretation into CVR format so that it can be easily compared to the actual CVR (e.g. in audit math or in reporting). The bug was that we were treating it like a
blank ballot, which is not too far off, so it likely slipped by unnoticed.

Fix bug in reporting when contest not on ballot

---

server/api/reports.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison_manifests.py
server/tests/ballot_comparison/snapshots/snap_test_contest_name_standardizations.py
server/tests/ballot_comparison/test_ballot_comparison.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/snapshots/snap_test_batches.py
server/tests/batch_comparison/snapshots/snap_test_sample_extra_batches_by_counting_group.py
server/tests/hybrid/snapshots/snap_test_hybrid.py

Instead of only showing vote deltas when there are both audited and reported votes, show any mismatch between the audited result and the reported result. This makes this column the one-stop shop for any audit discrepancy (instead of having to also look in the discrepancy column, which most users find confusing).
Also renames the "Vote Delta" to "Change in Results" and "Discrepancy" to "Change in Margin" to try to make those values a bit clearer.
_Review by commit_

Improve clarity of discrepancy columns in audit report

---

.coveragerc
server/api/batch_inventory.py
server/api/cvrs.py
server/api/full_hand_tally.py
server/api/rounds.py
server/api/sample_sizes.py
server/api/support.py
server/audit_math/ballot_polling.py
server/audit_math/macro.py
server/audit_math/raire.py
server/tests/api/test_elections.py
server/tests/ballot_comparison/test_standardized_contests.py
server/tests/batch_comparison/test_batch_inventory.py
server/tests/batch_comparison/test_support_batch_comparison.py
server/tests/test_auth.py
server/tests/util/test_csv_parse.py

We've been so close to this for a while, so it didn't take long to clean up the loose ends. My general approach was:
- Add tests for cases we care about
- Turn some error cases into assertions, since we don't actually expect those cases to happen
- Ignore code that's very hard to test or is not so important (e.g. unlikely invalid cases in the deprecated full hand tally flow)

100% coverage for server

---

client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/AuditAdmin/Progress/Progress.tsx
client/src/components/_mocks.ts
client/src/components/useJurisdictions.ts
server/api/discrepancies.py
server/api/jurisdictions.py
server/api/reports.py
server/api/rounds.py
server/audit_math/macro.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/snapshots/snap_test_batches.py
server/tests/batch_comparison/test_batch_comparison.py

Task: #1813 
_Review by commit_
Adds a Discrepancies column to the audit admin Audit Progress screen for ballot comparison and batch comparison audits. This column shows a count of the number of discrepancies in the audit results after a jurisdiction finalizes their results. It's based on the same data that goes in the "Change in Results" audit report column (aka vote deltas) rather than the "Change in Margins" column (which is the internal audit math discrepancy value) since that data has been designed to flag any discrepancy between audit results and reported results, rather than just the ones that will impact the outcome of the statistical audit.
Next PR will include access to a discrepancy report.
To ensure this change will not slow down the jurisdictions endpoint (which is already …

Discrepancy indicators

---

client/src/components/Atoms/Table.tsx
client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/AuditAdmin/Progress/Progress.tsx
client/src/components/useSearchParams.ts

Closes #1513 
In order to allow audit admins to track a specific jurisdiction or a few jurisdictions over time, save the filter/sort state of the audit progress table in the URL. This will allow the user to refresh the page for updates (or even bookmark/share it) while keeping the focus on the desired jurisdictions.
https://github.com/votingworks/arlo/assets/530106/cf977281-0726-4ad2-9804-ab72df361388

Audit progress: Persist filter/sort in URL

---

Makefile
app.json

Heroku builds recently started failing. On the left is a successful build, and on the right is a failed build:
Recent updates to the [python-poetry-buildpack](https://github.com/moneymeets/python-poetry-buildpack) seem to be responsible. Simplest fix for now is to lock to a specific version of the buildpack [by specifying a commit hash](https://devcenter.heroku.com/articles/buildpacks#buildpack-references). Others have also used this technique to bypass issues with the buildpack, [as noted in this comment](https://github.com/moneymeets/python-poetry-buildpack/issues/67#issuecomment-1810362297). Through trial-and-error, I've found the latest commit that still works for us.
Note that I'm not sure how the `app.json` file and Heroku console interact. It's possible that, even after merging …

Fix Heroku builds by locking python-poetry-buildpack version

---

client/yarn.lock

Frontend tests are failing when run locally (CI is fine):
<table>
</table>
I've traced the error to a bug in a transitive dependency (`graceful-fs`): https://github.com/isaacs/node-graceful-fs/issues/224.
Upgrading `graceful-fs` solved the problem. I performed the update by erasing the entries for `graceful-fs`  in the `yarn.lock` and re-running `yarn install`.

Fix locally-run frontend tests (CI is fine)

---

client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/AuditAdmin/Progress/Progress.tsx

Issue link: https://github.com/votingworks/arlo/issues/1849
This one proved to be even easier than increasing batch audit sample size by 1 :smile:
_Before_
No distinction between more or fewer ballots than expected; confusing total `Difference From Expected Ballots`
<table>
</table>
_After_
Distinction between more or fewer ballots than expected; no total `Difference From Expected Ballots`
<table>
</table>

Use negative numbers when num ballots in manifest fewer than expected

---

server/api/rounds.py
server/api/shared.py
server/migrations/versions/c012fa6b13a9_sampledbatchdraw_contest_id.py
server/models.py

This PR adds contest ID to the `SampledBatchDraw` model in preparation for multi-contest batch comparison audits. This should be the only data model update necessary.
Ran the migration locally on the latest prod data and verified that it worked as expected.

Add contest ID to SampledBatchDraw model

---

client/src/components/AuditAdmin/Setup/Contests/__snapshots__/Contests.test.tsx.snap
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/HybridContestForm.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundSteps.test.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundTallyEntry/BatchDetail.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundTallyEntry/BatchRoundTallyEntry.test.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundTallyEntry/BatchRoundTallyEntry.tsx
client/src/components/_mocks.ts

This PR updates the batch tally entry UI to support multiple contests. Note that the batch audit creation UI still doesn't support creating audits with multiple contests.
_Two contests_
<table>
</table>
_One contest_
I chose to keep the contest header even when there's only one contest, for consistency.
<table>
</table>

Update batch tally entry UI to support multiple contests

---

server/feature_flags.py

Ginny pointed out that we don't want this feature enabled for Georgia's upcoming audits.

Disable extra batch selection for Georgia, for now

---

server/api/rounds.py
server/tests/api/test_rounds.py
server/tests/ballot_polling/test_ballot_polling.py

Previously, if you tried to finish a round that was already finished, you would get a database integrity error. No harm caused, but not the nicest UX (and causes an unnecessary alert). Instead, add a guard and a nice error message.
Note that it's not totally clear how you would do this in the UI, but potentially possible if you had two tabs open with the same audit and clicked the "Finish Round" button in each one in succession.

Guard against finishing a round multiple times

---

server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

We've received a few Dominion CVR files from Nevada containing percent values, which interfere with integer parsing:
```
invalid literal for int() with base 10: '0 (0%)'
```
This PR improves the user-facing error message (currently the opaque catch-all "Could not parse CVR file"). And in doing so also no longer has this error trigger PagerDuty.
<table><tr><td>
</td></tr></table>

Improve error message for Dominion CVR files with percent values

---

server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

Welp, as soon as we rolled out https://github.com/votingworks/arlo/pull/1885, we encountered a Dominion CVR file with a value that couldn't be parsed but that also didn't contain a percent:
```
invalid literal for int() with base 10: '0 (0)'
```
I'm changing course and now catching all failures to parse Dominion interpretation values as integers:
<table><tr><td>
</td></tr></table>
<table><tr><td>
</td></tr></table>

Catch all failures to parse Dominion interpretation values as integers

---

server/api/batch_inventory.py
server/api/batch_tallies.py
server/api/batches.py
server/api/contests.py
server/api/jurisdictions.py
server/api/reports.py
server/api/rounds.py
server/api/sample_sizes.py
server/api/shared.py
server/tests/batch_comparison/conftest.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/snapshots/snap_test_batches.py
server/tests/batch_comparison/snapshots/snap_test_multi_contest_batch_comparison.py
server/tests/batch_comparison/snapshots/snap_test_sample_extra_batches_by_counting_group.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/batch_comparison/test_batch_tallies.py
server/tests/batch_comparison/test_batches.py
server/tests/batch_comparison/test_multi_contest_batch_comparison.py
server/tests/helpers.py

This PR updates the Arlo backend to support multi-contest batch audits. Note that the batch audit creation UI still doesn't support creating audits with multiple contests.
We're keeping things simple for now and avoiding any updates to the audit math. Jurisdiction admins will still upload a single candidate-totals-by-batch file, where that file includes counts for candidates across all contests (in that jurisdiction). Sample sizes will be calculated and sample batches will be drawn for each contest independently. Even if a batch is selected for only one contest, batch results will be collected for all contests. While we'll display discrepancies for all collected data, only the batches that were actually selected by the audit math …

Update backend to support multi-contest batch audits

---

client/src/components/AuditAdmin/Setup/Contests/ContestForm.tsx
client/src/components/AuditAdmin/Setup/Contests/Contests.test.tsx
client/src/components/AuditAdmin/Setup/Contests/_mocks.ts
client/src/components/AuditAdmin/Setup/Review/Review.tsx
client/src/components/_mocks.ts

This PR updates the batch audit creation UI to support creating audits with multiple contests, now that the backend is ready. We're using the exact same UI as the other audit types.
<table>
</table>

Update batch audit creation UI to support creating audits with multiple contests

---

client/src/components/Atoms/CSVForm.tsx
client/src/components/Atoms/FileUpload.tsx
client/src/components/AuditAdmin/Progress/JurisdictionDetail.test.tsx
client/src/components/AuditAdmin/Progress/JurisdictionDetail.tsx
client/src/components/AuditAdmin/__snapshots__/AuditAdminView.test.tsx.snap
client/src/components/JurisdictionAdmin/JurisdictionAdminView.test.tsx
client/src/components/JurisdictionAdmin/JurisdictionAdminView.tsx
client/src/components/JurisdictionAdmin/candidateTotalsByBatchTemplates.ts
server/api/batch_tallies.py
server/tests/batch_comparison/test_batch_tallies.py
server/tests/batch_comparison/test_multi_contest_batch_comparison.py

Issue link: https://github.com/votingworks/arlo/issues/1856
This PR updates Arlo to provide template candidate-totals-by-batch files. These files are often incorrectly formatted when prepared from scratch, so these templates should reduce user error rates. The templates are audit-specific and jurisdiction-specific. Users should not have to update column names.
I've added buttons to the audit admin and jurisdiction admin UIs.
Notice the new "Download Template" button.
| Before upload | After upload |
| -- | -- |
| <img width="1512" alt="aa-before-upload" src="https://github.com/votingworks/arlo/assets/12616928/88e1f552-6bcd-43bd-be16-8e6c33b4fdb2"> | <img width="1512" alt="aa-after-upload" src="https://github.com/votingworks/arlo/assets/12616928/9a8e8c9d-5833-4a4a-aea1-0aa20fbbd854"> |
_In …

Provide template candidate-totals-by-batch files for batch audits

---

server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

We've been seeing the database query to delete CVR ballot records be slow in production sometimes. While we're getting to the bottom of it, this change ensures that the query is only run in the `process_cvr_file` background task. It's not as safe as our previous approach of deleting the records on file delete, but should be an ok temporary fix.

Clear old CVR ballots from database in background during CVR file upload

---

arlo.code-workspace
server/api/ballot_manifest.py
server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

In order to safely delete CvrBallot records, ensure the db query is
always run in a background task. We can't rely on the query planner to
consistently use the appropriate indices for this query, so this is a
safe option to ensure we don't timeout any requests.

Move cvr ballot deletion to background task

---

arlo.code-workspace
client/src/components/AuditAdmin/Progress/JurisdictionDetail.test.tsx
client/src/components/AuditAdmin/Progress/JurisdictionDetail.tsx
client/src/components/AuditAdmin/Progress/Progress.tsx
client/src/components/JurisdictionAdmin/JurisdictionAdminView.test.tsx
client/src/components/JurisdictionAdmin/JurisdictionAdminView.tsx
client/src/components/JurisdictionAdmin/candidateTotalsByBatchTemplateCsv.ts
server/api/batch_inventory.py
server/api/batch_tallies.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/batch_comparison/test_batch_tallies.py
server/tests/batch_comparison/test_multi_contest_batch_comparison.py

Issue link: https://github.com/votingworks/arlo/issues/1867
During previous batch audits, our audit specialists have manually downloaded every jurisdiction's candidate-totals-by-batch file, summed the numbers across batches, and prepared [a summary file to compare against state-published results](https://docs.google.com/spreadsheets/d/1g8X2-HGZ12rZ_orW1Jo82AoOqYsaw2pC9t8Bo0aAOcE/edit?usp=sharing). A very cumbersome task 😅.
This PR builds the generation of this summary file into the product.
_Before audit launch_
_After audit launch_
_Sample CSV before all jurisdiction files have been uploaded_
```
Jurisdiction,Contest 1 - Choice 1,Contest 1 - Choice 2,Contest 2 - Choice 3,Contest 2 - Choice 4,Total Ballots
J1,0,0,99,1,100
J2,40,10,,,50
J3,,,,,
Total,40,10,99,1,150
```
_Sample CSV after …

Add button to audit admin UI for downloading reported results summed by jurisdiction as CSV

---

client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundTallyEntry/BatchDetail.tsx
client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundTallyEntry/BatchRoundTallyEntry.test.tsx

@jonah noticed during Show and Tell that we're auto-focusing the wrong input in the batch tally entry UI when there are multiple contests. This PR corrects that. ✅
_Before_
https://github.com/votingworks/arlo/assets/12616928/9df9f5ba-9d5d-4426-87dc-b4e91b444246
_After_
https://github.com/votingworks/arlo/assets/12616928/c5b4da3f-d23d-45f2-a82d-a18087e3cf4d

Fix batch tally entry auto-focus bug when there are multiple contests

---

server/api/ballot_manifest.py
server/api/batch_tallies.py
server/api/contests.py
server/tests/batch_comparison/test_multi_contest_batch_comparison.py

In testing multi-contest batch audits, I found an issue able to affect not only multi-contest batch audits but also single-contest batch audits - the fact that we don't reprocess uploaded candidate-totals-by-batch files when contests are edited. The number of things that can go wrong because of this has just grown with multi-contest batch audits.
For example, adding a contest after uploading candidate-totals-by-batch files can render those files incomplete and actually crash Arlo the next time Arlo fetches jurisdictions:
```
INFO:werkzeug:127.0.0.1 - - [06/Mar/2024 17:57:53] "GET /api/election/c8472cc3-e746-4285-ad41-b7abd2b7a760/jurisdiction HTTP/1.1" 500 -
Traceback (most recent call last):
File "/home/arsalan/.cache/pypoetry/virtualenvs/arlo-Lrf6nvlW-py3.8/lib/python3.8/site-packages/se …
```

Reprocess candidate-totals-by-batch files when contests are edited

---

client/src/components/AuditAdmin/AuditAdminView.test.tsx
client/src/components/AuditAdmin/useRoundsAuditAdmin.ts
server/api/jurisdictions.py
server/api/shared.py

Small optimizations to the /jurisdictions endpoint to reduce the risk of multiple slow db queries causing a request timeout. Details in commits.
Since I wasn't able to reproduce hypothetical conditions where a request timeout would occur (when the db decided to do a seq scan for the query to count CVR ballots), I can't confirm that this solves the issue.
Planning a follow up PR to move discrepancy calculation to a separate endpoint because the slow query to load sampled ballots is currently blocking the entire page load, which is a pretty bad UX.

Optimize /jurisdictions endpoint to lower risk of timeouts

---

client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/AuditAdmin/Progress/Progress.tsx
client/src/components/_mocks.ts
client/src/components/useJurisdictions.ts
server/api/jurisdictions.py
server/tests/api/test_jurisdictions.py
server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
server/tests/ballot_comparison/test_ballot_comparison.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/batch_comparison/test_multi_contest_batch_comparison.py

Previously, discrepancy counts were included in jurisdiction round status. This can be a slow calculation, since we need to load all the sampled ballot interpretations. Since the jurisdictions endpoint blocks page load, it's not great to have a slow calculation as part of that endpoint. Instead, we load the discrepancy counts separately and show a spinner while they are loading.
https://github.com/votingworks/arlo/assets/530106/d4256457-2774-426d-a0ee-027d670b1f10

Fetch jurisdictions discrepancy counts from separate endpoint

---

client/src/components/AuditAdmin/ActivityLog.tsx
server/activity_log/slack_worker.py
server/api/batch_inventory.py

This PR adds activity logs for batch inventory file uploads. These logs will get outputted to the #arlo-activity Slack channel. This should make proactively debugging batch inventory file upload issues easier for our support specialists. Right now, we're having to log in as individual jurisdictions to check for errors.

Add activity logs for batch inventory file uploads

---

.coveragerc
client/jest.config.js
client/src/components/JurisdictionAdmin/BatchInventory.test.tsx
client/src/components/JurisdictionAdmin/BatchInventory.tsx
client/src/components/JurisdictionAdmin/JurisdictionAdminView.test.tsx
client/src/components/JurisdictionAdmin/JurisdictionAdminView.tsx
client/src/components/useFeatureFlag.ts
server/api/batch_inventory.py
server/api/cvrs.py
server/migrations/versions/cb8de251c1a5_batchinventorydata_system_type.py
server/models.py
server/tests/api/test_ballot_manifest.py
server/tests/api/test_jurisdictions_file.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/ballot_comparison/test_standardized_contests.py
server/tests/batch_comparison/test_batch_inventory.py
server/tests/batch_comparison/test_batch_tallies.py
server/tests/util/test_csv_parse.py
server/util/csv_parse.py

Issue link: https://github.com/votingworks/arlo/issues/1866
Jurisdictions often struggle to prepare their files for batch audits. We've built a "batch inventory" tool for Georgia that helps them prepare these files from their CVR files, while also still making sure that they still physically inventory their ballots (though part of audit setup, an audit of its own, in a way).
For Pennsylvania and Rhode Island's upcoming audits, we want to try a permutation of the above model. We're going to have PA and RI jurisdictions upload their CVR files and auto-generate one of the two batch audit files, the candidate-totals-by-batch file. We'll still have them prepare ballot manifests manually.
Also of note is that PA and RI use ES&S (GA uses Dominion). So I've added a screen to the batch inventory …

Update batch inventory tool to support generating candidate-totals-by-batch files from PA and RI ES&S CVR files

---

client/src/components/useFeatureFlag.ts

@ginvdr asked that we hide the batch inventory UI in the PA org for now since they're not quite ready to use the feature without our assistance. Some jurisdictions may also have ES&S file versions that we can't yet parse. We can either enable the feature for PA next week once we're actively supporting them or create a clone of their audit in one of our sandboxes to help them prepare files.

Hide batch inventory UI in PA org for now

---

server/api/batch_inventory.py
server/api/cvrs.py
server/tests/ballot_comparison/snapshots/snap_test_cvrs.py
server/tests/ballot_comparison/test_cvrs.py

Issue link: https://github.com/votingworks/arlo/issues/1905
This PR updates a mistaken assumption in our ES&S CVR parsing logic re type-1 and type-2 ES&S CVR ballots files.
Our previous understanding of ES&S CVR ballots files was as follows:
| Type | Has metadata rows? | Has Machine column? |
| -- | -- | -- |
| 1 | Yes | No |
| 2 | No | Yes |
Turns out, whether an ES&S CVR ballots file has metadata rows is independent of whether it has a Machine column. This PR removes the assumption that these two facets are paired and allows for all possibilities, removing the idea of type-1 and type-2 files from the parsing logic, and instead always checking for metadata rows and always checking for a Machine column.
We discovered this issue in our parsing logic during a previous Nevada ballot …

Update mistaken assumption re type-1 and type-2 ES&S CVR ballots files

---

client/jest.config.js
client/src/components/AuditAdmin/AuditAdminView.test.tsx
client/src/components/AuditAdmin/Setup/Participants/Participants.tsx
client/src/components/AuditAdmin/Setup/Review/CvrChoiceNameConsistencyError.tsx
client/src/components/AuditAdmin/Setup/Review/Review.test.tsx
client/src/components/AuditAdmin/Setup/Review/Review.tsx
client/src/components/AuditAdmin/Setup/Review/StandardizeContestChoiceNamesDialog.tsx
client/src/components/AuditAdmin/Setup/Review/StandardizeContestNames.tsx
client/src/components/AuditAdmin/Setup/Setup.test.tsx
client/src/components/AuditAdmin/__snapshots__/AuditAdminView.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/_mocks.ts
client/src/components/useContestChoiceNameStandardizations.ts
client/src/components/useContestNameStandardizations.ts
client/src/components/useContests.ts
client/src/components/useFileUpload.ts
client/src/components/useStandardizedContests.ts
server/api/contests.py
server/api/cvrs.py
server/api/standardized_contests.py
server/migrations/versions/8452f909a07e_jurisdiction_contest_choice_name_standardizations.py
server/models.py

Issue link: https://github.com/votingworks/arlo/issues/1917
This PR implements a contest choice name standardization flow that mirrors our existing contest name standardization flow!
We long ago made the assumption that, though contest names can vary across jurisdictions, choice names would not. That assumption has since been proven wrong, notably in Nevada and Washington. The new flow allows you to add choice names to your standardized contests file and map CVR choice names to those standardized choice names.
The new "Choice Names" column in the standardized contests file isn't required. If you don't include it, we'll still try to detect and warn you when contest choice names are inconsistent across jurisdictions, per existing logic. Main change to that existing warning is that it'll now …

Implement contest choice name standardization flow

---

client/src/components/useFeatureFlag.ts

We'd like to enable the batch inventory UI for Nevada and Washington, for when their ballot comparison audits require a full hand tally and we need to quickly set up a batch audit for that purpose.
Still getting confirmation on whether we should auto-generate the ballot manifest (and not just the candidate totals by batch file). Will merge once I get that confirmation.

Enable batch inventory for Nevada and Washington

---

server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

ES&S CVRs consist of one CVR file and one or more ballots files. The CVR file contains the actual votes, and the ballots files contain additional useful identifiers.
We use some simple checks to distinguish the CVR file from the ballots files in the upload. But lately, one such check has been misidentifying some CVR files as ballots files. Specifically the check that - if a file has a "Tabulator CVR" column, it's a ballots file. Some jurisdiction's CVR files now include this "Tabulator CVR" column.
Long-term, this actually means that we may not need ballots files from some ES&S jurisdictions. Though even for these jurisdictions that have a "Tabulator CVR" column in their CVR files, we may still sometimes need ballots files. I won't get into the weeds of that right now, but a nice …

ES&S CVR parsing: Allow "hinting" which file is the CVR file by changing the file name

---

client/jest.config.js
client/src/components/AuditAdmin/Setup/Review/StandardizeContestChoiceNamesDialog.tsx

This fallback is covering the case that a contest is only in some jurisdictions and not all. We have this same check [elsewhere](https://github.com/votingworks/arlo/blob/fdefe6ce30c497c264d872ed1b60ad488c121644/client/src/components/AuditAdmin/Setup/Review/StandardizeContestChoiceNamesDialog.tsx#L120) but missed it here.
We should definitely add a test for contest choice name standardizations when a contest is selected that is only in some jurisdictions, but I'm just patching this quickly to unblock WA's audit.
Took a DB snapshot to repro WA's audit's review page crashing (white screen) and verified that this fix works

Add missing fallback for case that contest is only in some jurisdictions

---

server/api/cvrs.py

Previously, we expected exactly 3 metadata columns. When given a file with more metadata columns, they were treated like contest columns. This caused a bloating of the contest metadata and major performance slowdown.
Manually tested this hotfix, will add regression test separately.

Hotfix: Expect more possible metadata columns when parsing ES&S CVRs

---

client/src/components/AuditAdmin/Setup/Review/Review.tsx

We currently render a modal for each contest that may require choice name standardization. These modals are all controlled by a single boolean flag. That means that showing any one modal will show all of them, which is not what we want to happen.
To fix this, I replaced the boolean flag with a contest ID for the modal to show.
Manually tested that this fixes the issue, and also confirmed that form state resets when closing/reopening the modal.

Review screen: Show only one modal for choice name standardization

---

server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py

We saw a ballots file uploaded with empty rows at the end, which caused an error when trying to access the "Cast Vote Record" column to sort on. Since empty rows are easy to filter out, I added logic to do that. I also changed the sorting code to use `column_value`, which checks for missing values and raises a user-facing error if missing as a backup.

Filter out empty rows and protect against missing values in ES&S CVR parsing

---

server/worker/tasks.py

In production (but not dev), it looks like the root log level gets changed somewhere before the worker logger is created, so worker logs were not showing up in Heroku. We explicitly force the log level back to info to fix it.

Ensure logger in worker uses info level

---

server/activity_log/slack_worker.py
server/tests/snapshots/snap_test_slack_worker.py

Fix jurisdiction link in Slack activity log message

---

server/worker/tasks.py

The previous approach (#1958) of modifying the root logger level only worked temporarily. It still got changed back. I don't understand why, but setting the log level on the logger itself is a more resilient fix, since it doesn't need to inherit the root logger level anymore.

Set worker logger level to info explicitly

---

server/api/cvrs.py
server/tests/ballot_comparison/snapshots/snap_test_cvrs.py
server/tests/ballot_comparison/test_cvrs.py

We added a hotfix in #1954 to allow different sets of metadata columsn in the CVR file. However, we still may see unknown columns we haven't seen before. Since there's no good way to differentiate those columsn from contest columns, our current approach may silently fail in that case. The consequence would be that metadata columns are treated as contests. This may or may not cause downstream issues.
To reduce the likelihood of that happening, we change our method of searching for the dividing line between metadata columns and contest columns to look for the _last_ known metadata header. That way, we'll get it right in every case except the case where the dividing line is a header we haven't seen before, which is much less likely to occur.

ES&S CVR parsing: Protect against unknown columns in CVR file

---

server/app.py

We're going to have to test this in staging, as many details depend on TLS.

make session cookie secure, so it's only sent over https.

---

server/api/reports.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/snapshots/snap_test_batches.py
server/tests/batch_comparison/snapshots/snap_test_multi_contest_batch_comparison.py
server/tests/batch_comparison/snapshots/snap_test_sample_extra_batches_by_counting_group.py

Where there are "extra" batches included we want to ignore those in the summary round-level data. This change updates the logic introduced in https://github.com/votingworks/arlo/pull/1988 to filter out "extra" batches when computing those fields. 
It also adds a "totals" row to the end of the batches section to still capture the information with the extra batches included. This row just computes totals for number of ballots, audited results, and reported results. Note that if there are multiple rounds occurring in the audit the totals will the be total of the batches from all rounds combined. This can be seen in some of the snapshot test updates.

Update batch comparison audit reports to better handle extra batches

---

Makefile
package.json

You have to run `husky install` for the git pre-commit hook to work. Following their docs, I added a `prepare` script to package.json. To make sure that script runs when setting up a new dev env, I also added it to the Makefile.

Ensure git hooks are setup

---

poetry.lock

This PR runs `poetry lock` to update server dependencies according to our existing semantic versioning for deps as listed in `pyproject.toml`. Discussion [here](https://votingworks.slack.com/archives/CKCVA0F9S/p1729187464644569).
Testing: Went through a batch comparison audit to test the normal flow.

Run poetry lock

---

.circleci/config.yml

Seeing issues with `main` branch failing after upgrading dependencies. Thinking that is a caching issue, so before downgrading `sentry-sdk` in [this PR ](https://github.com/votingworks/arlo/pull/2001), will attempt to fix it using this approach.

Bump cache version

---

.circleci/config.yml

Follow up to https://github.com/votingworks/arlo/pull/2002 which didn't fix the issue. Maybe since we are caching all of ~./cache, that is also caching the poetry deps even though that ideally should be separated out.

Bump cache-version

---

Makefile

We've now seen multiple cases where installing `gcc` and `python-dev` allow for the `psycog2-binary` to properly build, so it seems worth adding to our `deps` command.
To test, I created a fresh VM and was able to run `make deps` successfully without any additional commands, while previously I would run into the `psycog2-binary` issue on each VM I created.
As a follow up task, I'm thinking the `Makefile` might benefit from a bit of a reorganization, but will limit this PR to this change since it is impeding some people's setup.

Add dependencies that are required to build psycog2-binary on some VMs

---

server/tests/ballot_comparison/snapshots/snap_test_cvrs.py

I don't know why the first update in https://github.com/votingworks/arlo/pull/1999 didn't catch all of them.

Update test_cvrs snapshots again

---

.circleci/config.yml

Previously, we were caching Cypress by including all of `~/.cache` in the node cache, which only updates when `client/yarn.lock` changes. We hypothesize that since `~/.cache` also included cached Python dependencies, changes to the Python dependencies would be overriden by this cache. To fix this, we cache Cypress separately and restore the original behavior of the node cache (only caching node deps).
To be safe, I updated the cache version for all the existing caches.

CircleCI: Cache Cypress separately

---

server/tests/test_auth.py

The current test only allowed one second until the code expired and could be regenerated. It was being flaky and sometimes returning a new code when we attempted to check that you couldn't generate a new code inside that window. We need a little bit longer window to make that check safely.

Fix flaky auth code expiration test

---

server/api/sample_sizes.py
server/audit_math/macro.py
server/audit_math/sampler.py
server/tests/audit_math/test_macro.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/snapshots/snap_test_multi_contest_batch_comparison.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/batch_comparison/test_multi_contest_batch_comparison.py

Primarily this addresses #1857. Sample size calculations after round 1 should take the cumulative measured risk (p-value) into account; U does not change. 
Secondarily, compute_risk was set to terminate as soon as the risk limit was reached. That's valid, but tends to produce inflated p-values in many use cases. In discussion with @ginvdr we agreed that a good conservative approach is to use all the data from the RLA sample for the contest. (In principle it is legitimate to use the sequential minimum, which might be less if a batch late in the sample sequence has large discrepancies -- but that seems too clever.)

Improve batch computations

---

client/jest.config.js
client/package.json
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/Contests.test.tsx.snap
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/HybridContestForm.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/JurisdictionAdmin/__snapshots__/FullHandTallyDataEntry.test.tsx.snap
client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/SupportTools.tsx
client/src/components/SupportTools/support-api.tsx
client/yarn.lock
server/api/batches.py
server/api/jurisdictions.py
server/api/reports.py
server/api/rounds.py
server/api/sample_sizes.py
server/api/shared.py
server/api/support.py
server/audit_math/macro.py
server/migrations/versions/34824a2d1ba8_batch_combined_batch_name.py
server/models.py
server/tests/audit_math/test_macro.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/batch_comparison/test_support_batch_comparison.py

Closes: https://github.com/votingworks/arlo/issues/1932
In batch comparison audits, sometimes auditors discover after launching the audit the some of the sampled batches have been physically commingled such that it's impossible to know which ballots belonged to which batch. This PR adds the ability for Support Users to combine batches after the audit has started to mitigate this issue. A combined batch may consist of both sampled and unsampled batches.
Combined batches will then appear to auditors like any other batch, and the original batches that were combined will be hidden. The audit math is updated to conservatively incorporate these combined batches into the risk measurement calculation. Finally, the discrepancy report and audit reports are updated to include the combined batch …

Combine commingled batches during audit

---

server/migrations/versions/6c256e8152f8_backgroundtask_worker_id.py
server/models.py
server/tests/test_background_tasks.py
server/tests/test_websessions.py
server/websession.py
server/worker/tasks.py
server/worker/worker.py

Task: #1934 
Updates the background worker so that multiple workers can safely run concurrently. Attempts to ensure that:
- Every job is run exactly once
- If a worker is available, it will immediately start on the next job in the queue
- If a worker is terminated (e.g. by a [Heroku dyno shutdown](https://devcenter.heroku.com/articles/dyno-shutdown-behavior)), any in-progress job will be re-enqueued
Note that there is no logical locking of jobs to prevent conflicts when trying to access the same resources, but we'll need to add that as an additional layer on top of this (since it will require domain-specific logic). Will tackle this in a follow up PR.
For testing, I added some automated testing to simulate multiple concurrent workers competing for jobs. I also created a Heroku review app …

Concurrent background workers

---

server/tests/test_background_tasks.py
server/worker/tasks.py

Bugfix for #1990 
Previously, when a task got interrupted, we let the process die immediately, which would rollback the transaction automatically.
Now, we try to reset the task, which involves clearing the task started_at timestamp and then commiting the current transaction to save that change to the db. So in order to ensure that any in-progress changes from the task itself are not committed alongside those changes, we need to rollback the current transaction and start a new one.
I updated the tests for task resetting to cover this behavior, which they previously didn't cover because they didn't use the db.

Rollback db transaction when background task is interrupted

---

server/api/shared.py
server/tests/batch_comparison/test_sample_extra_batches_by_counting_group.py

Previously, we were choosing extra batches from a nondeterministically ordered set of batch ids. Instead, we use batch keys (instead of db ids, which are random) and sort them before choosing batches.

Make extra batch sampling deterministic by using sortable batch keys

---

server/api/ballot_manifest.py
server/tests/api/test_ballot_manifest.py

Returns a more specific error message when a Batch Inventory Worksheet is uploaded instead of ballot manifest.
Note that because CSV validation currently happens in upload before `process()`, it's easiest to trigger a toast notification rather than permanent job error under the upload field.
https://github.com/user-attachments/assets/2af2afea-46f7-43ef-994e-4f4d6eea2d6f

validate Batch Inventory Worksheet uploaded to ballot manifest

---

server/api/jurisdictions.py
server/tests/api/test_jurisdictions.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/batch_comparison/test_multi_contest_batch_comparison.py

This PR adds a server endpoint for getting discrepancies, and for now only adds the implementation for batch comparison audits.
Next, I plan to wire together the rest of the flow to the client, and then add implementation for ballot comparison audits. My plan is to build a bit more incrementally, so the PR doesn't become too much for me to reason about as I go.
For now, thought it might be helpful to agree upon the API and models I set up, of course subject to some minor changes if needed when the rest of the feature is built out.
Sample response received by the Client from this endpoint -

Server endpoint for surfacing discrepancies

---

client/cypress/end-to-end/ballot-comparison.cy.js
client/cypress/end-to-end/ballot-polling.cy.js
client/src/components/AuditAdmin/Setup/Settings/Settings.test.tsx
client/src/components/AuditAdmin/Setup/Settings/Settings.tsx

Closes #1777 
Adds a presentation mode for inputting the random seed. To begin an audit, state officials often have a ceremony where they publicly roll dice to generate the random seed and then type it into Arlo. They like to project Arlo onto a screen during this ceremony. This PR adds a presentation mode for the random seed input to be used during this ceremony.
https://github.com/user-attachments/assets/635e0c5a-0384-4737-b7a3-89cdf3cc50e4

Presentation mode for random seed input

---

server/api/ballot_manifest.py
server/api/batch_inventory.py
server/api/batch_tallies.py
server/api/cvrs.py
server/migrations/versions/4aec6c8a419f_backgroundtask_lock_key.py
server/models.py
server/tests/test_background_tasks.py
server/worker/tasks.py

Task: #1934 
Many background tasks modify audit data in the database that is relied on by other background tasks. We don't want to allow background tasks that touch the same data to run concurrently, as this may result in inconsistent behavior due to race conditions.
The simplest guard to prevent that is to ensure that only one background task per audit runs at a time. Background tasks don't ever modify data across multiple audits, so this is a safe level of granularity. We'll still get the benefit of having multiple concurrent workers when there are multiple audits running at the same time.

Only allow one background task per audit to run at a time

---

client/src/components/AuditAdmin/Progress/JurisdictionDiscrepancies.tsx
client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/AuditAdmin/Progress/Progress.tsx
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/_mocks.ts
client/src/components/useJurisdictions.ts

Commit by commit review will probably be easiest
This PR adds the ability to see batch comparison audit discrepancies in the UI from [this issue](https://github.com/votingworks/arlo/issues/1912).
https://github.com/user-attachments/assets/faf2b240-0a5f-41fe-b0b0-946d4c3fa58e
Follow ups:
- Add support for ballot comparison
- Add support for combined batches

Batch comparison discrepancies in UI batch comparison

---

client/cypress/end-to-end/ballot-polling.cy.js

I wasn't able to figure out from looking at the saved artifacts why the failure was happening beyond that this button was detached from the DOM when we try to click on it, but hoping this fixes it.

Attempt to fix flaky Cypress test

---

client/src/components/JurisdictionAdmin/BatchInventory.tsx
server/api/batch_inventory.py
server/api/cvrs.py
server/tests/batch_comparison/snapshots/snap_test_batch_inventory.py
server/tests/batch_comparison/test_batch_inventory.py
server/tests/helpers.py
server/tests/util/test_hart_parse.py
server/util/file.py
server/util/hart_parse.py

https://github.com/votingworks/arlo/issues/1865
Adds basic support for hart cvr uploads in the batch inventory tool. Extracts BatchNumber, when provided, from Hart CVRs to use to group batches, and falls back to the precinct (split) name. The hart documentation suggests that BatchNumber is only provided on central system drives, and in sample hart cvr files we have there are some without BatchNumbers. If the CVRs with a missing BatchNumber are precinct cvrs then grouping by precinct is a logical fallback. We may want to tweak this implementation as we have real use cases for it and understand the data better.

Support hart cvr files in batch inventory tool

---

server/api/batch_inventory.py
server/api/cvrs.py
server/tests/util/test_file_storage.py
server/util/file.py

Instead of downloading the entire file into memory this change streams it to a file in the temp working directory (already cleaned up at the end of processing) for processing. There is more work to do to make sure we never load everything in memory but this is a good easy win and first step. 
Testing on a dominion CVR that is 1.6 GB is size on main I found that the python process for the worker grows to ~1.7gb in memory usage as the file is downloaded and remains at that level for the length of processing before dropping back to its stable state of 200-300mb. After this change the same file shows that process holding steady with about 300mb of memory usage throughout the length of processing. Verified the tmp file is cleaned up at the end. 
Testing on a hart cvr zip of 1.4gb in prod it …

Stream file downloaded from s3 to temporary file for processing

---

client/src/components/AuditAdmin/Progress/Progress.tsx

This PR follows up [this](https://github.com/votingworks/arlo/pull/2033) to add the icon that was removed from the download button. @jonahkagan [suggested](https://github.com/votingworks/arlo/pull/2033#issuecomment-2455501439) removing the danger intent from the flag, and I mistakenly removed the icon altogether.
I currently lean towards the Flag instead of the Download icon to match the flag used for discrepancies elsewhere on the page, and because it is a slightly different sort of report in that it is flagging issues rather than being a data dump, but happy to go with either.

Add icon to download discrepancy report button

---

client/package.json
client/yarn.lock

Fixes the error about using the nullish coalescing operator. Based on https://github.com/stylelint/stylelint/issues/4473#issuecomment-675555699

Upgrade stylelint-processor-styled-components to fix error

---

client/src/components/AuditAdmin/Setup/Contests/ContestForm.tsx
client/src/components/AuditAdmin/Setup/Contests/Contests.test.tsx
client/src/components/AuditAdmin/Setup/Contests/schema.ts
client/src/components/useContests.ts
client/src/types.ts
server/api/contests.py
server/api/reports.py
server/audit_math/macro.py
server/audit_math/sampler_contest.py
server/migrations/versions/7ca7a4b0bcc0_contest_pending_ballots.py
server/models.py
server/tests/audit_math/snapshots/snap_test_macro.py
server/tests/audit_math/test_macro.py
server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py
server/tests/batch_comparison/snapshots/snap_test_multi_contest_batch_comparison.py
server/tests/batch_comparison/snapshots/snap_test_sample_extra_batches_by_counting_group.py
server/tests/batch_comparison/test_batch_comparison.py

Task: #1928 
Problem as described by @MarkVVaudits:
> The underlying challenge is that batch data, state-level vote counts at audit launch, and the final certified totals all can be different. This can occur **because some ballots are still pending at audit launch (they have not yet been tallied, and their eligibility may be undetermined)** and/or because some ballots are treated as unauditable and not included in batch uploads.
This feature provides a way for audit admins to tell Arlo about any ballots that have not been tallied before audit launch (aka pending ballots). The batch comparison audit math is then updated to treat these ballots conservatively, assuming they are votes for the loser and modifying the reported margin as such. This increases the resulting sample size and …

Incorporate pending ballots in batch comparison audits

---

client/src/components/AuditAdmin/Progress/JurisdictionDiscrepancies.tsx
client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/AuditAdmin/Progress/Progress.tsx
client/src/components/useJurisdictions.ts
server/api/jurisdictions.py
server/tests/api/test_jurisdictions.py
server/tests/ballot_comparison/test_ballot_comparison.py

Recommend to review commit by commit
This PR adds discrepancies in UI for ballot comparison audits.
[Issue](https://github.com/votingworks/arlo/issues/1912)
https://github.com/user-attachments/assets/ab0b007c-cf93-4312-9005-808ac2705667

Show discrepancies in UI for ballot comparison audits

---

server/api/batch_inventory.py
server/api/batch_tallies.py
server/api/contests.py
server/api/cvrs.py
server/api/standardized_contests.py
server/models.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/ballot_comparison/test_standardized_contests.py
server/tests/batch_comparison/test_batch_inventory.py
server/tests/batch_comparison/test_batch_tallies.py
server/tests/batch_comparison/test_multi_contest_batch_comparison.py
server/tests/helpers.py
server/tests/test_background_tasks.py

Refs https://github.com/votingworks/arlo/issues/1532
When making updates we'd like to check that no incomplete background jobs are dependent on the data we're about to change. This change takes steps in that direction, but does not fully fix the issue. For example, this change does not prevent deleting files where an incomplete job references that file.
I'd appreciate a more thorough review of this since it's the first non-trivial change I've made to Arlo in a while. See [this Slack thread](https://votingworks.slack.com/archives/CKCVA0F9S/p1730750352776399) for context.

fix: prevent some updates that would affect incomplete jobs

---

server/api/batch_inventory.py
server/tests/batch_comparison/snapshots/snap_test_batch_inventory.py
server/tests/batch_comparison/test_batch_inventory.py

https://github.com/votingworks/arlo/issues/2037
Adds testing and updates ESS batch inventory flow to:
- Not double count ballots for the manifest when used with multiple contests
- Handle write-ins better 
- Adds a fallback to check for a "Batch Name" column to name the batches if "Batch" does not exist as I noticed this in some real world CVR examples 
We still don't handle vote for many contests which are also not handled in the regular ESS cvr parsing flow

Add tests and fix small issues with ess batch inventory flow

---

server/api/ballot_manifest.py
server/api/batch_inventory.py
server/api/batch_tallies.py
server/api/cvrs.py
server/api/jurisdictions.py
server/api/standardized_contests.py
server/tests/api/test_ballot_manifest.py
server/tests/api/test_jurisdictions_file.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/ballot_comparison/test_standardized_contests.py
server/tests/batch_comparison/test_batch_inventory.py
server/tests/batch_comparison/test_batch_tallies.py
server/tests/helpers.py
server/tests/util/test_csv_parse.py
server/tests/util/test_file_storage.py
server/util/csv_parse.py
server/util/file.py

https://github.com/votingworks/arlo/issues/2039 
Validates that the storage path passed to upload-complete is the expected path before saving.

Add stronger validation for storage path on upload complete endpoints

---

client/src/components/AuditAdmin/Progress/Progress.tsx

Fix spacing on icon for review discrepancies button

---

server/api/jurisdictions.py
server/tests/batch_comparison/test_batch_comparison.py

This PR closes out https://github.com/votingworks/arlo/issues/1912.
It adds support for combined batches when calculating discrepancies.

Support combined batches when calculating discrepancies

---

server/api/batch_inventory.py
server/tests/batch_comparison/snapshots/snap_test_batch_inventory.py
server/tests/batch_comparison/test_batch_inventory.py

We've been seeing some Dominion files from Georgia with an extra space between contest names and the number of votes allowed in contest headers, e.g., `Contest 1  (Vote For=1)` as opposed to `Contest 1 (Vote For=1)`.
This is not true for all files across the state and likely has to do with different people managing programming for different jurisdictions, so we can't just add an extra space to the contest name in the Arlo audit config.
While we're advising jurisdictions on how to correct, this may be widespread enough that it's worth us just handling this automatically. That's what this PR does - it trims the extra spaces down to a single space.

Batch audit file prep tool: Handle extra spaces in Dominion CVR contest headers

---

server/api/ballot_manifest.py
server/tests/batch_comparison/test_sample_extra_batches_by_counting_group.py

Fixes: https://github.com/votingworks/arlo/issues/2054
Follow up to https://github.com/votingworks/arlo/pull/2011 to also show a similar error message when the Container column is missing, not only when it contains an invalid value.
The previous message was just `Missing required column "Container"`, which wasn't clear enough.

Improve error message when using batch inventory but missing container

---

client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/SupportTools.tsx
client/src/components/SupportTools/support-api.tsx
server/api/support.py
server/tests/api/test_support.py

Tweaks the list of audits on the support users home screen and the per-organization view to include a "status" tag with one of the following statuses: 
- Not Started - Round 1 has not started
- Round X In Progress
- Completed
The active audits list on the home page is already querying for audits updated in the last 2 weeks, I tweaked this to order the results by the last update date as I have personally found this confusing behavior. 
The organization page now orders audits by creation date (most recent first) to match the audit admin view 
New Screens

Make list of audits for support users easier to navigate

---

client/src/components/AuditAdmin/Progress/JurisdictionDetail.tsx

We already changed the jurisdiction manager UI for uploading ES&S CVR files to accept zips rather than CSVs, but didn't also change this audit admin interface. (See #2012)
Had to manual test since there's not an easy way to automated test this that I know of.

Expect zipped CVR file uploads in audit admin view

---

client/src/components/AuditAdmin/Progress/JurisdictionDiscrepancies.tsx
client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/AuditAdmin/Progress/Progress.tsx
client/src/components/_mocks.ts
client/src/components/useJurisdictions.ts
server/api/jurisdictions.py
server/tests/api/test_jurisdictions.py
server/tests/ballot_comparison/test_ballot_comparison.py
server/tests/batch_comparison/test_batch_comparison.py
server/tests/batch_comparison/test_multi_contest_batch_comparison.py

Now that we load the discrepancies themselves, we don't need to make a separate query to load the counts - we can just count them.

Refactor Audit Progress to use discrepancy query instead of discrepancy counts endpoint

---

server/api/ballot_manifest.py
server/api/batch_inventory.py
server/api/batch_tallies.py
server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/batch_comparison/test_batch_inventory.py
server/tests/batch_comparison/test_batch_tallies.py
server/util/file.py

Closes #1532 
Builds on https://github.com/votingworks/arlo/pull/2043
Adds guards to all jurisdiction file uploads to make sure that a JM can't accidentally remove or change a file that another pending file upload depends on. To keep things simple, I added guards on all files. While there are a few cases that may actually be safe, it felt easier to just have a blanket rule.
Note that I didn't have to add any more guards for election-level files, since those were already sufficient (we don't currently have "delete" functionality for those files, only replace).

Prevent race conditions when uploading/removing jurisdiction files

---

client/src/components/SupportTools/SupportTools.tsx

Accidently reversed the order here when I updated the PR to use sortBy, this fixes it and makes most recently created at the top of the list

reverse order of elections on support org page

---

server/api/contests.py
server/tests/batch_comparison/test_multi_contest_batch_comparison.py

Fixes https://github.com/votingworks/arlo/issues/1977
Previously, we were reprocessing all jurisdictions' batch tallies files whenever we made a request to update contests. This can be pretty disruptive because it affects every jurisdiction.
There are a few cases that we know don't actually impact the batch tallies at all, so we can skip reprocessing:
- When the audit admin doesn't change the contests at all (e.g. if they click "Save & Next" on the contests form without changing anything
- When the audit admin only changes the contest's jurisdiction list. Since batch tallies are specific to a single jurisdiction, adding or removing a jurisdiction will have no impact on other jurisdiction's batch tallies.

Only reprocess batch tallies when relevant contest fields change

---

client/src/components/AuditAdmin/AuditAdminView.tsx
client/src/components/useJurisdictions.ts

Deletes an unnecessary call to `invalidateQueries` per https://github.com/votingworks/arlo/pull/2061#discussion_r1847115083

delete unnecessary invalidateQueries call

---

server/activity_log/slack_worker.py
server/tests/test_slack_worker.py

Otherwise we get a `msg_too_long` error. I based the limit of 4000 characters on the Slack API docs: https://api.slack.com/methods/chat.postMessage#truncating

Truncate long error messages in Slack activity notifications

---

server/api/batch_tallies.py
server/api/cvrs.py
server/tests/ballot_comparison/test_cvrs.py
server/tests/batch_comparison/test_batch_tallies.py
server/util/string.py

Shortens two error messages that previously contained arbitrarily long lists of items from the uploaded files. Instead of showing the entire list, just show the first few items to make it easier to read.

Shorten unbounded file processing error messages

---

server/api/jurisdictions.py
server/api/support.py
server/tests/api/test_support.py

https://github.com/votingworks/arlo/issues/1891
* Filters soft-deleted elections from support users' active elections page
* Reduces active window from 14 to 7 days
**Previous broken behavior**
Soft-deleted elections are listed, allowing user to click in and eventually trigger error.
https://github.com/user-attachments/assets/87ef69d7-97fc-48cb-9bfd-928af8b411de
**After filtering**
Soft-deleted election no longer listed.

Adjust active election filtering

---

server/tests/api/test_jurisdictions.py

I'm not 100% sure this will fix the issue but my guess is that the expected login event is being created ~simultaneously with the round, causing it to be filtered out by the timestamp query.

Fix flaky test with last login by jurisdiction

---

Procfile

Configures `gunicorn` to restart web workers after every N requests (with a random "jitter" to avoid simultaneous worker restarts). This will contain slow memory leakage.
To set the threshold, I observed from logs that each dyno is fielding about 1.6k requests per hour at peak traffic. There are 4 workers per dyno, so that's about 400 requests per worker per hour. Based on how quickly memory has been rising, it seemed like restarting each worker around once every 2-3 hours would be sufficient to contain the issue, so I set the request limit to 1000.

Auto-restart web dynos regularly

---

server/api/reports.py
server/tests/ballot_comparison/test_single_jurisdiction_ballot_comparison.py
server/tests/batch_comparison/test_single_jurisdiction_batch_comparison.py

Normally, we wait to show discrepancies until they audit boards sign off (ballot comparison) or finalize batch results (batch comparison). This is good in general, but in single jurisdiction audits, it means there is no visibility into discrepancies until the audit is over. (Generally single jurisdiction audits are used for large jurisdictions.) So we make an exception and show the discrepancies immediately for single jurisdiction audits.

In single jurisdiction audits, show discrepancies as they are audited

---

.circleci/config.yml
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/Contests.test.tsx.snap
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/HybridContestForm.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/JurisdictionAdmin/__snapshots__/FullHandTallyDataEntry.test.tsx.snap
client/src/components/SupportTools/SupportTools.tsx
server/api/support.py
server/tests/api/test_support.py

https://github.com/votingworks/arlo/issues/1854
Adds a tool to the bottom of the Organizations column on the support page to export a csv of Audit Admins and Jurisdiction Managers.

Add tool for support users to export Audit Admins and Jurisdiction Managers

---

server/config.py
server/tests/test_auth.py

We log the database URL on web server startup. In prod, this may contain a username/password that is probably best kept as secret as possible. So this PR scrubs these credentials before logging when `FLASK_ENV=production`.

Scrub database credentials from logs in production

---

scripts/parse-xml-cvrs.py
server/api/batch_inventory.py
server/api/cvrs.py
server/util/csv_parse.py

Updates a script used to parse xml cvrs into dominion csv form to
- If provided parse scanned ballot information files and adds "Workstation" column to the outputted csv, in the future if we want to add other columns from the scanned ballot info that would be easy. This option also assumes the xml cvr files are in a subdirectory within an outer directory containing that folder and the scanned ballot information files. 
- If run with --include-votes-cast-per-contest will add a column for every contest with the total votes cast in each contest for that cvr row. This will allow a human interpretting the csv to determine which cvrs represent undervotes or overvotes without needing to understand the number of votes allowed to be cast per contest in the context of the script 
In order to filter …

Modify parse-xml-cvrs to support ask from Clark County

---

.circleci/config.yml

Sometimes, it appears that the Cypress cache is restored successfully but the actual files are not present in the filesystem as far as I can tell. This causes the CI job to fail.
Until we can get to the bottom of what's going on, this PR implements a workaround to check if Cypress is installed and, if not, install it.

CircleCI: Install Cypress again if cache restoration didn't work

---

server/tests/api/test_jurisdictions.py

Possibly addresses a [flaky test](https://app.circleci.com/pipelines/github/votingworks/arlo/7592/workflows/2fddd1fc-e91a-45ef-bd23-13784f44b71f/jobs/23361).
I wasn't able to repro locally so I can't confirm, but usage of `record_login` in prod routes includes immediately [committing the db session](https://github.com/votingworks/arlo/blob/63c5fd98311d625691181e282298bf3c4c36701a/server/auth/auth_routes.py#L341-L342). The test doesn't explicitly commit the db session, and the db session being flushed some but not all of the time would explain the flakiness and outcome of the test.

commit db session after logs are added to it in test

---

.circleci/config.yml
README.md

We've been seeing issues the last couple weeks with the cached Cypress binary being found in the cache, supposedly restored, but then it is missing when Cypress runs.
We implemented a safe fail last week, where we check if Cypress is there, and then install it if not. This has unblocked development, but recent builds have been needing to use the failsafe, reinstalling Cypress on [main](https://app.circleci.com/jobs/github/votingworks/arlo/23455) and this recent [branch](https://app.circleci.com/pipelines/github/votingworks/arlo/7630/workflows/2936d6fa-1f68-49c2-978c-7dfacd1dbac2/jobs/23519) during the `Verify Cypress` step. 
1. This PR changes the cache path from using a `~` to indicate the home path, to explicitly using the home path of `home/circleci`. In a somewhat unrelated post, it …

Attempt to fix Cypress CI caching issue

---

client/src/components/Atoms/StatusTag.tsx
client/src/components/AuditAdmin/Progress/Progress.test.tsx
client/src/components/AuditAdmin/Progress/Progress.tsx
client/src/components/AuditAdmin/Progress/ProgressMap.tsx

https://github.com/votingworks/arlo/issues/2065
Updates `Logged in` status to be a different color than the various `In progress` statuses. The latter is now `GOLD1`/`GOLD4` in [Blueprint](https://blueprintjs.com/docs/#core/colors) upon which Arlo's design system is based. `Logged in` used to use the `warning` `Intent` that `In progress` also uses. `warning` uses orange per [Blueprint docs](https://blueprintjs.com/docs/#core/colors).
I didn't want to get into changing the vendored design system so I added a non-standard `alert` intent on the Arlo component that needs it. The non-standard intent is filtered out so we don't pass it as an invalid prop to the underlying Blueprint components.

differentiate logged-in status from in-progress status

---

.circleci/config.yml
Makefile
client/Makefile

This PR makes updates to Makefile to better mirror the commands of VxSuite and more common make commands.
The inspiration for this was that as a new developer to Arlo, I found myself stumbling a bit when figuring out what commands to run. My hope is that this would be intuitive for both more familiar and newer engineers.
I've made some opinionated choices, with the idea that feedback will help me find the right balance. I'm definitely not attached to any of these changes!
Main points:
1. If possible, choose a command name that mirrors VxSuite [commands](https://github.com/votingworks/vxsuite/blob/main/apps/mark/backend/Makefile) and fallback to other common commands
2. Since the root directory is also the root of the server, let all base commands (like `make typecheck`) reference the …

Standardize Makefile

---

server/api/discrepancies.py
server/api/shared.py
server/tests/batch_comparison/test_single_jurisdiction_batch_comparison.py

We recently introduced a special case where we surface discrepancies for single jurisdiction batch comparison audits even before the round is finalized. But, this meant that immediately upon the round opening, we were showing discrepancies.
We only want to show discrepancies for batches that have been audited. There may be a more correct way to do this using a db query, but this PR uses the approach of checking the `audited_batch_result` object that we are already using, and looks for a single non-zero entry indicating the result is valid.
Now we no longer see the discrepancies upon launching. 
But once a single batch is audited, we see only those discrepancies.
1. The discrepancy report already handled this by checking if a batch is `audited` using [this check …

Only surface discrepancies in single jurisdiction for finalized batches

---

client/src/components/Atoms/Wrapper.tsx
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/Contests.test.tsx.snap
client/src/components/AuditAdmin/Setup/Contests/__snapshots__/HybridContestForm.test.tsx.snap
client/src/components/AuditAdmin/__snapshots__/ActivityLog.test.tsx.snap
client/src/components/AuditAdmin/__snapshots__/AuditAdminView.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/Ballot.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/BoardTable.test.tsx.snap
client/src/components/AuditBoard/__snapshots__/SignOff.test.tsx.snap
client/src/components/Header.tsx
client/src/components/JurisdictionAdmin/__snapshots__/FullHandTallyDataEntry.test.tsx.snap
client/src/components/SupportTools/SupportTools.test.tsx
client/src/components/SupportTools/SupportTools.tsx

Updated with Fixed Padding
https://github.com/user-attachments/assets/d0cb0ea6-be43-46af-bd72-8fc75a91c2b8
Updated with Filter Input:
https://github.com/user-attachments/assets/36cd9445-4d3b-4a41-b033-2ca4347c00fb
Updated after PR feedback:
https://github.com/user-attachments/assets/95cd42f5-a993-4315-a2fa-aed159ac88d9
Outdated:
https://github.com/user-attachments/assets/9399c5ad-a0c3-44c6-b35a-d62016c980ce
Main changes:
1. Increase width of support tools pages. Next, I plan to improve the spacing of the Organization, Audit, and Jurisdiction sub-pages.
2. Make Active Audits the widest column. This is just preference for how the page looks with it. Also move the status tag to the right side.
3. Rename Downloads to Tools, move Create Org button there, disable button until input is dirty, …

Update Support Tools UI Homepage

---

app.json

Upgrades to Heroku stack 24 following [official docs](https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack#setting-the-stack). All 3 apps have already been upgraded with `heroku stack:set heroku-24 -a <name>` but a successful new build is required to complete the process.
https://github.com/votingworks/arlo/issues/2101

Upgrade to heroku 24

---

server/api/batch_inventory.py
server/tests/batch_comparison/test_batch_inventory.py

Similar in spirit to https://github.com/votingworks/arlo/pull/2053 but for leading/trailing spaces in CVR choice names, which we're seeing for a specific choice in Georgia's current batch inventory CVR uploads.
> :x: Could not find contest choices in CVR file: Tim Echols (I) for contest PSC - District 2 - Rep.
In the CVR file, there's a space at the end of `Tim Echols (I) `.

Batch inventory: Trim leading/trailing spaces from CVR choice names

---

server/tests/util/test_csv_parse.py
server/util/csv_parse.py

We have a valid ballot manifest in Georgia that's getting flagged as having a total row, i.e., a row where the last row is simply the sum of all rows above, and thereby rejected.
| Container | Batch Name | Number of Ballots |
| :- | :- | :- |
| Advanced Voting | AV-Elections Office ICP 1 - 0 | 6 |
| Election Day | Election Day Central ICP 1 - 0 | 6 |
> :x: It looks like the last row in the CSV might be a total row. Please remove this row from the CSV.
To get this file through, I'm disabling the total row check when a CSV has only two rows, which generally seems like a good idea.

Don't surface total row error when a CSV has only two rows

---

server/tests/api/test_public.py
server/util/file.py

Prevents a user-controllable string (`key` in the request) from being used to write data to an arbitrary path on the local file system.

fix(security): prevent path traversal in `/api/file-upload`
