app.py
This is almost identical to #191, just for a different CSV file and refactors slightly to use the same logic for both.
Closes #194
=> feat: improve filename of audit report

arlo-client/src/components/AuditForms/__snapshots__/index.test.tsx.snap
Fixes merge conflict caused by https://github.com/votingworks/arlo/pull/196 and https://github.com/votingworks/arlo/pull/197.
=> test: update snapshots after merge conflict

audits/bravo.py, tests/test_bravo.py
=> bugfix: fixes expected sample numbers to include prior samples. 

app.py
=> fix: constrain audit board to hopefully prevent duplicates

.dockerignore, Dockerfile, README.md, arlo-client/src/setupProxy.js, config/database.cfg.docker, docker-compose.yml
This commit adds the ability to develop Arlo using Docker as an alternative approach. This does not replace the existing approach, just makes a new one available.
The main advantages are reproducibility and isolation of development environment, ease of installing dependencies regardless of the host system, and ease of orchestrating development processes. The main disadvantages are adding indirection to development systems and adding reliance on yet more software (Docker).
If we're not opposed to this in principle, I'd appreciate if you could try it out and let me know what you think.
=> Add Docker infrastructure

app.py, tests/test_app.py
Addresses @mcchilders comment about deduplicating the retrieval list on #198. https://github.com/votingworks/arlo/pull/198#issuecomment-569736536
=> Dedupes ballots in retrieval list, puts in list of ticket numbers

arlo-client/src/components/AuditFlow/Ballot.test.tsx
master was broken somehow. fixing field name.
=> fix winners --> numWinners

pull_request_template.md
Adding workflow requirement to keep rebasing top of mind 
**New Tests**
NA
**Checklist**
*Function*
[] Code is fully functional and ready for review (or is tagged WIP)
[] No errors/warnings in the browser console ( ﾟヮﾟ)/
[] package.json is committed if I added or removed any dependencies
[] Tests added as needed to ensure code base still has 100% passing coverage
[] Tests added as needed to cover new functionality
*Style*
[] Passes linter without errors
[] Code is easily understandable and self-documenting (using naming conventions in keeping with the rest of the codebase)
[] Interfaces all have 'I' before their names (as in `IAudit`)
[] Comments are only included as needed to explain the 'why' instead of the 'what'
[] Common standards and coding practices are adhered to …
=> Adding new requirement

sampler.py, tests/test_sampler.py
This allows the MACRO math to actually work on the sample we draw. See [here](https://static.usenix.org/events/evt08/tech/full_papers/aslam/aslam.pdf) for more. This PR depends on #223.
=> Adds sampling with probability proportional to error bound

app.py, arlo-client/src/components/AuditFlow/index.tsx, arlo-client/src/components/AuditForms/CalculateRiskMeasurement.test.tsx, arlo-client/src/components/AuditForms/CalculateRiskMeasurement.tsx, arlo-client/src/components/AuditForms/EstimateSampleSize.test.tsx, arlo-client/src/components/AuditForms/EstimateSampleSize.tsx, arlo-client/src/components/AuditForms/SelectBallotsToAudit.tsx, arlo-client/src/components/AuditForms/__snapshots__/CalculateRiskMeasurement.test.tsx.snap, arlo-client/src/components/AuditForms/__snapshots__/EstimateSampleSize.test.tsx.snap, arlo-client/src/components/AuditForms/__snapshots__/SelectBallotsToAudit.test.tsx.snap, arlo-client/src/components/AuditForms/__snapshots__/index.test.tsx.snap, arlo-client/src/components/AuditForms/_mocks.ts, arlo-client/src/components/AuditForms/index.test.tsx, arlo-client/src/components/AuditForms/index.tsx, arlo-client/src/test/specs/auditFlow.ts, arlo-client/src/test/specs/createAudit.ts, arlo-client/src/test/specs/helpers.ts, arlo-client/src/types.ts, arlo-client/test-run.log, models.py, tests/test_app.py
- Added `auto` field to the `AuditBoard` type
- Added checkboxes into form two for each audit board
- Updated models and endpoints to support this
- Updated frontend to reflect backend support
**New Tests**
- Update unit tests and snapshots, as well as test functionality
- Updated end to end tests
**Checklist**
*Function*
[*] Code is fully functional and ready for review (or is tagged WIP)
[*] No errors/warnings in the browser console ( ﾟヮﾟ)/
[*] package.json is committed if I added or removed any dependencies
[*] Tests added as needed to ensure code base still has 100% passing coverage
[*] Tests added as needed to cover new functionality
*Style*
[*] Passes linter without errors
[*] Code is easily understandable and self-documenting (using naming conventions in keeping …
=> Adding auto toggle functionality

Makefile, README.md, app.py, arlo-client/src/components/AuditFlow/index.tsx, arlo-client/src/components/AuditForms/CalculateRiskMeasurement.test.tsx, arlo-client/src/components/AuditForms/CalculateRiskMeasurement.tsx, arlo-client/src/components/AuditForms/EstimateSampleSize.test.tsx, arlo-client/src/components/AuditForms/EstimateSampleSize.tsx, arlo-client/src/components/AuditForms/SelectBallotsToAudit.tsx, arlo-client/src/components/AuditForms/__snapshots__/CalculateRiskMeasurement.test.tsx.snap, arlo-client/src/components/AuditForms/__snapshots__/EstimateSampleSize.test.tsx.snap, arlo-client/src/components/AuditForms/__snapshots__/SelectBallotsToAudit.test.tsx.snap, arlo-client/src/components/AuditForms/__snapshots__/index.test.tsx.snap, arlo-client/src/components/AuditForms/_mocks.ts, arlo-client/src/components/AuditForms/index.test.tsx, arlo-client/src/components/AuditForms/index.tsx, arlo-client/src/test/specs/auditFlow.ts, arlo-client/src/test/specs/createAudit.ts, arlo-client/src/test/specs/helpers.ts, arlo-client/src/types.ts, arlo-client/test-run.log, config/database.cfg.dev, models.py, run-dev.sh, tests/test_app.py
make it easier to dev in Linux without Docker.
=> More makefile

arlo-client/package.json, arlo-client/src/components/AuditFlow/BoardTable.tsx, arlo-client/src/components/AuditFlow/__snapshots__/index.test.tsx.snap, arlo-client/src/components/AuditFlow/__snapshots__/index_members.test.tsx.snap, arlo-client/src/components/AuditFlow/index.test.tsx, arlo-client/src/components/AuditFlow/index.tsx, arlo-client/src/components/AuditFlow/index_members.test.tsx, arlo-client/src/components/AuditForms/CalculateRiskMeasurement.test.tsx, arlo-client/src/components/AuditForms/index.test.tsx, arlo-client/src/components/utilities.ts, arlo-client/yarn.lock
- Restructured some of the hooks and conditions in the audit data entry flow index so that it's not using stale and blank data at unexpected times.
- This solves the randomly appearing timeout error toast popup
**New Tests**
- Made testing for when there is and isn't ballots more stable and wrapped more `render` calls in `async act` blocks.
**Checklist**
*Function*
[*] Code is fully functional and ready for review (or is tagged WIP)
[*] No errors/warnings in the browser console ( ﾟヮﾟ)/
[*] package.json is committed if I added or removed any dependencies
[*] Tests added as needed to ensure code base still has 100% passing coverage
[*] Tests added as needed to cover new functionality
*Style*
[*] Passes linter without errors
[*] Code is easily understandable and …
=> Timeout fix

API.md, arlo-client/docs/api_sequence.md
Using `jsonc` language code allows us to use comments in JSON and to have prettier reformat it nicely, and for it to be displayed with nice syntax highlighting.
=> docs(api): reformat JSON using jsonc

audits/macro.py, sampler.py, tests/test_macro.py
* Addresses issues raised by @plauditsforaudits, closes #274
* Refactors MACRO class and usage to be a bit more pythonic, i.e. to
get a higher pylint score :sweat_smile:
=> Refactors MACRO class

Makefile, README.md, app.py, config/__init__.py
These are some fixes for problems I ran into while setting up my dev environment. Probably easiest to view commit by commit as it's a grab bag of unrelated items.
**New Tests**
N/A
**Checklist**
N/A
=> Fixes from setting up my dev environment

arlo-client/.eslintignore, arlo-client/.eslintrc.js, arlo-client/package.json, arlo-client/src/components/AuditFlow/Ballot.tsx, arlo-client/src/components/AuditFlow/BoardTable.tsx, arlo-client/src/components/AuditFlow/MemberForm.test.tsx, arlo-client/src/components/AuditFlow/_mocks.ts, arlo-client/src/components/AuditFlow/index.test.tsx, arlo-client/src/components/AuditFlow/index.tsx, arlo-client/src/components/AuditForms/CalculateRiskMeasurement.test.tsx, arlo-client/src/components/AuditForms/CalculateRiskMeasurement.tsx, arlo-client/src/components/AuditForms/EstimateSampleSize.test.tsx, arlo-client/src/components/AuditForms/EstimateSampleSize.tsx, arlo-client/src/components/AuditForms/ResetButton.tsx, arlo-client/src/components/AuditForms/SelectBallotsToAudit.test.tsx, arlo-client/src/components/AuditForms/SelectBallotsToAudit.tsx, arlo-client/src/components/AuditForms/_mocks.ts, arlo-client/src/components/AuditForms/index.tsx, arlo-client/src/components/Form/_helpers.tsx, arlo-client/src/components/testUtilities.ts, arlo-client/src/components/utilities.test.ts, arlo-client/src/components/utilities.ts, arlo-client/src/serviceWorker.ts, arlo-client/src/test/specs/auditFlow.ts, arlo-client/src/test/specs/helpers.ts, arlo-client/src/test/types/webdriverio.d.ts, arlo-client/src/utils/indexes.ts, arlo-client/src/utils/number-schema.test.ts, arlo-client/src/utils/number-schema.ts, arlo-client/yarn.lock
These changes were almost entirely about upgrading eslint.
=> chore(dev-deps): upgrade `react-scripts`

audits/audit.py, audits/bravo.py, sampler.py
Small PR that spruces up some docstrings.
=> Fixes some docstring typos and inaccuracies

arlo_server/__init__.py, models.py
This is an early draft of possible data modeling for users and roles in Arlo. What do you think?
=> feat: add basic user/auth data models

arlo_server/base.py, config/__init__.py, tests/test_app.py
flask needs a trailing slash on static_folder for some reason.
=> Fix production build

Pipfile, Pipfile.lock, README.md, arlo-client/src/setupProxy.js, arlo_server/__init__.py, config/__init__.py, docs/auth0.md, mypy.ini, tests/test_auth.py
Implement the Auth0 flow for audit admins.
We may have a separate flow for jurisdiction admins, we'll see.
As per product tickets #250 and #260.
=> Audit Admin Login Flow

arlo_server/__init__.py, audits/bravo.py, tests/test_app.py, tests/test_macro.py, util/binpacking.py
Some of the unused variables I considered to be dead code and deleted their values as well. Others had side effects we wanted to preserve, such as asserting that a record exists in the database.
@umbernhard, I wanted to make sure the changes I made do not affect the audit math at all. They shouldn't, but better to check.
=> fix: ensure there are no unused variables in app code

arlo_server/__init__.py, models.py, tests/test_auth.py
`/auth/me` now provides the data necessary to create a landing page for a user's organizations and jurisdictions.
Needed for #261
=> provide orgs and jurisdictions for a user in /auth/me

arlo_server/__init__.py, tests/test_app.py, tests/test_report.py
Task: #237 
Adds a row to the audit board report with each audit board member's name and party affiliation, as well as the name of the audit board they were on.
**New Tests**
Adds test_report.py with a simple test that also covers the rest of the report content.
**Checklist**
*Function*
[] Code is fully functional and ready for review (or is tagged WIP)
[] No errors/warnings in the browser console ( ﾟヮﾟ)/
[] package.json is committed if I added or removed any dependencies
[] Tests added as needed to ensure code base still has 100% passing coverage
[] Tests added as needed to cover new functionality
*Style*
[] Passes linter without errors
[] Code is easily understandable and self-documenting (using naming conventions in keeping with the rest of the codebase)
[] Interfaces …
=> Add audit board members to audit report

models.py, tests/test_jurisdiction_bulk_update.py, util/jurisdiction_bulk_update.py
=> feat: add function to bulk-update election jurisdictions & admins

arlo_server/__init__.py
This was likely a copy-paste error.
=> fix: remove references to undefined variable

arlo_server/__init__.py, audits/bravo.py, audits/macro.py, sampler.py, tests/test_bravo.py, tests/test_contest.py, tests/test_macro.py, tests/test_sampler.py, util/contest.py
Refactors backend to be more functional. Adds a Contest data structure, and a few more tests.
=> Backend refactor

arlo_server/__init__.py, models.py
Task: #309 
To support both targeted and opportunistic contests, the first step is
to change the TargetedContest data type to be generic to all contests.
We add `is_targeted` as a boolean flag to specify which contests are
targeted and which are opportunistic. There are no other types of
contests, so this should be sufficient.
**Testing**
Covered by existing tests
**Progress**
Ready for review. This will require some sort of db migration - need advice on that.
=> Change TargetedContest model to Contest, adding is_targeted flag

package.json
since I merged #340 before I saw @eventualbuddha's last comment.
=> lock to python 3.7 like everything else

arlo_server/routes.py, tests/test_app_upload_jurisdictions_file.py
This updates the API signature to follow the proposal from #339.
**Testing**
Covered by existing tests.
**Progress**
Progress toward #339.
=> fix: correct the API signature for bulk jurisdictions upload

arlo_server/routes.py, tests/test_app_upload_jurisdictions_file.py, tests/test_contests.py, tests/test_jurisdictions.py
This brings it inline with the existing `/election/<election_id>/jurisdiction/…` endpoints.
**Testing**
Covered by existing tests.
**Progress**
This should make #365 a little simpler.
=> fix: move jurisdictions file upload to `…/jurisdiction/file`

arlo-client/src/App.tsx, arlo-client/src/__snapshots__/App.test.tsx.snap, arlo-client/src/components/Audit/__snapshots__/index.test.tsx.snap, arlo-client/src/components/Audit/index.test.tsx, arlo-client/src/components/Audit/index.tsx, arlo-client/src/components/CreateAudit.test.tsx, arlo-client/src/components/CreateAudit.tsx, arlo-client/src/components/Header.test.tsx, arlo-client/src/components/Header.tsx, arlo-client/src/components/__snapshots__/Header.test.tsx.snap
- Add links in the header for authenticated users
- Route `/election/:electionId/setup` and `/election/:electionId/progress` properly
**Testing**
- Updating snapshots
- Verifying that the right views display the right content with the right authentication and routing conditions
**Progress**
- Ready for review
- A bit sticking point with this was trying to get the react router hooks to be testable properly
=> Global header nav

arlo-client/src/components/Audit/__snapshots__/index.test.tsx.snap
The snapshots somehow got out of date. Most likely a logical merge conflict.
**Testing**
n/a
**Progress**
n/a
=> test: update snapshots

arlo_server/rounds.py, arlo_server/routes.py, arlo_server/sample_sizes.py, audit_math/bravo.py, audit_math/macro.py, audit_math/sampler.py, audit_math/sampler_contest.py, tests/test_audit_status.py, tests/test_bravo.py, tests/test_macro.py, tests/test_sampler.py, tests/test_sampler_contest.py, util/ballot_manifest.py
* Renames from `audits` to `audit_math
* Implementes typing for all of the audit_math files
* Cleans up some outdated documentation
**Testing**
N/A
**Progress**
=> General improvements to the audit_math library

.pylintrc
There were no violations of these rules, so this just changes the config to enforce them.
**Testing**
n/a
**Progress**
n/a
=> test(pylint): enable `possibly-unused-variable` and `undefined-variable` rules

arlo_server/__init__.py
Follow up to #401 
**Testing**
n/a
**Progress**
n/a
=> fix(csp): allow unsafe inline styles

arlo-client/package.json, arlo-client/src/components/Audit/Setup/Participants/__snapshots__/index.test.tsx.snap, arlo-client/src/components/Audit/Setup/Participants/index.test.tsx, arlo-client/src/components/Audit/Setup/Participants/index.tsx, arlo-client/src/components/Audit/Setup/Participants/types.ts, arlo-client/src/components/Audit/Setup/Settings/index.test.tsx, arlo-client/src/components/Audit/Setup/Settings/index.tsx, arlo-client/src/components/Audit/Setup/Settings/schema.ts, arlo-client/src/components/Audit/Setup/Settings/types.ts, arlo-client/src/components/Audit/Setup/__snapshots__/index.test.tsx.snap, arlo-client/src/components/Audit/Setup/index.test.tsx, arlo-client/src/components/Audit/Setup/useAuditSettings.test.tsx, arlo-client/src/components/Audit/Setup/useAuditSettings.tsx, arlo-client/src/components/Audit/__snapshots__/index.test.tsx.snap, arlo-client/src/components/Audit/_mocks.ts, arlo-client/src/components/Audit/index.test.tsx, arlo-client/src/components/Form/_helpers.tsx, arlo-client/src/setupProxy.js, arlo-client/src/types.ts, arlo-client/yarn.lock
- Add form to the Audit Settings screen
- Add submission to the `/election/:electionId/settings` endpoint from the Participants and Audit Settings screens
**Testing**
- none yet
**Progress**
- ~~TODO: tests~~ Done!
=> Audit settings

arlo_server/__init__.py, arlo_server/errors.py, arlo_server/routes.py
Moves the Flask error handlers to their own file. Also adds a function `handle_unique_constraint_exception`. I needed to use this logic in a different routes module so I am factoring it out in this PR.
**Testing**
Existing tests cover.
**Progress**
=> Move error handlers to separate file

arlo-client/src/components/DataEntry/__snapshots__/index.test.tsx.snap, arlo-client/src/components/DataEntry/__snapshots__/index_members.test.tsx.snap, arlo-client/src/components/DataEntry/index.tsx
- When styling the wrapper for the audit setup flow to account for the sidebar, it inadvertently messed up the styling for the audit board member forms. Fixed now.
**Testing**
- Just the snapshots
**Progress**
- Done!
=> Fixing styling of audit board member form

arlo-client/src/components/Audit/EstimateSampleSize.tsx, arlo-client/src/components/Audit/__snapshots__/EstimateSampleSize.test.tsx.snap, arlo-client/src/components/Audit/__snapshots__/index.test.tsx.snap, arlo-client/src/test/specs/helpers.ts, arlo-client/wdio.conf.js
According to the test logs from failed test runs, the tests timed out waiting for the #audit-name component to be interactable. But there are two different components with id #audit-name! One is on the create audit screen, one on the audit setup screen (which is actually the election name, not the audit name).
My hypothesis is that the second time the tests try to find #audit-name, they sometimes find the component from the first screen, which has been removed from the DOM (or disabled, I'm not sure which) and is no longer interactable.
I think this is confirmed by the following test log. The first time we find #audit-name, we get back:
```
[0-1] 2020-04-16T20:52:53.929Z INFO webdriver: RESULT { 'element-6066-11e4-a52e-4f735466cecf': '4057cfd9-61da-4882-a380-7bd0c756c7bf' }
```
The second …
=> Fix integration tests: change #audit-name to #election-name

tests/conftest.py, tests/helpers.py, tests/routes_tests/test_audit_boards.py, tests/routes_tests/test_ballots.py, tests/routes_tests/test_contests.py, tests/routes_tests/test_jurisdictions.py
Just consolidating some common test constants.
**Testing**
Existing tests cover.
**Progress**
=> Factor out test constants

Pipfile.lock, config/__init__.py, tests/test_app.py
There was a bugfix for the static folder logic that caused a test
failure. See more details here: https://github.com/pallets/flask/issues/3452
(I ran into this while trying to add `pytest-cov` to Pipfile, which resulted in this upgrade)
**Testing**
Fixed broken test. Ran the app locally
**Progress**
=> Upgrade to Flask 1.1.2

arlo_server/audit_boards.py, tests/conftest.py, tests/helpers.py, tests/routes_tests/test_audit_boards.py, tests/routes_tests/test_ballots.py, tests/routes_tests/test_jurisdictions.py, tests/routes_tests/test_sample_sizes.py, tests/test_rounds.py
Forgot to do this before since it's not something that was implemented yet in the single jurisdiction flow.
**Testing**
Added some checks to existing test cases.
**Progress**
=> Count votes and record results when ending a round

arlo_server/contests.py, tests/routes_tests/test_contests.py
Adds `/election/<election_id>/jurisdiction/<jurisdiction_id>/round/<round_id>/audit-board/<audit_board_id>/contest` that gets a list of contests when logged in as an audit board. It only returns the contests that have the audit board's jurisdiction in their contest universe.
**Testing**
Added two new tests.
**Progress**
Ready.
=> Add list contests endpoint for audit boards

arlo-client/src/App.tsx, arlo-client/src/__snapshots__/App.test.tsx.snap, arlo-client/src/components/Audit/RoundManagement/index.tsx, arlo-client/src/components/Audit/__snapshots__/index.test.tsx.snap, arlo-client/src/components/Audit/index.test.tsx, arlo-client/src/components/Audit/index.tsx, arlo-client/src/components/Audit/useRoundsJurisdictionAdmin.ts, arlo-client/src/components/CreateAudit.test.tsx, arlo-client/src/components/CreateAudit.tsx, arlo-client/src/components/DataEntry/__snapshots__/index.test.tsx.snap, arlo-client/src/components/UserContext.tsx, arlo-client/src/components/__snapshots__/CreateAudit.test.tsx.snap, arlo-client/src/types.ts
Separate the `Audit` component into different components for diff audit types/user types.
**Testing**
Existing tests cover.
**Progress**
Ready
=> Refactor audit component

arlo-client/src/components/Audit/Progress/index.tsx, arlo-client/src/components/Audit/useJurisdictions.ts
Add statuses for the current round to the Jurisdiction Progress screen.
**Testing**
Skipped
**Progress**
Ready
=> AA Jurisdiction Progress screen (during round)

arlo_server/superadmin.py, arlo_server/templates/superadmin/jurisdictions.html, arlo_server/templates/superadmin/organizations.html, tests/helpers.py, tests/routes_tests/test_superadmin.py
tests not fully written yet, waiting to see how horrified @jonahkagan is first :)
=> old-man HTML actions for super admins

arlo-client/src/components/Audit/__snapshots__/index.test.tsx.snap, arlo-client/src/components/Audit/index.test.tsx, arlo-client/src/components/Audit/index.tsx
There's no separate "round management" view for AAs, so we default them to the progress view.
**Testing**
Changed one test.
**Progress**
Ready
=> Audit admin default to progress view

arlo-client/src/App.tsx, arlo-client/src/components/Audit/RoundManagement/CreateAuditBoards.tsx, arlo-client/src/components/Audit/RoundManagement/generateSheets.ts, arlo-client/src/components/Audit/RoundManagement/index.tsx, arlo-client/src/components/Audit/Setup/BallotManifest/index.tsx, arlo-client/src/components/Audit/StatusBox.tsx, arlo-client/src/components/Audit/__snapshots__/index.test.tsx.snap, arlo-client/src/components/Audit/index.tsx, arlo-client/src/components/Audit/useAuditBoards.ts, arlo-client/src/components/Audit/useBallotManifest.ts, arlo-client/src/components/Audit/useJurisdictions.ts, arlo-client/src/components/Audit/useRoundsJurisdictionAdmin.ts
Adds the Jurisdiction Admin status box. Hoists state that is depended on by both the status box and the other JA views into the parent component.
**Testing**
No new tests
**Progress**
Ready
=> Jurisdiction Admin Status Box

arlo-client/src/components/Audit/RoundManagement/RoundProgress.tsx, arlo-client/src/components/Audit/RoundManagement/index.tsx
- Adding progress bars to the Round Progress view
**Testing**
- none yet
**Progress**
- Looks nice, imo!
=> Adding progress bars

arlo-client/src/components/Audit/StatusBox.tsx
=> Status bar cleanup

arlo-client/src/components/Audit/Setup/Participants/index.tsx, arlo-client/src/components/Audit/Setup/Participants/useJurisdictionFile.ts
- Abstracted out management of the jurisdictions manifest like with the ballot manifest, and made it so it shows the details of the currently uploaded file, as well as allowing you to replace it.
**Testing**
- not touched
**Progress**
- LGTM
=> Replace jurisdictions

.circleci/config.yml, arlo_server/auth.py, config/__init__.py, tests/routes_tests/test_superadmin_loadtesting.py
a focused auth hack for load testing. PR against the `loadtesting` branch that should never be merged into master.
=> auth hack for loadtesting

arlo-client/src/components/Audit/Setup/BallotManifest/index.tsx
- Fix bug setting default state from props
- Rearrange buttons to better match the mock
**Testing**
N/A
**Progress**
Ready
=> Fix JA ballot manifest upload

create-admin.py
So we don't forget to create the user in auth0 as well
=> Add auth0 note to create-admin.py

arlo-client/src/components/DataEntry/Atoms.tsx, arlo-client/src/components/DataEntry/BoardTable.test.tsx, arlo-client/src/components/DataEntry/BoardTable.tsx, arlo-client/src/components/DataEntry/MemberForm.tsx, arlo-client/src/components/DataEntry/SignOff.tsx, arlo-client/src/components/DataEntry/__snapshots__/Ballot.test.tsx.snap, arlo-client/src/components/DataEntry/__snapshots__/BoardTable.test.tsx.snap, arlo-client/src/components/DataEntry/__snapshots__/MemberForm.test.tsx.snap, arlo-client/src/components/DataEntry/__snapshots__/index.test.tsx.snap, arlo-client/src/components/DataEntry/_mocks.ts, arlo-client/src/components/DataEntry/index.test.tsx, arlo-client/src/components/DataEntry/index.tsx, arlo-client/src/components/utilities.ts, arlo-client/src/types.ts, arlo_server/routes.py, tests/routes_tests/test_auth.py
Added a signoff page and final confirmation page
Updated the backend to return `signedOffAt`
**Testing**
Updated existing tests
**Progress**
Ready
=> Audit board signoff

arlo-client/src/components/Audit/Setup/BallotManifest/index.tsx, arlo-client/src/components/Audit/Setup/Participants/index.tsx
- Adding a key to the replace button so they don't prompt a submit due to this bug: https://github.com/jaredpalmer/formik/issues/2004
**Testing**
- none
**Progress**
- It works!
=> Upload toggle fix

arlo-client/src/components/Audit/Setup/BallotManifest/index.tsx, arlo-client/src/components/Audit/useBallotManifest.ts
While the ballot manifest is uploading, poll in the background until it completes. If there's an error at the end, show the error.
=> Poll for ballot manifest upload status

audit_math/bravo.py, tests/audit_math_tests/test_bravo.py
Adds logical check in backend math for landslides (when one candidate gets all the votes). 
**Testing**
Adds new tests in the backend to cover this case. 
**Progress**
N/A
=> Fix landslides

tests/routes_tests/test_audit_boards.py
This test was failing like 1/30 times. I think this fixes it.
=> Fix non-deterministic audit board test

arlo-client/src/components/Audit/Setup/Review/index.tsx
- Adds link to the review and launch stage for downloading the jurisdictions file
**Testing**
- none
**Progress**
- Needs the endpoint to be integrated into the backend to work
=> Adding link to jurisdictions file download

arlo-client/src/components/Audit/StatusBox.tsx
Just messed this up somehow when I originally built it.
=> Fix AA status box buttons

arlo-client/src/components/DataEntry/Ballot.tsx, arlo-client/src/components/DataEntry/BoardTable.tsx, arlo-client/src/components/DataEntry/_mocks.ts, arlo-client/src/components/DataEntry/index.test.tsx, arlo-client/src/components/DataEntry/index.tsx
Depends on #515 
**Testing**
Updated some mocks
**Progress**
Ready
=> Use new /ballots endpoint in audit board flow

arlo-client/src/components/Audit/Setup/Review/ConfirmLaunch.tsx, arlo-client/src/components/Audit/Setup/Review/index.tsx, arlo-client/src/components/Audit/Setup/Review/useConfirmLaunch.tsx
- Added a confirmation dialog for the review and launch stage
- Made launching the audit redirect you to the progress view
**Testing**
- none
**Progress**
- works with manual testing
=> Confirm dialog and redirect for Review and Launch stage

arlo-client/src/components/Audit/Setup/Contests/DropdownCheckboxList.tsx
- adding a 'select all' checkbox for the dropdown.
**Testing**
- none
**Progress**
- works with my manual testing
=> Select all feature for jurisdiction selection

arlo-client/src/components/DataEntry/SignOff.tsx, arlo-client/src/components/DataEntry/index.tsx
- Added a wrapper div inside the pre-existing wrapper div so that the flex doesn't make things go sideways.
**Testing**
- None.
**Progress**
- It looks right to me, and I only edited those two components, but @jonahkagan should check it since he wrote this part of the UI.
=> Signoff and data entry completion styling fix

arlo-client/src/components/Audit/Setup/Review/ConfirmLaunch.tsx, arlo-client/src/components/Audit/Setup/Review/index.tsx
adding x of y jurisdictions have uploaded ballot manifests note to confirmation dialog
**Testing**
-none
**Progress**
- LGTM
=> Adding note to launch confirm dialog

arlo-client/src/components/Atoms/Form/FormButton.tsx, arlo-client/src/components/Audit/Progress/JurisdictionDetail.tsx, arlo-client/src/components/Audit/Progress/index.tsx, arlo-client/src/components/Audit/useJurisdictions.ts
- Adding 'minimal' option to FormButton
- Adding a dialog to the Progress screen that shows details and download link for jurisdictions
**Testing**
- Manual
**Progress**
LGTM! Very pretty
=> Jurisdiction detail dialog

arlo-client/src/components/Audit/Setup/BallotManifest/index.tsx, arlo-client/src/components/Audit/index.tsx, arlo-client/src/components/Audit/useBallotManifest.ts
This one was a bit tricky. Explanation in the code.
**Testing**
Manual testing.
**Progress**
Ready
=> Button to clear ballot manifest

arlo_server/models.py, arlo_server/reports.py, arlo_server/routes.py, tests/routes_tests/test_audit_boards.py, tests/routes_tests/test_reports.py
New endpoints for the audit reports for AAs and JAs.
**Testing**
Added very basic snapshot tests.
**Progress**
Ready
=> Multi-jurisdiction audit reports (AA + JA)

arlo-client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx
Follow up to #529 
**Testing**
Manual test
**Progress**
Ready
=> JA round management - use /ballots endpoint

arlo-client/src/components/MultiJurisdictionAudit/RoundManagement/CreateAuditBoards.tsx, arlo-client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx
Title says it all
Also fixed a bug that I introduced in #532 where we didn't actually load the ballots correctly.
**Testing**
**Progress**
Ready
=> Show JA number of ballots to audit when creating audit boards

arlo-client/src/components/MultiJurisdictionAudit/StatusBox.tsx
=> Fix JA status box message about other jurisdictions

arlo-client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx
The hidden QR code component was messing up the button spacing, so I moved it
to below the buttons where it doesn't get in the way.
**Testing**
**Progress**
Ready
=> JA round management: fix button spacing

arlo-client/src/components/DataEntry/BallotAudit.tsx
simple way to clear a selection
=> allow clearing of a selection

arlo_server/reports.py, tests/routes_tests/test_reports.py
* Reformats audit report so headers are consistent throughout the file
**Testing**
* Updates test in test_reports to work with new format
**Progress**
Ready to roll.
=> Reformats audit report

arlo-client/src/components/MultiJurisdictionAudit/RoundManagement/generateSheets.ts
Off by one error
**Testing**
**Progress**
Ready
=> Fix placeholder/label sheet round number

arlo-client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap, arlo-client/src/components/MultiJurisdictionAudit/index.test.tsx
- Tweaking the tests for MultiJurisdictionAudit marked `AA setup flow`
**Testing**
- Just updating snapshots and tweaking mock values so far
**Progress**
-  lgtm
=> Fixing AA setup flow tests

arlo-client/package.json, arlo-client/src/components/DataEntry/__snapshots__/MemberForm.test.tsx.snap, arlo-client/src/components/DataEntry/__snapshots__/index.test.tsx.snap, arlo-client/src/components/MultiJurisdictionAudit/Setup/Review/index.test.tsx, arlo-client/src/components/MultiJurisdictionAudit/useSetupMenuItems.test.ts, arlo-client/src/components/SingleJurisdictionAudit/CalculateRiskMeasurement.test.tsx, arlo-client/src/test/specs/createAudit.ts, arlo-client/src/test/specs/helpers.ts
Fixing tests broken by a few of my recent changes, as well as remaining test failures.
=> Frontend test fixes

arlo_server/models.py
See commits for changes and reasoning.
=> Cleanup db models

.circleci/config.yml, README.md, arlo_server/models.py, config/__init__.py, config/database.cfg.dev, config/database.cfg.docker, config/database.cfg.example, tests/routes_tests/test_auth.py, tests/routes_tests/test_reports.py, tests/test_app.py
A number of warnings would show at the end of any test runs. This PR has a series of commits that fixes each warning.
=> Fix test warnings

.coveragerc, arlo_server/__init__.py, arlo_server/audit_boards.py, arlo_server/auth.py, arlo_server/errors.py, arlo_server/routes.py, create.py, resetdb.py, tests/conftest.py, tests/routes_tests/test_audit_boards.py, tests/routes_tests/test_auth.py, tests/routes_tests/test_ballot_manifest.py, tests/test_app_upload_jurisdictions_file.py, tests/test_errors.py, tests/util_tests/test_jsonschema.py, util/csv_parse.py
This PR adds test coverage for everything I could easily get to. I didn't try to cover some of the old routes from routes.py. I also avoided the math, binpacking, and background processing.
So not 100% coverage yet.
```
----------- coverage: platform linux, python 3.7.5-final-0 -----------
Name                    Stmts   Miss     Cover   Missing
--------------------------------------------------------
arlo_server/routes.py     383      9    97.65%   616, 618, 661, 664, 687, 700, 717, 849, 879
audit_math/bravo.py       138      2    98.55%   191, 250
audit_math/macro.py        53      5    90.57%   58, 186-192, 247
bgcompute.py               45     10    77.78%   37-38, 54-55, 71-72, 78-80, 84
util/binpacking.py        101     18    82.18%   27, 45, 48-50, 99-110, 136, …
```
=> Server test coverage

tests/audit_math_tests/test_bravo.py, tests/audit_math_tests/test_macro.py, tests/audit_math_tests/test_sampler.py, tests/audit_math_tests/test_sampler_contest.py, tests/conftest.py, tests/routes_tests/test_audit_status.py, tests/routes_tests/test_single_jurisdiction_ballot_list.py, tests/routes_tests/test_superadmin.py, tests/test_app.py, tests/util_tests/test_binpacking.py
Accidentally merged #564 into `coverage-server` instead of `master`
=> Remove unneeded generators (merge to master)

arlo-client/package.json, arlo-client/src/components/MultiJurisdictionAudit/StatusBox/index.test.tsx, arlo-client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx, arlo-client/src/components/MultiJurisdictionAudit/_mocks.ts, arlo-client/src/components/MultiJurisdictionAudit/useRoundsJurisdictionAdmin.ts, arlo-client/src/components/MultiJurisdictionAudit/useSetupMenuItems.test.ts
Increasing test coverage
**Testing**
- Covering all states of the status box and its functions
**Progress**
Done!
Note: Depending on if this or @jonahkagan 's PR with upgrading the libraries gets merged first, one or the other will need to be minorly updated.
=> 100% Coverage of StatusBox

arlo_server/routes.py
This ensures that these endpoints can't be used by an anonymous user to
update a multi-jurisdiction audit.
=> Require anonymous user on single-jurisdiction flow routes

arlo-client/src/components/DataEntry/BallotAudit.tsx, arlo-client/src/components/DataEntry/__snapshots__/Ballot.test.tsx.snap
- Reverting the clear button that was a stopgap fix
**Testing**
- updating snapshot
**Progress**
- should be good
=> Removing clear button from ballot data entry

client/package.json, client/src/__snapshots__/App.test.tsx.snap, client/src/components/MultiJurisdictionAudit/Setup/Contests/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/Setup/Review/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/Setup/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap, client/src/components/SingleJurisdictionAudit/EstimateSampleSize.test.tsx, client/src/components/SingleJurisdictionAudit/EstimateSampleSize.tsx, client/src/components/SingleJurisdictionAudit/__snapshots__/EstimateSampleSize.test.tsx.snap, client/src/components/SingleJurisdictionAudit/__snapshots__/index.test.tsx.snap, client/src/components/SingleJurisdictionAudit/_mocks.ts, client/src/components/SingleJurisdictionAudit/index.test.tsx
- Yey tests!
**Testing**
- Added a test for redirection
- Un-skipped the tests that had been skipped
- Updated the snapshots
**Progress**
Yey!
=> Single Page 100% coverage

.slugignore
The extension changed from .ts to .tsx
=> Fix .slugignore pattern for testUtilities.tsx

client/src/components/MultiJurisdictionAudit/Setup/Review/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/Setup/Review/index.test.tsx, client/src/components/MultiJurisdictionAudit/Setup/Review/index.tsx
- The custom sample size feature got lost in the mix, and now it is added back in again.
**Testing**
- Snapshots updated
**Progress**
- lgtm, but haven't tested it exhaustively.
=> adding custom sample size

client/src/CreateSingleJurisdictionAudit.test.tsx, client/src/CreateSingleJurisdictionAudit.tsx, client/src/__snapshots__/CreateSingleJurisdictionAudit.test.tsx.snap, client/src/components/MultiJurisdictionAudit/useSetupMenuItems.test.ts
- adding tests
**Testing**
- covering the single jurisdiction create audit view
**Progress**
- got stuck trying to implement the new mocking setup. @jonahkagan think you could take a look and see what I'm doing wrong?
=> testing CreateSingleJurisdictionAudit

client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/RoundManagement/index.test.tsx
More tests
**Testing**
Covering RoundManagement
**Progress**
done!
=> RoundManagement coverage

README.md
=> README: update config path

server/config.py
=> Fix default database URL username/password

server/superadmin.py, server/templates/superadmin/organizations.html, server/tests/api/test_superadmin.py
Motivation: clean up the staging database. Could be useful in production someday too
=> Superadmin: add button to delete election

server/api/reports.py
The current report code has a bunch of helper functions that write to a
report stream. If one section was skipped, it resulted in an extra empty
line in between the report sections.
To fix this, I refactored the helpers to return a list of rows to write
(instead of writing them directly), so that the report building parent
function can easily deal with filtering out empty sections and joining
them correctly with new lines.
This is a precursor to adding reports for offline results in #662
=> Reports: refactor to functional style

server/api/jurisdictions.py, server/tests/api/test_jurisdictions.py
We had a previous first cut at jurisdiction status for offline audits which basically said that a jurisdiction hadn't audited any ballots until the round completed.
Now that we have a way to record offline results, we actually do know when a jurisdiction is finished auditing their ballots.
=> Improve jurisdiction status for offline audits

client/src/CreateSingleJurisdictionAudit.test.tsx, client/src/CreateSingleJurisdictionAudit.tsx, client/src/__snapshots__/App.test.tsx.snap, client/src/components/CreateAudit.test.tsx, client/src/components/CreateAudit.tsx, client/src/components/MultiJurisdictionAudit/RoundManagement/useAuditSettingsJurisdictionAdmin.ts, client/src/components/MultiJurisdictionAudit/Setup/Review/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/Setup/Review/_mocks.ts, client/src/components/MultiJurisdictionAudit/Setup/Review/index.tsx, client/src/components/MultiJurisdictionAudit/Setup/Settings/index.test.tsx, client/src/components/MultiJurisdictionAudit/Setup/Settings/index.tsx, client/src/components/MultiJurisdictionAudit/Setup/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/_mocks.ts, client/src/components/MultiJurisdictionAudit/useAuditSettings.ts, client/src/types.ts
Closes #640 
Closes #639 
Closes #638 
**Testing**
- none yet
**Progress**
- Functional, just need to update tests.
=> adding front end support for batch comparison audit creation

client/package.json, client/yarn.lock
=> Chromedriver v84.0.0

server/api/jurisdictions.py, server/tests/api/test_jurisdictions.py
Fixes #691
Audit boards with no ballots assigned shouldn't be expected to sign off
for the jurisdiction to complete a round. This is already implemented
for the logic that checks if the round is complete, but the jurisdiction
status wasn't factoring this change in.
=> Fix audit progress for ABs with no ballots assigned

client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx, server/api/__init__.py, server/api/ballots.py, server/api/batches.py, server/tests/api/test_ballots.py, server/tests/batch_comparison/conftest.py, server/tests/batch_comparison/snapshots/snap_test_batches.py, server/tests/batch_comparison/test_batches.py
Task: #672 
Two endpoints that are needed for the JA for batch audits.
=> JA get batches and batch retrieval list endpoints

server/api/rounds.py
=> cumulative_batch_results: only return batches that have been sampled

server/api/reports.py, server/models.py, server/tests/api/snapshots/snap_test_reports.py, server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py, server/tests/batch_comparison/test_batch_comparison.py, server/tests/snapshots/snap_test_multiple_targeted_contests.py, server/tests/snapshots/snap_test_offline_data_entry.py
=> Batch audit report

.circleci/config.yml, Makefile, Pipfile, Pipfile.lock, mypy.ini, server/util/csv_parse.py
- upgrading to 3.8
**Testing**
- shouldn't affect tests
**Progress**
- yey!
=> using 3.8 instead of 3.7

Makefile
Bandaid for intermittent test failures
=> Lower server test parallelism from 4 to 2

server/auth/lib.py
They were on the wrong line and weren't applying.
=> Fix "no cover" comments

client/package.json, client/src/__snapshots__/App.test.tsx.snap, client/src/components/HomeScreen.test.tsx, client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx, client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/index.test.tsx, client/src/components/MultiJurisdictionAudit/index.tsx, client/src/components/MultiJurisdictionAudit/timers.test.tsx, client/src/components/utilities.ts, client/yarn.lock
Closes #696 
- Adds a `useInterval` custom hook for managing `setInterval` and `clearInterval` in React
**Testing**
- none yet
**Progress**
- It polls every 5 minutes successfully and without any problems, very clean.
- It displays in a very human friendly fashion how long it's been since the last refresh
- Need to test it all
=> Adding auto-refresh to the progress view

client/src/components/HomeScreen.test.tsx, client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/index.test.tsx, client/src/components/MultiJurisdictionAudit/index.tsx, client/src/components/MultiJurisdictionAudit/timers.test.tsx
- fixes the sidebar, since it needs to refresh after everything is mounted so it will accurately reflect the proper state. This refresh got removed in another PR, this just puts it back in.
**Testing**
- updated
**Progress**
- ready to go
=> Refresh onmount

client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx
- limiting check for tallies uploads to jurisdictions in the contest universe
**Testing**
- No changes necessary
**Progress**
- Tested manually, it works now
=> Fixing sample size check

server/api/__init__.py, server/api/cvrs.py, server/bgcompute.py, server/database.py, server/migrations/env.py, server/migrations/versions/7f86511c05e0_cvrs.py, server/models.py, server/tests/ballot_comparison/snapshots/snap_test_cvrs.py, server/tests/ballot_comparison/test_cvrs.py
Task: #757 
Barebones CVR uploading, parsing, and storing in the db. No real error handling or testing or validation or anything. Quick and dirty.
But it runs fast! Parsed and stored a 900k row CVR in 44 seconds.
=> Basic CVR upload

client/package.json, client/yarn.lock
=> chromedriver v86

server/auth/routes.py, server/tests/test_auth.py
=> Not being logged in is not a crime.

server/api/cvrs.py, server/api/rounds.py, server/api/sample_sizes.py, server/audit_math/supersimple.py, server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py, server/tests/ballot_comparison/snapshots/snap_test_cvrs.py, server/tests/ballot_comparison/test_ballot_comparison.py, server/tests/ballot_comparison/test_cvrs.py
Redoing votingworks/arlo#785 because I merged it too early
=> Pass discrepancies into sample size calculator (redo)

server/api/cvrs.py, server/tests/ballot_comparison/snapshots/snap_test_cvrs.py, server/tests/ballot_comparison/test_ballot_comparison_manifests.py, server/tests/ballot_comparison/test_cvrs.py
Task: #796 
It's an optional column, so we just ignore it.
=> Parse CVR files with CountingGroup column

client/package.json, client/src/components/DataEntry/Ballot.tsx, client/src/components/DataEntry/BoardTable.tsx, client/src/components/DataEntry/__snapshots__/BoardTable.test.tsx.snap, client/src/components/DataEntry/__snapshots__/index.test.tsx.snap
- moving imprinted ID to last place
**Testing**
- none yet
**Progress**
- moved the imprinted ID, adjusted order of columns
=> Data entry tweaks

client/src/components/HomeScreen.tsx
- Just what the title says
**Testing**
- No changes needed.
**Progress**
- Done!
=> Sorting audits alphabetically

server/api/rounds.py, server/api/routes.py, server/api/sample_sizes.py, server/audit_math/ballot_polling.py, server/audit_math/bravo.py, server/models.py
Creates a ballot_polling module that will eventually house both BRAVO and Minerva (and maybe others). 
**Testing**
N/A
**Progress**
Ready.
=> Alters ballot polling interface in anticipation of minerva math

client/src/components/MultiJurisdictionAudit/AASetup/Participants/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/AASetup/Participants/index.tsx, client/src/components/MultiJurisdictionAudit/AASetup/__snapshots__/index.test.tsx.snap
Closes #821 
**Testing**
- snapshots updated
**Progress**
done
=> Adding headers to ballot comparison audit screen

client/src/__snapshots__/App.test.tsx.snap, client/src/components/Atoms/Wrapper.tsx, client/src/components/DataEntry/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/index.tsx
Closes #823 
**Testing**
Updated snapshots
**Progress**
Done
@jonahkagan is there a reason we don't just have bottom padding on the `Wrapper` component by default?
=> Adding padding below ja screens

server/api/standardized_contests.py, server/models.py, server/tests/ballot_comparison/test_standardized_contests.py
Task: #794 
Also add delete-orphan relationship property for all files to make sure
they get properly deleted when their parent is deleted.
=> Finish tests for standardized contests file

server/api/rounds.py, server/api/sample_sizes.py, server/audit_math/ballot_polling.py, server/audit_math/bravo.py, server/audit_math/minerva.py, server/models.py, server/tests/api/snapshots/snap_test_sample_sizes.py, server/tests/audit_math/test_bravo.py
Reconfigures the data passed to the math to be friendlier to Minerva. Introduces a new DB query to get results by round, not just cumulatively, and updates BRAVO and applicable files. 
**Testing**
N/A
**Progress**
Ready
=> Minerva changes

server/api/sample_sizes.py, server/audit_math/supersimple.py, server/tests/audit_math/test_supersimple.py, server/tests/ballot_comparison/test_ballot_comparison.py
Fix for ballot comparison audits.
=> Sample sizes endpoint should always return round 1 sample sizes

client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/generateSheets.test.tsx.snap, client/src/components/MultiJurisdictionAudit/RoundManagement/generateSheets.ts
Closes #826 
Just added an extra line with a clickable direct link. Straightforward and simple.
**Testing**
- snapshots
**Progress**
done
=> Adding clickable link to pdf for AB credentials

server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py, server/tests/ballot_comparison/test_ballot_comparison.py
Task: #741 
It was kind of confusing/unreliable trying to programmatically decide
how to audit each ballot. Instead, we write in the desired audit results
by hand.
This will set us up for the next few changes that might change the
results of this test.
=> Improve ballot comparison integration test

client/public/sample_manifest_BC.csv, client/src/components/MultiJurisdictionAudit/index.tsx
Closes #822 
**Testing**
- None necessary
**Progress**
- Done
=> Swapping out sample manifest file for BC

server/api/reports.py, server/api/rounds.py, server/audit_math/supersimple.py, server/tests/audit_math/test_bravo.py, server/tests/audit_math/test_supersimple.py, server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py
=> Added multiplicty to supersimple

server/api/rounds.py, server/api/sample_sizes.py, server/audit_math/ballot_polling.py, server/audit_math/minerva.py
Passes round sizes to minerva.py.
**Testing**
N/A
**Progress**
Ready.
=> passing round sizes to math module

client/src/components/DataEntry/Ballot.test.tsx, client/src/components/DataEntry/BallotAudit.tsx, client/src/components/DataEntry/BallotReview.tsx, client/src/components/DataEntry/__snapshots__/Ballot.test.tsx.snap, client/src/components/DataEntry/__snapshots__/index.test.tsx.snap, client/src/components/DataEntry/index.test.tsx, client/src/types.ts
Closes #843 
Closes #846 
Is the front end for #853 
**Testing**
- Updated interactions with the changed buttons
**Progress**
- Done!
=> Ballot auditing options updates

client/package.json, client/src/index.tsx, client/yarn.lock
Intializes error capture by Sentry when REACT_APP_SENTRY_DSN env
variable is set.
=> Sentry frontend

server/tests/audit_math/test_bravo.py
Adds a testcase to verify that really large audits don't cause any math problems. 
**Testing**
Adds the current GA presidential race to see if it crashes. 
**Progress**
Ready.
=> Added test for GA-sized contest

server/tests/util/test_jurisdiction_bulk_update.py, server/util/jurisdiction_bulk_update.py
needs a regression test, adding it shortly.
=> fix the deletion query in bulk upload of jurisdiction admins

client/package.json, client/src/components/Atoms/Table.tsx, client/src/components/DataEntry/__snapshots__/BoardTable.test.tsx.snap, client/src/components/DataEntry/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/Progress/index.test.tsx, client/src/components/MultiJurisdictionAudit/Progress/index.tsx, client/src/components/MultiJurisdictionAudit/useJurisdictions.ts, server/api/jurisdictions.py, server/tests/test_sample_all_ballots.py
- When all ballots sampled, add a new column to the table with the
number of batches audited
- Rename all the columns to be more clear if they are ballots or batches
=> Show batches audited in Jurisdiction Progress screen

client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx
=> Offline batch results sticky headers

client/src/__snapshots__/App.test.tsx.snap, client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx, client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/index.test.tsx.snap, client/src/utils/array.test.ts, client/src/utils/array.ts
=> Use a modal to add/edit batches in offline batch results form

server/api/cvrs.py, server/api/standardized_contests.py, server/tests/ballot_comparison/snapshots/snap_test_cvrs.py, server/tests/ballot_comparison/test_cvrs.py, server/tests/ballot_comparison/test_standardized_contests.py
Strips newline characters out of CVRs and standardized contest files.
**Testing**
Adds testing of files with newlines in them. 
**Progress**
Tests pass?
=> Strips newline characters from CVRs and standardized contests

client/package.json, client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx, client/src/components/MultiJurisdictionAudit/RoundManagement/useOfflineBatchResults.ts, server/api/offline_batch_results.py, server/tests/snapshots/snap_test_sample_all_ballots.py, server/tests/test_sample_all_ballots.py
backend ready, frontend needed.
=> Add per-batch-results API for parallel data entry

client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx, server/api/offline_batch_results.py, server/tests/test_sample_all_ballots.py
Also add batch name to edit modal title
=> Fix: can't edit batch name to existing batch name

client/package.json, client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx
=> Offline batch results total rows

scripts/end-round.py, server/api/offline_batch_results.py, server/tests/test_sample_all_ballots.py
Add a script to do it instead.
=> Don't end round automatically after last jurisdiction finalizes

client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx, scripts/end-round.py, server/api/reports.py, server/tests/snapshots/snap_test_sample_all_ballots.py, server/tests/test_sample_all_ballots.py
For both AAs and JAs. Also reenable the JA audit report button.
=> Audit report: add batch results

client/src/__snapshots__/App.test.tsx.snap, client/src/components/Atoms/Form/_helpers.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Participants/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/AASetup/Review/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/AASetup/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/CSVForm/index.tsx, client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/StatusBox/index.test.tsx, client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx
- Colors the callout for the status box green when all the needed files are successfully uploaded.
**Testing**
- I'm looking for the test that needs updating for this, since it didn't show any failing after the change.
**Progress**
- It works, just investigating tests.
=> Make JA upload success more obvious

server/api/reports.py, server/tests/api/snapshots/snap_test_reports.py, server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py, server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison_manifests.py, server/tests/batch_comparison/snapshots/snap_test_batch_comparison.py, server/tests/snapshots/snap_test_multi_winner_contest.py, server/tests/snapshots/snap_test_multiple_targeted_contests.py, server/tests/snapshots/snap_test_offline_data_entry.py, server/tests/snapshots/snap_test_sample_all_ballots.py
- Add organization name to election info section
- Order offline batch results by batch name
- Display p-value of 0 as 0, not <0.0000000001
=> Audit report tweaks

client/package.json, client/src/components/MultiJurisdictionAudit/CSVForm/index.tsx, client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap
- Removing the temp fix from before there was a permanent fix
**Testing**
- snapshots updated
**Progress**
- good to go
=> fixing timezone on CSVForm

server/app.py
=> Increase session timeout to 5 hours

server/api/ballots.py, server/models.py
Load all joined relationships in the original database query for the ballots.
=> Optimize /ballots endpoint

server/api/jurisdictions.py
=> Optimize /jurisdictions endpoint

server/tests/util/test_jurisdiction_bulk_update.py
Saw a test run fail on CI because of this.
=> Change a few JA emails in test to not clash

server/tests/ballot_polling/snapshots/snap_test_minerva_ballot_polling.py, server/tests/ballot_polling/test_minerva_ballot_polling.py
Fixes minerva test with inconsistent sample sizes. 
**Testing**
Alters test. 
**Progress**
Ready.
=> Fixes minerva test to stop failure.

client/src/App.test.tsx, client/src/__snapshots__/App.test.tsx.snap, client/src/components/MultiJurisdictionAudit/useSetupMenuItems.test.ts
- More test fixes
**Testing**
- Testing the login for ABs
**Progress**
- I'll be adding to this a bit before merging I think, but still keeping to smaller batches of updates.
=> More test fixes

client/src/components/MultiJurisdictionAudit/RoundManagement/OfflineBatchRoundDataEntry.tsx
=> Hide 'Advance' batch type

.circleci/config.yml
Scales down CircleCI resource class. 
**Testing**
N?A
**Progress**
Ready.
=> Moving back down to medium

scripts/clear-audit-boards.py
=> Script to clear audit boards for a jurisdiction

client/src/components/DataEntry/Ballot.test.tsx, client/src/components/DataEntry/BallotReview.tsx
Closes #969 
- Stops double submission errors on DataEntry ballot audit review
**Testing**
- Added regression test that successfully fails without this fix and passes with it.
**Progress**
- Done!
=> Adding Formik to BallotReview

client/src/components/DataEntry/MemberForm.tsx, client/src/components/DataEntry/SignOff.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Contests/ContestForm.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Contests/ContestSelect.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Settings/index.tsx, client/src/components/MultiJurisdictionAudit/RoundManagement/BatchRoundDataEntry.tsx, client/src/components/MultiJurisdictionAudit/RoundManagement/CreateAuditBoards.tsx, client/src/components/MultiJurisdictionAudit/RoundManagement/RoundDataEntry.tsx
- Using Formik's `isSubmitting` to prevent double submissions.
=> Preventing double submissions

client/src/__snapshots__/App.test.tsx.snap, client/src/components/DataEntry/BoardTable.tsx, client/src/components/DataEntry/__snapshots__/BoardTable.test.tsx.snap, client/src/components/DataEntry/__snapshots__/index.test.tsx.snap
- Adding left margin to re audit button on data entry table for audit boards
Closes #1015 
**Testing**
- snapshots updated
**Progress**
- done!
=> Adding margin to re-audit button

server/app.py, server/config.py
- Set default log level to INFO
- Standardize logger names (server.app -> arlo, root -> arlo.config)
- Standardize logging of config vars
=> Logging cleanup

server/api/audit_boards.py
Task: #1027 
Previously, we loaded all the sampled ballots into memory at once, which
was memory-intensive and led to high water marking.
With this new approach, we count the sampled ballots per batch in the
database, and use bulk update operations to assign the audit boards, so
we never need to load the ballots into memory.
=> Optimize assigning ballots to audit boards

Pipfile, Pipfile.lock, Procfile
Task: #1025 
Allows concurrent request processing (unlike the Flask built-in dev server).
=> Run server with gunicorn

Procfile
Saves memory by loading application code before forking processes. https://devcenter.heroku.com/articles/python-gunicorn#app-preloading
=> Add gunicorn preload option

client/src/components/MultiJurisdictionAudit/AASetup/Review/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx, client/src/components/MultiJurisdictionAudit/useSetupMenuItems/_mocks/index.ts
- Matching the back to the front
**Testing**
- Missing unit tests written
**Progress**
- Done
=> Adding frontend validation for custom sample sizes

server/api/audit_boards.py
Manually tested the logging works
=> Check for ballots not getting assigned to audit boards

client/public/sample_manifest_hybrid.csv, client/src/__snapshots__/App.test.tsx.snap, client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/index.tsx
Closes #1055 
Includes hybrid manifest from #1053 
**Testing**
- updated snapshots
**Progress**
- Done, if it looks right for @mcchilders !
=> Hybrid ja upload

client/src/components/MultiJurisdictionAudit/AASetup/Contests/HybridContestForm.test.tsx
**Testing**
- Adding a couple more unit tests
**Progress**
- should be good to go
=> More Hybrid tests

client/src/components/MultiJurisdictionAudit/_mocks.ts, client/src/components/MultiJurisdictionAudit/index.test.tsx
**Testing**
- testing deletion of CSVs
**Notes**
This is for coverage, going through and cleaning up missing code branches
=> Misc unit tests

client/src/components/MultiJurisdictionAudit/AASetup/Participants/_mocks.ts, client/src/components/MultiJurisdictionAudit/_mocks.ts, client/src/components/MultiJurisdictionAudit/index.test.tsx, client/src/components/MultiJurisdictionAudit/useSetupMenuItems/_mocks/index.ts, client/src/components/MultiJurisdictionAudit/useSetupMenuItems/_mocks/test_error_jurisdiction.csv
=> Adding more tests

server/api/rounds.py, server/tests/hybrid/test_hybrid.py
Task: #1054
Draw two samples - one for CVR ballots and one for non-CVR ballots.
=> Hybrid: draw sample

server/api/reports.py, server/tests/hybrid/snapshots/snap_test_hybrid.py
Task: #1050 
Add CVR/non-CVR vote counts and total ballots cast to contest info.
=> Hybrid: update audit report

client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Review/useSampleSizes.ts
=> Hybrid: show CVR/non-CVR sample sizes

server/api/standardized_contests.py, server/tests/ballot_comparison/test_standardized_contests.py
=> Standardized contests: parse "all" without case-sensitivity

client/src/components/MultiJurisdictionAudit/StatusBox/index.test.tsx, client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx, client/src/components/MultiJurisdictionAudit/useSetupMenuItems/_mocks/index.ts, client/src/components/SupportTools/SupportTools.tsx, client/src/components/SupportTools/support-api.tsx, server/api/ballots.py, server/api/rounds.py, server/tests/hybrid/snapshots/snap_test_hybrid.py, server/tests/hybrid/test_hybrid.py
- JA status box
- Support tools audit type tag
- ballot retrieval list
- round 2 sample size selection
=> Hybrid: cleanup all places we check audit type

server/api/ballot_manifest.py, server/api/sample_sizes.py, server/tests/hybrid/test_hybrid.py
Task: #1106 
All of the validation will return an error on the Review screen from the sample sizes endpoint.
=> Hybrid: add validation for manifests/CVRs/contest metadata

server/audit_math/macro.py, server/tests/audit_math/snapshots/snap_test_sampler.py, server/tests/audit_math/test_macro.py
Adds new tests to macro to get 100% coverage
**Testing**
New tests for corner cases in MACRO like recounts and worst-case scenarios. 
**Progress**
Ready
=> Adds new tests to macro to get 100% coverage

server/api/ballot_manifest.py, server/tests/ballot_comparison/test_cvrs.py
Task: #1124 
Since the CVR file depends on the batches created from the manifest, if the manifest changes, we need to reprocess the CVR file.
=> Reprocess CVR file when ballot manifest reuploaded

client/cypress/end-to-end/ballot-comparison-failure-cases.spec.js, client/cypress/end-to-end/ballot-comparison-happy-path.spec.js, client/cypress/end-to-end/ballot-polling-happy-path.spec.js, client/cypress/end-to-end/batch-comparison-failure-cases.spec.js, client/cypress/end-to-end/batch-comparison-happy-path.spec.js
Since my editor is configured to always autoformat on save, I figured it would be better to just go ahead and autoformat these. That way, when I make changes, it's easy to see what's changed (instead of also getting a bunch of formatting changes).
=> Autoformat Cypress tests

server/audit_math/suite.py, server/tests/audit_math/test_suite.py
Adds handling for a corner case where one stratum gets recounted but the other doesn't. 
**Testing**
Adds new test for this corner case.
**Progress**
Ready.
=> Suite fixes

client/src/__snapshots__/App.test.tsx.snap, client/src/components/MultiJurisdictionAudit/StatusBox/index.test.tsx, client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx, client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/index.tsx
Closes #1116 
**Testing**
- Test that it shows up in the status bars
**Progress**
- Ready to go!
=> Adding audit name to status bar

.circleci/config.yml, client/.gitignore
- So we can see more about what is failing when it happens on CI
(Based on this: https://circleci.com/docs/2.0/artifacts/?section=pipelines)
=> Adding support for saving cy screencaps as artifacts

client/cypress/end-to-end/ballot-comparison-failure-cases.spec.js, client/cypress/end-to-end/batch-comparison-failure-cases.spec.js, client/src/components/DataEntry/SignOff.test.tsx, client/src/components/DataEntry/SignOff.tsx, client/src/components/DataEntry/__snapshots__/SignOff.test.tsx.snap, client/src/components/HomeScreen.test.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Participants/index.test.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Settings/index.test.tsx, client/src/components/MultiJurisdictionAudit/index.test.tsx
**Testing**
- Filling in the gaps
=> Adding tests

server/api/rounds.py
This was making the audit report slow. It's also used in sample size/risk measurement calculations, so should see some benefit there as well.
=> Optimize ballot interpretations query

client/src/__snapshots__/App.test.tsx.snap, client/src/components/DataEntry/BoardTable.tsx, client/src/components/DataEntry/__snapshots__/BoardTable.test.tsx.snap, client/src/components/DataEntry/__snapshots__/index.test.tsx.snap
Closes #1162 
**Testing**
**Progress**
@mcchilders is this what you're thinking?
=> Making ballot audit status more clear

client/src/__snapshots__/App.test.tsx.snap, client/src/components/Atoms/Form/FormField.tsx, client/src/components/Atoms/Form/__snapshots__/FormField.test.tsx.snap, client/src/components/DataEntry/__snapshots__/Ballot.test.tsx.snap, client/src/components/DataEntry/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/AASetup/Contests/ContestForm.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Contests/__snapshots__/HybridContestForm.test.tsx.snap, client/src/components/MultiJurisdictionAudit/AASetup/Contests/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/AASetup/Contests/_mocks.ts, client/src/components/MultiJurisdictionAudit/AASetup/Contests/index.test.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Contests/schema.ts, client/src/components/MultiJurisdictionAudit/AASetup/Review/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/AASetup/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/BatchRoundDataEntry.test.tsx.snap, client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/RoundDataEntry.test.tsx.snap, client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap, server/api/contests.py, server/tests/api/test_contests.py, server/tests/ballot_comparison/test_standardized_contests.py
Backend:
- Must not be empty
- Must contain valid jurisdiction ids
Frontend:
- Must select jurisdictions to save contests
=> Validate contest universe

client/cypress/end-to-end/ballot-comparison.spec.js, client/cypress/end-to-end/ballot-polling.spec.js, client/cypress/end-to-end/batch-comparison.spec.js, client/cypress/end-to-end/offline-batch-data-entry-tests.spec.js, client/src/components/HomeScreen.test.tsx, client/src/components/HomeScreen.tsx, client/src/components/MultiJurisdictionAudit/_mocks.ts, client/src/components/__snapshots__/HomeScreen.test.tsx.snap
Closes #1011 
**Testing**
- Added new unit test to verify this works
- Updated cypress flows
**Progress**
Should be good to go if it works
=> Redirecting JA to audit screen if only one audit

server/migrations/versions/141edd274627_fix_null_round_contest_sample_size.py
=> Fix RoundContest.sample_size migration

client/src/components/MultiJurisdictionAudit/AASetup/Review/index.test.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Review/index.tsx, server/api/rounds.py, server/tests/hybrid/test_hybrid.py
=> Hybrid: custom sample size

client/src/components/Atoms/Confirm.test.tsx, client/src/components/Atoms/Confirm.tsx, client/src/components/Atoms/__snapshots__/Confirm.test.tsx.snap
**Testing**
- Adding unit tests for the Confirm component
**Progress**
- Should be almost done, looking for a way to avoid using `any`, and I'm not sure if the snapshots are working right.
=> Confirm tests

client/src/components/MultiJurisdictionAudit/RoundManagement/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/RoundManagement/index.tsx
=> Don't show placeholder/label buttons for batch audits

server/activity_log/activity_log.py, server/activity_log/slack_worker.py, server/api/audit_boards.py, server/api/ballot_manifest.py, server/api/batch_tallies.py, server/api/batches.py, server/api/cvrs.py, server/api/offline_results.py, server/tests/snapshots/snap_test_slack_worker.py, server/tests/test_slack_worker.py
Task: #1208 
Add activity log notifications for jurisdiction level events.
=> Jurisdiction activity notifications

server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py, server/tests/ballot_comparison/test_ballot_comparison.py, server/tests/ballot_comparison/test_cvrs.py, server/tests/batch_comparison/test_batch_tallies.py, server/tests/util/test_csv_parse.py, server/util/csv_parse.py
Task: #1212 
- Check for the words total(s) or subtotal(s) anywhere in the cell
- Check if the values in a column sum up to the value in the last row in the column
=> csv_parse: improve total row detection

server/activity_log/slack_worker.py, server/tests/test_slack_worker.py
Need to come back in a later PR and figure out why this error didn't cause an alert.
=> slack_worker: fix error when user_type is None

app.json, poetry.lock, pyproject.toml
We have to add a specific community buildpack.
=> Build Heroku app with poetry

server/app.py, server/sentry.py, server/tests/test_auth.py
=> Add user/election/org context to Sentry errors

client/src/components/Atoms/Confirm.tsx, client/src/components/SupportTools/SupportTools.test.tsx, client/src/components/SupportTools/SupportTools.tsx, client/src/components/SupportTools/support-api.tsx, server/api/support.py, server/models.py, server/tests/api/test_support.py
Task: #1260 
Only works if the org has no audits that haven't been deleted.
=> Support tools: button to delete organization

client/src/components/SupportTools/SupportTools.test.tsx, client/src/components/SupportTools/SupportTools.tsx, client/src/components/SupportTools/support-api.tsx, client/src/components/utilities.ts, server/api/support.py, server/tests/api/test_support.py, server/tests/helpers.py
=> Support tools: rename organization button

client/cypress/end-to-end/ballot-polling.spec.js, client/src/App.tsx, client/src/__snapshots__/App.test.tsx.snap, client/src/components/Atoms/Table.tsx, client/src/components/Header.test.tsx, client/src/components/Header.tsx, client/src/components/HomeScreen.test.tsx, client/src/components/MultiJurisdictionAudit/ActivityLog.test.tsx, client/src/components/MultiJurisdictionAudit/ActivityLog.tsx, client/src/components/MultiJurisdictionAudit/__snapshots__/ActivityLog.test.tsx.snap, client/src/components/MultiJurisdictionAudit/index.tsx, client/src/components/SupportTools/SupportTools.test.tsx, client/src/components/SupportTools/SupportTools.tsx, client/src/components/SupportTools/support-api.tsx, server/api/__init__.py, server/api/activity.py, server/models.py, server/tests/api/test_activity.py
=> Activity log for audit admins

client/src/components/MultiJurisdictionAudit/ActivityLog.test.tsx, client/src/components/MultiJurisdictionAudit/ActivityLog.tsx, client/src/components/MultiJurisdictionAudit/__snapshots__/ActivityLog.test.tsx.snap, server/activity_log/activity_log.py, server/activity_log/slack_worker.py, server/auth/routes.py, server/tests/api/test_activity.py
=> Jurisdiction admin login activity logs

client/src/App.tsx
Needs to be inside the provider
=> Fix react-query debugger

client/package.json
Maybe this will fix random timeout errors.
=> Increase jest timeout on CI

client/cypress/end-to-end/ballot-comparison.spec.js, client/cypress/end-to-end/ballot-polling.spec.js, client/cypress/end-to-end/batch-comparison.spec.js, client/cypress/end-to-end/offline-batch-data-entry-tests.spec.js, client/src/components/Atoms/AsyncButton.tsx, client/src/components/Atoms/Confirm.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Participants/index.test.tsx, client/src/components/MultiJurisdictionAudit/CSVForm/index.tsx, client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/index.test.tsx, client/src/components/utilities.ts
- Use an AsyncButton to get a spinner on the Delete button
- Change success text from "Upload successfully completed" to "Uploaded"
=> CSV form UX tweaks

client/package.json, client/src/__snapshots__/App.test.tsx.snap, client/src/components/MultiJurisdictionAudit/AASetup/Participants/index.test.tsx, client/src/components/MultiJurisdictionAudit/AASetup/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/CSVForm/index.tsx, client/src/components/MultiJurisdictionAudit/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/_mocks.ts, client/src/components/MultiJurisdictionAudit/index.test.tsx, client/src/components/MultiJurisdictionAudit/useCSV.ts, client/src/components/MultiJurisdictionAudit/useSetupMenuItems/_mocks/index.ts, client/src/components/__snapshots__/HomeScreen.test.tsx.snap, client/src/components/testUtilities.tsx, client/src/components/utilities.ts, client/yarn.lock
Show a progress bar during large CVR file uploads (> 1MB). To do this, we have to use `axios` (which uses XHR under the hood), since `fetch` doesn't support this feature.
https://user-images.githubusercontent.com/530106/132766937-b1b706c6-fb6f-43bf-8a59-208cef8084cb.mov
=> CVR upload progress

server/activity_log/activity_log.py, server/api/ballot_manifest.py, server/api/batch_tallies.py, server/api/cvrs.py, server/tests/api/test_activity.py
Otherwise, on failure, the activity would get rolled back along with the other changes from the file upload task.
=> Record file upload activity in separate session

client/package.json, client/src/components/DataEntry/Ballot.test.tsx, client/src/components/DataEntry/index.test.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Settings/index.test.tsx, client/src/components/MultiJurisdictionAudit/Progress/index.test.tsx, client/src/components/MultiJurisdictionAudit/RoundManagement/generateSheets.test.tsx
That way our default timeout that is larger can take effect.
=> Remove manual jest timeouts

README.md
Small self explanatory typo fix in the README
=> Fixed funny typo

.circleci/config.yml, README.md, client/run-cypress-tests.sh, poetry.lock, pyproject.toml, run-dev.sh
- Run a local nOAuth server with Cypress tests to see if it makes them less flaky
- Also run a local nOAuth server alongside the dev server to simplify configuring Arlo
=> Run local nOAuth server

server/app.py, server/config.py, server/main.py
- Standardize how we load env vars
- Make sure we raise an exception for all missing required env vars
=> Clean up config.py

client/src/components/DataEntry/Ballot.tsx, client/src/components/DataEntry/BoardTable.tsx, client/src/components/DataEntry/__snapshots__/Ballot.test.tsx.snap, client/src/components/DataEntry/__snapshots__/BoardTable.test.tsx.snap, client/src/components/DataEntry/__snapshots__/index.test.tsx.snap
Closes #1319 
**Testing**
- Snapshots updated
**Progress**
=> Fixing headers for DataEntry

README.md, server/auth/routes.py, server/config.py, server/tests/test_auth.py
=> Allow multiple Support User domains

server/tests/ballot_polling/snapshots/snap_test_ballot_polling.py, server/tests/ballot_polling/test_ballot_polling.py
Order the sampled ballot draws by ticket number so they are consistent between test runs.
=> Fix flaky test

Makefile
Fixes nodejs and poetry install process to work correctly on new Ubuntu installs
=> Fix makefile to work on ubuntu

client/src/components/MultiJurisdictionAudit/Progress/ProgressMap.tsx, client/src/components/MultiJurisdictionAudit/Progress/index.test.tsx, client/src/components/MultiJurisdictionAudit/Progress/index.tsx, client/src/components/MultiJurisdictionAudit/useJurisdictions.ts, server/migrations/versions/f400f19f7a35_file_background_task.py
- A couple of the classes were incorrect
- We were missing one state for when file have started but are not complete yet
=> Fix jurisdiction progress status text and colors

client/cypress/end-to-end/ballot-polling.spec.js, server/api/elections.py, server/tests/api/test_election_settings.py, server/tests/api/test_elections.py, server/tests/api/test_support.py
=> Default ballot polling audits to online data entry

server/config.py
There were some env vars that were being configured incorrectly due to lax type checking. This changes all env vars(including default values) to strings that must be parsed explicitly.
=> Standardize env var types

client/src/components/DataEntry/Ballot.test.tsx, client/src/components/DataEntry/BoardTable.test.tsx, client/src/components/HomeScreen.test.tsx, client/src/components/MultiJurisdictionAudit/AASetup/Participants/index.test.tsx, client/src/components/MultiJurisdictionAudit/AASetup/__snapshots__/index.test.tsx.snap, client/src/components/MultiJurisdictionAudit/AASetup/index.test.tsx, client/src/components/MultiJurisdictionAudit/Progress/index.test.tsx, client/src/components/MultiJurisdictionAudit/RoundManagement/FullHandTallyDataEntry.test.tsx, client/src/components/MultiJurisdictionAudit/useSetupMenuItems/_mocks/index.ts
Some test tweaks, and an additional test.
=> Adjusting awaits on tests

client/src/components/MultiJurisdictionAudit/AASetup/Participants/index.test.tsx, client/src/components/MultiJurisdictionAudit/index.test.tsx, client/src/components/MultiJurisdictionAudit/useSetupMenuItems/_mocks/index.ts
=> Adding tests for error displays on file uploads

client/cypress/end-to-end/ballot-comparison.spec.js
Documentation and one tweak to correct a piece of the end to end test
=> Clarify cypress comments

.gitmodules, Makefile
Adds an arlo-extra-tests submodule to hold other Arlo test vectors that are too slow for CI. 
**Testing**
For now, a bunch of other RAIRE tests. 
**Progress**
=> Extra tests

package.json, yarn.lock
Upgrades Husky to address Dependabot complaints. 
**Testing**
N/A
**Progress**
Ready.
=> Upgrading husky

server/api/cvrs.py, server/tests/ballot_comparison/test_cvrs.py
Make it less repetitive and easier to read
=> Change required column error message

client/src/components/MultiJurisdictionAudit/AASetup/Participants/index.tsx, client/src/components/MultiJurisdictionAudit/CSVForm/index.tsx, client/src/components/MultiJurisdictionAudit/Progress/JurisdictionDetail.tsx, client/src/components/MultiJurisdictionAudit/index.test.tsx, client/src/components/MultiJurisdictionAudit/index.tsx, client/src/components/MultiJurisdictionAudit/useCSV.ts, client/src/components/testUtilities.tsx, server/api/cvrs.py, server/migrations/versions/dd3f3330aee2_cvrfiletype_ess.py, server/models.py, server/tests/ballot_comparison/snapshots/snap_test_cvrs.py, server/tests/ballot_comparison/test_cvrs.py, server/util/csv_parse.py, server/util/file.py
Task: #1249 
- Adds an ES&S CVR file type (to the database and frontend)
- Updates the frontend to allow multiple file selection when uploading ES&S CVRs
- Updates the backend to support multi-file uploads by zipping them
- Parses ES&S CVRs
=> ES&S CVR parsing

server/api/cvrs.py, server/tests/ballot_comparison/snapshots/snap_test_cvrs.py, server/tests/ballot_comparison/test_cvrs.py
=> Dominion CVRs: fall back to UniqueVotingIdentifier if no ImprintedId

server/tests/api/test_support.py, server/util/csv_parse.py, server/util/jsonschema.py
=> Support Tools: validate audit admin email address when creating

server/api/cvrs.py, server/tests/ballot_comparison/snapshots/snap_test_ballot_comparison.py, server/tests/ballot_comparison/test_ballot_comparison.py
That way, there's a deterministic order for tests.
=> Sort unioned CVR choice names

Makefile, README.md, run-dev.sh, server/config.py
- Use Ubuntu 20
- Set default values for all required env vars
- Remove some outdated info from README
=> Update setup instructions and config

server/tests/util/test_file_storage.py, server/util/file.py
Messed this up and also messed up my manual testing that should have caught it.
=> Fix S3 delete_object call

docs/architecture.md
Adds architecture diagrams to the docs directory.
=> Architecture diagrams

client/package.json, client/src/components/SupportTools/SupportTools.test.tsx, client/src/components/SupportTools/support-api.tsx, client/yarn.lock
Needed some of the changes for upcoming work. I had to modify a couple small things to get the existing tests to pass.
=> react-query v3.39.0

server/tests/util/test_csv_parse.py, server/util/csv_parse.py
If we incorrectly detect the encoding of a CSV and only find out deep into the file parsing, we should simply replace the undecodable chararacters we find rather than crashing, since we already got so far it's probably just a few characters.
=> csv_parse: Replace undecodable chararacters

client/package.json, client/src/App.tsx, client/src/components/Atoms/Confirm.test.tsx, client/src/components/AuditAdmin/Progress/JurisdictionDetail.test.tsx, client/src/components/AuditAdmin/Setup/Contests/Contests.test.tsx, client/src/components/AuditAdmin/Setup/Review/Review.test.tsx, client/src/components/AuditAdmin/Setup/Review/Review.tsx, client/src/components/AuditBoard/AuditBoardView.test.tsx, client/src/components/AuditBoard/Ballot.test.tsx, client/src/components/HomeScreen.test.tsx, client/src/components/JurisdictionAdmin/BatchRoundDataEntry.test.tsx, client/src/components/JurisdictionAdmin/FullHandTallyDataEntry.test.tsx, client/src/components/JurisdictionAdmin/FullHandTallyDataEntry.tsx, client/src/components/JurisdictionAdmin/generateSheets.test.tsx, client/src/components/SupportTools/SupportTools.test.tsx, client/src/components/testUtilities.tsx, client/src/components/useCSV.ts, client/src/components/useFileUpload.ts, client/src/components/utilities.ts, client/src/utils/array.test.ts, client/src/utils/array.ts, client/yarn.lock
This enables support for Typescript optional chaining, and is the smallest upgrade that does so.
There were a bunch of automatic formatting changes required after the upgrade.
=> Upgrade prettier to v1.19

README.md
Fixes https://github.com/votingworks/arlo/issues/1622
=> README: fix link to Auth0 docs

scripts/restore-db-backup.sh
Having to enter it every time was annoying.
=> Add non-secret password to scripts/restore-db-backup.sh

.husky/pre-commit, client/.gitignore, client/package.json, client/src/components/AuditAdmin/AuditAdminView.test.tsx, client/src/components/AuditAdmin/Setup/Contests/HybridContestForm.test.tsx, client/src/components/testUtilities.tsx, client/tsconfig.json, client/yarn.lock, package.json, yarn.lock
_Review by commits_
(╯°□°）╯︵ ┻━┻
A variety of tweaks found in various internet sources. Brings average pre-commit hook time down from >1m to <10s on my machine.
=> Speed up pre-commit checks

client/src/App.tsx, client/src/components/HomeScreen.test.tsx, client/src/components/HomeScreen.tsx, client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundSteps.test.tsx, client/src/components/testUtilities.tsx
See comment in the diff for explanation.
=> Set query client stale time to 1s

client/cypress/end-to-end/batch-comparison.cy.js, client/src/components/Atoms/CodeInput.test.tsx, client/src/components/Atoms/CodeInput.tsx, client/src/components/AuditAdmin/Setup/Contests/__snapshots__/Contests.test.tsx.snap, client/src/components/AuditAdmin/Setup/Contests/__snapshots__/HybridContestForm.test.tsx.snap, client/src/components/AuditAdmin/Setup/__snapshots__/Setup.test.tsx.snap, client/src/components/AuditBoard/__snapshots__/AuditBoardView.test.tsx.snap, client/src/components/JurisdictionAdmin/BatchRoundSteps/BatchRoundSteps.test.tsx, client/src/components/JurisdictionAdmin/BatchRoundSteps/TallyEntryAccountsStep.tsx, client/src/components/JurisdictionAdmin/__snapshots__/JurisdictionAdminView.test.tsx.snap, client/src/components/JurisdictionAdmin/__snapshots__/RoundManagement.test.tsx.snap, client/src/components/testUtilities.tsx
Adds a custom input component for login codes that shows one text input per digit.
https://user-images.githubusercontent.com/530106/197087212-2c84f58c-ae59-47a4-8cc8-26c2abf34dc8.mov
=> Fancy login code input

server/api/cvrs.py, server/tests/ballot_comparison/test_cvrs.py
The arranging of field names and values in the sentence was a bit confusing.
=> Improve wording of error message when CVR batch doesn't match manifest

server/api/activity.py, server/api/elections.py, server/api/public.py, server/app.py, server/auth/auth_helpers.py, server/auth/auth_routes.py, server/static.py
Closes #1665 
Ensures that every route has an access control decorator applied. Details in the individual commits.
=> Ensure access control on all routes

client/src/components/JurisdictionAdmin/RoundManagement.tsx, client/src/components/JurisdictionAdmin/RoundProgress.tsx, client/src/components/JurisdictionAdmin/__snapshots__/RoundProgress.test.tsx.snap
=> Fix flex styling on JM round management screen

server/api/batch_inventory.py, server/tests/batch_comparison/snapshots/snap_test_batch_inventory.py
=> Update batch inventory worksheet copy

client/src/components/Atoms/CSVForm.tsx, client/src/components/TallyEntryUser/TallyEntryUserView.test.tsx
=> Fix spacing of CVR type input

client/src/components/JurisdictionAdmin/JurisdictionAdminView.test.tsx, client/src/components/JurisdictionAdmin/JurisdictionAdminView.tsx
=> Show a message to JMs when they are done with audit setup

server/api/batch_inventory.py, server/tests/batch_comparison/snapshots/snap_test_batch_inventory.py, server/tests/batch_comparison/test_batch_inventory.py
=> Revert "Batch inventory: aggregate write-ins from CVRs"

client/src/components/Atoms/CodeInput.test.tsx, client/src/components/Atoms/CodeInput.tsx
Just realized out of the blue that we didn't support this. It's probably not a huge deal, but it was quick to add.
=> Allow pasting into CodeInput

client/src/components/Atoms/StatusBox.test.tsx, client/src/components/Atoms/StatusBox.tsx, client/src/components/AuditAdmin/Setup/Review/Review.tsx, client/src/components/AuditAdmin/Setup/Review/useSampleSizes.ts, client/src/components/utilities.test.ts, client/src/components/utilities.ts
I made this change while working on debugging the timers tests (https://github.com/votingworks/arlo/pull/1724) because I thought there was something weird going on with the polling. Turned out that wasn't the issue, but since this was already done, might as well move forward with it.
=> Use react-query for useSampleSizes

Makefile, app.json
Tracks changes relevant to #1502.
=> Bumping versions to satisfy new Heroku stack

client/package.json, client/run-cypress-tests.sh, client/yarn.lock, server/tests/audit_math/test_minerva2.py
This test assertion was off by a tiny fraction in my dev env today, so I added some tolerance (a similar approach is used elsewhere in this file).
=> Add tolerance for floating point in Minerva test

server/api/batch_inventory.py, server/api/cvrs.py, server/tests/batch_comparison/conftest.py, server/tests/batch_comparison/snapshots/snap_test_batch_inventory.py, server/tests/batch_comparison/test_batch_inventory.py
This PR updates the batch inventory flow that we built for Georgia to support multi-contest batch audits. After we deploy this, we can fully close out https://github.com/votingworks/arlo/issues/1815.
=> Update batch inventory flow to support multi-contest batch audits

arlo.code-workspace
🙈 Didn't mean to commit setting this to `false` in https://github.com/votingworks/arlo/commit/f09f16983647d8d3cda02e682fe62dea1e90d350
=> Re-enable formatting on save

poetry.lock, pyproject.toml
The poetry export command was failing. I did some debugging of the poetry code and this seemed to fix it - seems like a bug on their end.
=> Fix build by adding branch reference for consistent_sampler

server/tests/ballot_comparison/snapshots/snap_test_cvrs.py
Somehow it seems like a bunch of snapshots for test_cvrs.py got deleted. When I run the tests on `main`, they added a bunch of snapshot data as if the snapshots had never been created at all. I'm not sure what happened, but since we haven't actually modified code related to these tests, I'm ok with just updating the snapshots to the current result of running the tests.
=> Update missing snapshots

README.md
Also remove outdated psycopg-binary note
=> README: Add instructions about adding poetry to PATH

Makefile
Thought this was a common enough task to be useful to add an alias for
=> Add migratedb make directive

server/api/shared.py
The current logic for combined batches allows a non-RLA batch to be the "representative batch" for the combined batch (when using the feature flag to sample extra batches). This means that audit results for the combined batch are associated with that representative batch in the db.
However, we filter out non-RLA batches when querying the batch results in the db for calculating the risk measurement to avoid accidentally including them in the calculation. This caused an error if a non-RLA batch was the representative batch, since the results for the entire combined batch would be missing.
Luckily, it turns out that the risk measurement calculation [uses a different data source](https://github.com/votingworks/arlo/blob/jonah/fix-combined-batches-with-extra-batches/server/audit_math/macro.py#L …
=> Fix risk measurement calculation for combined batches with non-RLA batches

server/api/shared.py
We had to remove this filtering in https://github.com/votingworks/arlo/pull/2075 to fix a bug related to how combined batches interacted with extra sampled batches. Technically, this filtering isn't necessary, since the audit math uses the ticket number dict as the source of truth for which batches to include in the p-value calculation. However, it's nice to have multiple guards in place like we did previously rather than depend on that implementation detail for safety.
=> Add filter for extra batches to sampled batch results query

client/src/components/Atoms/CSVForm.tsx, client/src/components/JurisdictionAdmin/BatchInventory.tsx, client/src/components/useCSV.ts, client/src/components/useFeatureFlag.ts, server/api/batch_inventory.py, server/auth/auth_routes.py, server/models.py, server/tests/helpers.py, server/tests/util/test_collections.py, server/tests/util/test_cvr_snapshot_parse.py, server/tests/util/test_file_storage.py, server/util/collections.py, server/util/cvr_snapshot_parse.py, server/util/file.py
Closes #2154
https://github.com/user-attachments/assets/f8fc5f14-8ebe-4257-a1b1-5d42e1e1c364
=> feat(batch-prep-tool): add support for ES&S CVR snapshots as used in MD

scripts/create-admin.py, scripts/resetdb.py, server/api/ballots.py, server/api/batches.py, server/api/reports.py, server/audit_math/minerva.py, server/audit_math/raire.py, server/audit_math/raire_utils.py, server/tests/api/test_audit_boards.py, server/tests/api/test_ballot_manifest.py, server/tests/api/test_contests.py, server/tests/api/test_jurisdictions.py, server/tests/api/test_jurisdictions_file.py, server/tests/ballot_comparison/test_cvrs.py, server/tests/batch_comparison/test_batch_tallies.py, server/tests/conftest.py, server/tests/test_auth.py, server/tests/test_full_hand_tally.py, server/tests/test_multi_winner_contest.py, server/tests/test_multiple_targeted_contests.py, server/tests/util/test_csv_parse.py, server/util/csv_parse.py, stubs/consistent_sampler/__init__.pyi
I'd like to switch from `pylint` to `ruff`, but before doing that I'm just applying the autofixes that don't break Arlo.
=> style: apply simple `ruff` fixes

poetry.lock, pyproject.toml, server/tests/test_auth.py, server/tests/test_errors.py, server/tests/test_websessions.py, server/websession.py
=> chore(deps): update `flask` and related dependencies
